DECLARE @loop int = (SELECT COUNT(baseid) FROM mbs..bases);
DECLARE @i int = 0; 
DECLARE @empresa nvarchar(MAX);
DECLARE @pathORCT nvarchar(MAX);
DECLARE @pathOCRG nvarchar(MAX);
DECLARE @pathRCT2 nvarchar(MAX);
DECLARE @pathOINV nvarchar(MAX);
DECLARE @pathORIN nvarchar(MAX);
DECLARE @pathINV1 nvarchar(MAX);
DECLARE @pathRIN1 nvarchar(MAX);
DECLARE @pathODPI nvarchar(MAX);
DECLARE @pathRCT3 nvarchar(MAX);
DECLARE @pathOACT nvarchar(MAX);
DECLARE @pathOCRD nvarchar(MAX);
DECLARE @pathCRD7 nvarchar(MAX);
DECLARE @pathFT_ORCA nvarchar(MAX);
DECLARE @pathFT_OHRQ nvarchar(MAX);

DROP TABLE ##fluxoreceber

CREATE TABLE ##fluxoreceber(
	[BASE] [nvarchar](50) NULL,
	[CNPJ] [nvarchar](50) NULL,
	[FILIAL] [nvarchar](200) NULL,
	[DOCCR] [nvarchar](15) NULL,
	[DOCNFS] [nvarchar](15) NULL,
	[NUMNFS] [nvarchar](15) NULL,
	[FORMA_PGTO] [nvarchar](15) NULL,
	[DTFATNFS] [nvarchar](20) NULL,
	[DTVENCNFS] [nvarchar](20) NULL,
	[DTRECEB] [nvarchar](20) NULL,
	[CODPN] [nvarchar](15) NULL,
	[NOMEPN] [nvarchar](100) NULL,
	[TIPODOC] [nvarchar](20) NULL,
	[VLRNFS] [float] NULL,
	[VLRDOCCR] [float](15) NULL,
	[PARCELA] [nvarchar](15) NULL,
	[PARCELAS] [nvarchar](15) NULL,
	[CONTACOD] [nvarchar](15) NULL,
	[CONTANOME] [nvarchar](100) NULL,
	[OBSERVACAO] [nvarchar](MAX) NULL
) ON [PRIMARY]


while @i < @loop
	begin
		set @i = @i + 1;
		set @empresa = (select empresa from mbs..bases where baseid = @i)

		set @pathORCT = CONCAT(N'CREATE SYNONYM tpathORCT FOR ',@empresa,N'.DBO.ORCT');
		set @pathOCRG = CONCAT(N'CREATE SYNONYM tpathOCRG FOR ',@empresa,N'.DBO.OCRG');
		set @pathRCT2 = CONCAT(N'CREATE SYNONYM tpathRCT2 FOR ',@empresa,N'.DBO.RCT2');
		set @pathOINV = CONCAT(N'CREATE SYNONYM tpathOINV FOR ',@empresa,N'.DBO.OINV');
		set @pathORIN = CONCAT(N'CREATE SYNONYM tpathORIN FOR ',@empresa,N'.DBO.ORIN');
		set @pathINV1 = CONCAT(N'CREATE SYNONYM tpathINV1 FOR ',@empresa,N'.DBO.INV1');
		set @pathRIN1 = CONCAT(N'CREATE SYNONYM tpathRIN1 FOR ',@empresa,N'.DBO.RIN1');
		set @pathODPI = CONCAT(N'CREATE SYNONYM tpathODPI FOR ',@empresa,N'.DBO.ODPI');
		set @pathRCT3 = CONCAT(N'CREATE SYNONYM tpathRCT3 FOR ',@empresa,N'.DBO.RCT3');
		set @pathOACT = CONCAT(N'CREATE SYNONYM tpathOACT FOR ',@empresa,N'.DBO.OACT');
		set @pathOCRD = CONCAT(N'CREATE SYNONYM tpathOCRD FOR ',@empresa,N'.DBO.OCRD');
		set @pathCRD7 = CONCAT(N'CREATE SYNONYM tpathCRD7 FOR ',@empresa,N'.DBO.CRD7');
		set @pathFT_ORCA = CONCAT(N'CREATE SYNONYM tpathFT_ORCA FOR ',@empresa,N'.DBO.[@FT_ORCA]');
		set @pathFT_OHRQ = CONCAT(N'CREATE SYNONYM tpathFT_OHRQ FOR ',@empresa,N'.DBO.[@FT_OHRQ]');

		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathORCT') > 0 BEGIN DROP SYNONYM tpathORCT; EXEC(@pathORCT); END ELSE BEGIN exec(@pathORCT); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathOCRG') > 0 BEGIN DROP SYNONYM tpathOCRG; EXEC(@pathOCRG); END ELSE BEGIN exec(@pathOCRG); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathRCT2') > 0 BEGIN DROP SYNONYM tpathRCT2; EXEC(@pathRCT2); END ELSE BEGIN exec(@pathRCT2); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathOINV') > 0 BEGIN DROP SYNONYM tpathOINV; EXEC(@pathOINV); END ELSE BEGIN exec(@pathOINV); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathORIN') > 0 BEGIN DROP SYNONYM tpathORIN; EXEC(@pathORIN); END ELSE BEGIN exec(@pathORIN); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathINV1') > 0 BEGIN DROP SYNONYM tpathINV1; EXEC(@pathINV1); END ELSE BEGIN exec(@pathINV1); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathRIN1') > 0 BEGIN DROP SYNONYM tpathRIN1; EXEC(@pathRIN1); END ELSE BEGIN exec(@pathRIN1); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathODPI') > 0 BEGIN DROP SYNONYM tpathODPI; EXEC(@pathODPI); END ELSE BEGIN exec(@pathODPI); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathRCT3') > 0 BEGIN DROP SYNONYM tpathRCT3; EXEC(@pathRCT3); END ELSE BEGIN exec(@pathRCT3); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathOACT') > 0 BEGIN DROP SYNONYM tpathOACT; EXEC(@pathOACT); END ELSE BEGIN exec(@pathOACT); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathOCRD') > 0 BEGIN DROP SYNONYM tpathOCRD; EXEC(@pathOCRD); END ELSE BEGIN exec(@pathOCRD); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathCRD7') > 0 BEGIN DROP SYNONYM tpathCRD7; EXEC(@pathCRD7); END ELSE BEGIN exec(@pathCRD7); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathFT_ORCA') > 0 BEGIN DROP SYNONYM tpathFT_ORCA; EXEC(@pathFT_ORCA); END ELSE BEGIN exec(@pathFT_ORCA); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathFT_OHRQ') > 0 BEGIN DROP SYNONYM tpathFT_OHRQ; EXEC(@pathFT_OHRQ); END ELSE BEGIN exec(@pathFT_OHRQ); END
		
		
INSERT INTO ##fluxoreceber
	SELECT 
		@empresa BASE, 
		isnull((select top 1 r.lictradnum from tpathOCRD r where r.cardcode = R0.cardcode),(select max(case when not (d.taxid0 = '' or d.taxid0 is null) then d.taxid0 else case when not (d.taxid4 = '' or d.taxid4 is null) then d.taxid4 else '' end end) from tpathCRD7 d where d.cardcode = R0.cardcode)) CPF_CNPJ, 
		COALESCE(R0.BPLNAME,REPLACE(@empresa,'SBO','')) FILIAL,
		R0.DOCNUM DOCCR, 
		R2.DOCENTRY DOCNFS, 
		CASE
			WHEN R2.INVTYPE = 13 THEN V0.SERIAL
			WHEN R2.INVTYPE = 14 THEN D0.SERIAL
			WHEN R2.INVTYPE = 24 THEN 0
			WHEN R2.INVTYPE = 203 THEN 0
			ELSE 0
		END NUMNFS,
		CASE
			WHEN DdctSumSy > 0 THEN '###DEDUCTION###'
			WHEN CashSumSy > 0 THEN 'DINHEIRO'
			WHEN CredSumSy > 0 THEN 'CARTAO'
			WHEN CheckSumSy> 0 THEN 'CHEQUE'
			WHEN TrsfrSumSy> 0 THEN 'TRANSFERENCIA'
			WHEN NoDocSumSy> 0 THEN '###NO_DOC###'
			ELSE 'X'
		END FORMA_PGTO,
		CASE
			WHEN R2.INVTYPE = 13 THEN CAST(V0.DOCDATE AS DATE)
			WHEN R2.INVTYPE = 14 THEN CAST(D0.DOCDATE AS DATE)
			WHEN R2.INVTYPE = 24 THEN CAST(R0.DOCDATE AS DATE)
			WHEN R2.INVTYPE = 203 THEN CAST(A0.DOCDATE AS DATE)
			ELSE CAST(R0.DOCDATE AS DATE)
		END DTFATNFS,
		CASE
			WHEN R2.INVTYPE = 13 THEN CAST(V0.DOCDUEDATE AS DATE)
			WHEN R2.INVTYPE = 14 THEN CAST(D0.DOCDUEDATE AS DATE)
			WHEN R2.INVTYPE = 24 THEN CAST(R0.DOCDUEDATE AS DATE)
			WHEN R2.INVTYPE = 203 THEN CAST(A0.DOCDUEDATE AS DATE)
			ELSE CAST(R0.DOCDUEDATE AS DATE)
		END DTVENCNFS,
		CAST(R0.DOCDATE AS DATE) DTRECEB, 
		R0.CARDCODE CODPN, 
		R0.CARDNAME NOMEPN, 
		CASE
			WHEN R2.INVTYPE = 13 THEN 'FAT_NFS'
			WHEN R2.INVTYPE = 14 THEN 'DEV_NFS'
			WHEN R2.INVTYPE = 24 THEN 'CONTAS_RECEBER'
			WHEN R2.INVTYPE = 203 THEN 'ADIANTAMENTO'
			ELSE R2.INVTYPE
		END TIPODOC,
		ROUND(CASE
			WHEN R2.INVTYPE = 13 THEN CAST(V0.MAX1099 AS FLOAT)/V0.INSTALLMNT
			WHEN R2.INVTYPE = 14 THEN -CAST(D0.MAX1099 AS FLOAT)/D0.INSTALLMNT
			ELSE CAST(R0.DocTotalSy/(SELECT COUNT(DOCTRANSID) FROM tpathRCT2 WHERE DOCTRANSID = R2.DOCTRANSID) AS FLOAT)
		END,-1) VLRNFS,
		ROUND(CASE WHEN R2.INVTYPE = 14 THEN -CAST(R2.APPLIEDSYS AS FLOAT) ELSE CAST(R2.APPLIEDSYS AS FLOAT) END,-1) VLRDOCCR,
		R2.INSTID PARCELA,
		CASE
			WHEN R2.INVTYPE = 13 THEN V0.INSTALLMNT
			WHEN R2.INVTYPE = 14 THEN D0.INSTALLMNT
			ELSE (SELECT COUNT(DOCTRANSID) FROM tpathRCT2 WHERE DOCTRANSID = R2.DOCTRANSID)
		END PARCELAS,
		CASE
			WHEN R2.INVTYPE = 13 THEN (SELECT TOP 1 V1.ACCTCODE FROM tpathINV1 V1 WHERE V1.DOCENTRY = V0.DOCENTRY)
			WHEN R2.INVTYPE = 14 THEN (SELECT TOP 1 D1.ACCTCODE FROM tpathRIN1 D1 WHERE D1.DOCENTRY = D0.DOCENTRY)
			WHEN R2.INVTYPE = 203 THEN A0.CtlAccount
			ELSE COALESCE(COALESCE(COALESCE(NULLIF(R0.CASHACCT,''),NULLIF(R0.TRSFRACCT,'')),NULLIF(R0.CHECKACCT,'')),R0.BPACT)
		END CONTACOD,
		(SELECT ACCTNAME FROM tpathOACT WHERE ACCTCODE LIKE
																		CASE
																			WHEN R2.INVTYPE = 13 THEN (SELECT TOP 1 V1.ACCTCODE FROM tpathINV1 V1 WHERE V1.DOCENTRY = V0.DOCENTRY)
																			WHEN R2.INVTYPE = 14 THEN (SELECT TOP 1 D1.ACCTCODE FROM tpathRIN1 D1 WHERE D1.DOCENTRY = D0.DOCENTRY)
																			WHEN R2.INVTYPE = 203 THEN A0.CtlAccount
																			ELSE COALESCE(COALESCE(COALESCE(NULLIF(R0.CASHACCT,''),NULLIF(R0.TRSFRACCT,'')),NULLIF(R0.CHECKACCT,'')),R0.BPACT)
																		END ) CONTANOME,
		CASE
			WHEN R2.INVTYPE = 13 THEN CONCAT(REPLACE(REPLACE(REPLACE(V0.COMMENTS,CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),' | ',V0.JrnlMemo)
			WHEN R2.INVTYPE = 14 THEN CONCAT(REPLACE(REPLACE(REPLACE(D0.COMMENTS,CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),' | ',D0.JrnlMemo)
			ELSE R0.JrnlMemo
		END OBSERVACAO
	FROM 
		tpathORCT R0 INNER JOIN
		tpathRCT2 R2 ON R2.DOCNUM = R0.DOCNUM LEFT JOIN
		tpathOINV V0 ON V0.TRANSID = R2.DOCTRANSID LEFT JOIN
		tpathORIN D0 ON D0.TRANSID = R2.DOCTRANSID LEFT JOIN
		tpathODPI A0 ON A0.TRANSID = R2.DOCTRANSID LEFT JOIN
		tpathRCT3 R3 ON R3.DocNum = R0.DOCNUM
	WHERE 
		YEAR(R0.DOCDATE) = 2020 and
		(select G.GROUPNAME from tpathOCRG g where g.groupcode = (select groupcode from tpathOCRD r where cardcode = R0.CARDCODE)) NOT LIKE '%ligada%' -- sem coligadas

end;	  

UPDATE ##fluxoreceber SET BASE = 
									CASE	
										WHEN BASE = 'SBOEquilibrium' THEN 'EQL'
										WHEN BASE = 'SBOVidafarma' THEN 'VDM'
										ELSE BASE
									END


DROP TABLE MBS..politicacredito003

--005. TABELA COMPLEMENTAR DE CALCULO DOS ATRASOS MEDIOS PONDERADOS DO CLIENTE DURANTE O ANO DE 2020, EXCLUINDO-SE AS EMPRESAS COLIGADAS;
CREATE TABLE MBS..politicacredito003(
	[BASE] [nvarchar](50) NULL,
	[CNPJ] [nvarchar](50) NULL,
	[FILIAL] [nvarchar](200) NULL,
	[DOCCR] [nvarchar](15) NULL,
	[DOCNFS] [nvarchar](15) NULL,
	[NUMNFS] [nvarchar](15) NULL,
	[FORMA_PGTO] [nvarchar](15) NULL,
	[DTFATNFS] [nvarchar](20) NULL,
	[DTVENCNFS] [nvarchar](20) NULL,
	[DTRECEB] [nvarchar](20) NULL,
	[CODPN] [nvarchar](15) NULL,
	[NOMEPN] [nvarchar](100) NULL,
	[TIPODOC] [nvarchar](20) NULL,
	[VLRNFS] [float] NULL,
	[VLRDOCCR] [float](15) NULL,
	[PARCELA] [nvarchar](15) NULL,
	[PARCELAS] [nvarchar](15) NULL,
	[CONTACOD] [nvarchar](15) NULL,
	[CONTANOME] [nvarchar](100) NULL,
	[OBSERVACAO] [nvarchar](MAX) NULL,
	[ATRASO] [int] NULL
) ON [PRIMARY]


INSERT INTO MBS..politicacredito003
	select 
		*, 
		CASE WHEN CONVERT(INT,(CONVERT(DATETIME,DTRECEB) - CONVERT(DATETIME,DTVENCNFS))) < 6 THEN 0 ELSE CONVERT(INT,(CONVERT(DATETIME,DTRECEB) - CONVERT(DATETIME,DTVENCNFS))) END ATRASO
	from 
		##fluxoreceber 
	WHERE BASE IN ('EQL','VDM') AND 
	LEFT(CONTACOD,1) = '3' 



DROP TABLE [Mbs].[dbo].[politicacredito006]

--006. TABELA COMPLEMENTAR QUE AGRUPA OS PRINCIPAIS CAMPOS A SEREM UTILIZADOS NO ITEM 007 E QUE DETERMINA O ATRASO MEDIO PONDERADO E O FATOR DE CORRECAO MEDIO PUNITIVO POR CNPJ;
CREATE TABLE [Mbs].[dbo].[politicacredito006](
	[CPF_CNPJ] [nvarchar](50) NULL,
	[ATRASOMEDIO] [int] NULL,
	[FCMEDIO] [float] NULL
) ON [PRIMARY]

INSERT INTO [Mbs].[dbo].[politicacredito006]
	SELECT 
		 [CNPJ]
		,ROUND(AVG([ATRASO]),0) ATRASOMEDIO
		,CONVERT(FLOAT,
			CASE
				WHEN ROUND(AVG([ATRASO]),0) < 6  THEN 1.50
				WHEN ROUND(AVG([ATRASO]),0) < 11 THEN 1.40
				WHEN ROUND(AVG([ATRASO]),0) < 16 THEN 1.30
				WHEN ROUND(AVG([ATRASO]),0) < 21 THEN 1.20
				WHEN ROUND(AVG([ATRASO]),0) < 26 THEN 1.10
				WHEN ROUND(AVG([ATRASO]),0) < 31 THEN 1.00
				WHEN ROUND(AVG([ATRASO]),0) < 46 THEN 0.90
				WHEN ROUND(AVG([ATRASO]),0) < 61 THEN 0.75
				WHEN ROUND(AVG([ATRASO]),0) < 76 THEN 0.50
				WHEN ROUND(AVG([ATRASO]),0) < 91 THEN 0.25
				ELSE 0
			END) FCMEDIO --006-01. TABELA DE CONVERSAO REGRESSIVA PUNITIVA PARA ATRIBUIR PERCENTUAIS DE REDUCAO DO FATOR 1.5X ORIGINAL EM FUNCAO DOS ATRASOS DETECTADOS NO RECEBIMENTO;
	FROM [Mbs].[dbo].[politicacredito003]
	GROUP BY [CNPJ]

