DECLARE @loop int = (SELECT COUNT(baseid) FROM mbs..bases);
DECLARE @i int = 0; 
DECLARE @empresa nvarchar(MAX);
DECLARE @pathOVPM nvarchar(MAX);
DECLARE @pathVPM2 nvarchar(MAX);
DECLARE @pathOINV nvarchar(MAX);
DECLARE @pathORIN nvarchar(MAX);
DECLARE @pathOPCH nvarchar(MAX);
DECLARE @pathORPC nvarchar(MAX);
DECLARE @pathPCH1 nvarchar(MAX);
DECLARE @pathRPC1 nvarchar(MAX);
DECLARE @pathINV1 nvarchar(MAX);
DECLARE @pathRIN1 nvarchar(MAX);
DECLARE @pathODPO nvarchar(MAX);
DECLARE @pathVPM3 nvarchar(MAX);
DECLARE @pathOACT nvarchar(MAX);
DECLARE @pathFT_ORCA nvarchar(MAX);
DECLARE @pathFT_OHRQ nvarchar(MAX);

DROP TABLE [MBS].[dbo].[FLUXOP]

CREATE TABLE [MBS].[dbo].[FLUXOP](
	[ORIGEM] [nvarchar](8) NULL,
	[BASE] [nvarchar](50) NULL,
	[FILIAL] [nvarchar](200) NULL,
	[DOCCP] [nvarchar](15) NULL,
	[DOCNFE] [nvarchar](15) NULL,
	[NUMNFE] [nvarchar](15) NULL,
	[TRANSIDCP] [nvarchar](15) NULL,
	[TRANSIDNFE] [nvarchar](15) NULL,
	[SUPERVISOR] [nvarchar](100) NULL,
	[FORMA_PGTO] [nvarchar](15) NULL,
	[DTFATNFE] [nvarchar](20) NULL,
	[DTVENCNFE] [nvarchar](20) NULL,
	[DTPGTO] [nvarchar](20) NULL,
	[CODPN] [nvarchar](15) NULL,
	[NOMEPN] [nvarchar](100) NULL,
	[TIPODOC] [nvarchar](20) NULL,
	[VLRNFE] [float] NULL,
	[VLRDOCCP] [float](15) NULL,
	[PARCELA] [nvarchar](15) NULL,
	[PARCELAS] [nvarchar](15) NULL,
	[CONTACOD] [nvarchar](15) NULL,
	[CONTANOME] [nvarchar](100) NULL,
	[OBSERVACAO] [nvarchar](MAX) NULL
) ON [PRIMARY]

while @i < @loop
	begin
		set @i = @i + 1;
		set @empresa = (select empresa from mbs..bases where baseid = @i)

		set @pathOVPM = CONCAT(N'CREATE SYNONYM tpathOVPM FOR ',@empresa,N'.DBO.OVPM');
		set @pathVPM2 = CONCAT(N'CREATE SYNONYM tpathVPM2 FOR ',@empresa,N'.DBO.VPM2');
		set @pathOINV = CONCAT(N'CREATE SYNONYM tpathOINV FOR ',@empresa,N'.DBO.OINV');
		set @pathORIN = CONCAT(N'CREATE SYNONYM tpathORIN FOR ',@empresa,N'.DBO.ORIN');
		set @pathINV1 = CONCAT(N'CREATE SYNONYM tpathINV1 FOR ',@empresa,N'.DBO.INV1');
		set @pathRIN1 = CONCAT(N'CREATE SYNONYM tpathRIN1 FOR ',@empresa,N'.DBO.RIN1');

		set @pathOPCH = CONCAT(N'CREATE SYNONYM tpathOPCH FOR ',@empresa,N'.DBO.OPCH');
		set @pathORPC = CONCAT(N'CREATE SYNONYM tpathORPC FOR ',@empresa,N'.DBO.ORPC');
		set @pathPCH1 = CONCAT(N'CREATE SYNONYM tpathPCH1 FOR ',@empresa,N'.DBO.PCH1');
		set @pathRPC1 = CONCAT(N'CREATE SYNONYM tpathRPC1 FOR ',@empresa,N'.DBO.RPC1');

		set @pathODPO = CONCAT(N'CREATE SYNONYM tpathODPO FOR ',@empresa,N'.DBO.ODPO');
		set @pathVPM3 = CONCAT(N'CREATE SYNONYM tpathVPM3 FOR ',@empresa,N'.DBO.VPM3');
		set @pathOACT = CONCAT(N'CREATE SYNONYM tpathOACT FOR ',@empresa,N'.DBO.OACT');
		set @pathFT_ORCA = CONCAT(N'CREATE SYNONYM tpathFT_ORCA FOR ',@empresa,N'.DBO.[@FT_ORCA]');
		set @pathFT_OHRQ = CONCAT(N'CREATE SYNONYM tpathFT_OHRQ FOR ',@empresa,N'.DBO.[@FT_OHRQ]');

		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathOVPM') > 0 BEGIN DROP SYNONYM tpathOVPM; EXEC(@pathOVPM); END ELSE BEGIN exec(@pathOVPM); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathVPM2') > 0 BEGIN DROP SYNONYM tpathVPM2; EXEC(@pathVPM2); END ELSE BEGIN exec(@pathVPM2); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathOPCH') > 0 BEGIN DROP SYNONYM tpathOPCH; EXEC(@pathOPCH); END ELSE BEGIN exec(@pathOPCH); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathORPC') > 0 BEGIN DROP SYNONYM tpathORPC; EXEC(@pathORPC); END ELSE BEGIN exec(@pathORPC); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathPCH1') > 0 BEGIN DROP SYNONYM tpathPCH1; EXEC(@pathPCH1); END ELSE BEGIN exec(@pathPCH1); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathRPC1') > 0 BEGIN DROP SYNONYM tpathRPC1; EXEC(@pathRPC1); END ELSE BEGIN exec(@pathRPC1); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathOINV') > 0 BEGIN DROP SYNONYM tpathOINV; EXEC(@pathOINV); END ELSE BEGIN exec(@pathOINV); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathORIN') > 0 BEGIN DROP SYNONYM tpathORIN; EXEC(@pathORIN); END ELSE BEGIN exec(@pathORIN); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathINV1') > 0 BEGIN DROP SYNONYM tpathINV1; EXEC(@pathINV1); END ELSE BEGIN exec(@pathINV1); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathRIN1') > 0 BEGIN DROP SYNONYM tpathRIN1; EXEC(@pathRIN1); END ELSE BEGIN exec(@pathRIN1); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathODPO') > 0 BEGIN DROP SYNONYM tpathODPO; EXEC(@pathODPO); END ELSE BEGIN exec(@pathODPO); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathVPM3') > 0 BEGIN DROP SYNONYM tpathVPM3; EXEC(@pathVPM3); END ELSE BEGIN exec(@pathVPM3); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathOACT') > 0 BEGIN DROP SYNONYM tpathOACT; EXEC(@pathOACT); END ELSE BEGIN exec(@pathOACT); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathFT_ORCA') > 0 BEGIN DROP SYNONYM tpathFT_ORCA; EXEC(@pathFT_ORCA); END ELSE BEGIN exec(@pathFT_ORCA); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathFT_OHRQ') > 0 BEGIN DROP SYNONYM tpathFT_OHRQ; EXEC(@pathFT_OHRQ); END ELSE BEGIN exec(@pathFT_OHRQ); END
		
		
	INSERT INTO [MBS].[dbo].[FLUXOP]
		SELECT 
			'CPAGAR' ORIGEM,
			@empresa BASE, 
			COALESCE(R0.BPLNAME,REPLACE(@empresa,'SBO','')) FILIAL,
			R0.DOCNUM DOCCR, 
			R2.DOCENTRY DOCNFS, 
			CASE
				WHEN R2.INVTYPE = 13 THEN V0.SERIAL
				WHEN R2.INVTYPE = 14 THEN D0.SERIAL
				WHEN R2.INVTYPE = 18 THEN C0.SERIAL
				WHEN R2.INVTYPE = 19 THEN DC0.SERIAL
				WHEN R2.INVTYPE = 24 THEN 0
				WHEN R2.INVTYPE = 204 THEN 0
				ELSE 0
			END NUMNFS,
			R0.TRANSID TRANSIDCR, 
			R2.DOCTRANSID TRANSIDNFS, 
			CASE
				WHEN R2.INVTYPE = 13 THEN COALESCE(NULLIF(Z1.NAME,''),'SEM_SUPERVISOR')
				WHEN R2.INVTYPE = 14 THEN COALESCE(NULLIF(Z2.NAME,''),'SEM_SUPERVISOR')
				WHEN R2.INVTYPE = 18 THEN COALESCE(NULLIF(H1.NAME,''),'SEM_SUPERVISOR')
				WHEN R2.INVTYPE = 19 THEN COALESCE(NULLIF(H2.NAME,''),'SEM_SUPERVISOR')
				ELSE 'SEM_SUPERVISOR'
			END SUPERVISOR,	
			CASE
				WHEN DdctSumSy > 0 THEN '###DEDUCTION###'
				WHEN CashSumSy > 0 THEN 'DINHEIRO'
				WHEN CredSumSy > 0 THEN 'CARTAO'
				WHEN CheckSumSy> 0 THEN 'CHEQUE'
				WHEN TrsfrSumSy> 0 THEN 'TRANSFERENCIA'
				WHEN NoDocSumSy> 0 THEN '###NO_DOC###'
				ELSE 'X'
			END FORMA_PGTO,
			CASE
				WHEN R2.INVTYPE = 13 THEN CAST(V0.DOCDATE AS DATE)
				WHEN R2.INVTYPE = 14 THEN CAST(D0.DOCDATE AS DATE)
				WHEN R2.INVTYPE = 18 THEN CAST(C0.DOCDATE AS DATE)
				WHEN R2.INVTYPE = 19 THEN CAST(DC0.DOCDATE AS DATE)
				WHEN R2.INVTYPE = 204 THEN CAST(A0.DOCDATE AS DATE)
				ELSE CAST(R0.DOCDATE AS DATE)
			END DTFATNFE,
			CASE
				WHEN R2.INVTYPE = 13 THEN CAST(V0.DOCDUEDATE AS DATE)
				WHEN R2.INVTYPE = 14 THEN CAST(D0.DOCDUEDATE AS DATE)
				WHEN R2.INVTYPE = 18 THEN CAST(C0.DOCDUEDATE AS DATE)
				WHEN R2.INVTYPE = 19 THEN CAST(DC0.DOCDUEDATE AS DATE)
				WHEN R2.INVTYPE = 204 THEN CAST(A0.DOCDUEDATE AS DATE)
				ELSE CAST(R0.DOCDUEDATE AS DATE)
			END DTVENCNFE,
			CAST(R0.DOCDATE AS DATE) DTPGTO, 
			R0.CARDCODE CODPN, 
			R0.CARDNAME NOMEPN, 
			CASE
				WHEN R2.INVTYPE = 13 THEN 'FAT_NFS'
				WHEN R2.INVTYPE = 14 THEN 'DEV_NFS'		
				WHEN R2.INVTYPE = 18 THEN 'CMP_NFE'
				WHEN R2.INVTYPE = 19 THEN 'DEV_NFE'
				WHEN R2.INVTYPE = 24 THEN 'CONTAS_PAGAR'	
				WHEN R2.INVTYPE = 30 THEN 'LANC_MANUAL'	
				WHEN R2.INVTYPE = 204 THEN 'ADIANTAMENTO F'
				ELSE R2.INVTYPE
			END TIPODOC,
			CASE
				WHEN R2.INVTYPE = 13 THEN -CAST(V0.MAX1099 AS FLOAT)/V0.INSTALLMNT
				WHEN R2.INVTYPE = 14 THEN CAST(D0.MAX1099 AS FLOAT)/D0.INSTALLMNT
				WHEN R2.INVTYPE = 18 THEN CAST(C0.MAX1099 AS FLOAT)/C0.INSTALLMNT
				WHEN R2.INVTYPE = 19 THEN -CAST(DC0.MAX1099 AS FLOAT)/DC0.INSTALLMNT
				ELSE CAST(R0.DocTotalSy/(SELECT COUNT(DOCTRANSID) FROM tpathVPM2 WHERE DOCTRANSID = R2.DOCTRANSID) AS FLOAT)
			END VLRNFE,
			CASE WHEN (R2.INVTYPE = 13 OR R2.INVTYPE = 19) THEN -CAST(R2.APPLIEDSYS AS FLOAT) ELSE CAST(R2.APPLIEDSYS AS FLOAT) END VLRDOCCR,
			R2.INSTID PARCELA,
			CASE
				WHEN R2.INVTYPE = 13 THEN V0.INSTALLMNT
				WHEN R2.INVTYPE = 14 THEN D0.INSTALLMNT
				WHEN R2.INVTYPE = 18 THEN C0.INSTALLMNT
				WHEN R2.INVTYPE = 19 THEN DC0.INSTALLMNT
				ELSE (SELECT COUNT(DOCTRANSID) FROM tpathVPM2 WHERE DOCTRANSID = R2.DOCTRANSID)
			END PARCELAS,
			CASE
				WHEN R2.INVTYPE = 13 THEN (SELECT TOP 1 V1.ACCTCODE FROM tpathINV1 V1 WHERE V1.DOCENTRY = V0.DOCENTRY)
				WHEN R2.INVTYPE = 14 THEN (SELECT TOP 1 D1.ACCTCODE FROM tpathRIN1 D1 WHERE D1.DOCENTRY = D0.DOCENTRY)
				WHEN R2.INVTYPE = 18 THEN (SELECT TOP 1 P1.ACCTCODE FROM tpathPCH1 P1 WHERE P1.DOCENTRY = C0.DOCENTRY)
				WHEN R2.INVTYPE = 19 THEN (SELECT TOP 1 F1.ACCTCODE FROM tpathRPC1 F1 WHERE F1.DOCENTRY = DC0.DOCENTRY)
				WHEN R2.INVTYPE = 204 THEN A0.CtlAccount
				ELSE COALESCE(COALESCE(COALESCE(NULLIF(R0.CASHACCT,''),NULLIF(R0.TRSFRACCT,'')),NULLIF(R0.CHECKACCT,'')),R0.BPACT)
			END CONTACOD,
			(SELECT ACCTNAME FROM tpathOACT WHERE ACCTCODE LIKE
																			CASE
																				WHEN R2.INVTYPE = 13 THEN (SELECT TOP 1 V1.ACCTCODE FROM tpathINV1 V1 WHERE V1.DOCENTRY = V0.DOCENTRY)
																				WHEN R2.INVTYPE = 14 THEN (SELECT TOP 1 D1.ACCTCODE FROM tpathRIN1 D1 WHERE D1.DOCENTRY = D0.DOCENTRY)
																				WHEN R2.INVTYPE = 18 THEN (SELECT TOP 1 P1.ACCTCODE FROM tpathPCH1 P1 WHERE P1.DOCENTRY = C0.DOCENTRY)
																				WHEN R2.INVTYPE = 19 THEN (SELECT TOP 1 F1.ACCTCODE FROM tpathRPC1 F1 WHERE F1.DOCENTRY = DC0.DOCENTRY)
																				WHEN R2.INVTYPE = 204 THEN A0.CtlAccount
																				ELSE COALESCE(COALESCE(COALESCE(NULLIF(R0.CASHACCT,''),NULLIF(R0.TRSFRACCT,'')),NULLIF(R0.CHECKACCT,'')),R0.BPACT)
																			END ) CONTANOME,
			CASE
				WHEN R2.INVTYPE = 13 THEN CONCAT(REPLACE(REPLACE(REPLACE(V0.COMMENTS,CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),' | ',V0.JrnlMemo)
				WHEN R2.INVTYPE = 14 THEN CONCAT(REPLACE(REPLACE(REPLACE(D0.COMMENTS,CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),' | ',D0.JrnlMemo)
				WHEN R2.INVTYPE = 18 THEN CONCAT(REPLACE(REPLACE(REPLACE(C0.COMMENTS,CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),' | ',C0.JrnlMemo)
				WHEN R2.INVTYPE = 19 THEN CONCAT(REPLACE(REPLACE(REPLACE(DC0.COMMENTS,CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),' | ',DC0.JrnlMemo)
				ELSE R0.JrnlMemo
			END OBSERVACAO
		FROM 
			tpathOVPM R0 INNER JOIN
			tpathVPM2 R2 ON R2.DOCNUM = R0.DOCNUM LEFT JOIN
			tpathOPCH C0 ON C0.TRANSID = R2.DOCTRANSID LEFT JOIN
			tpathORPC DC0 ON DC0.TRANSID = R2.DOCTRANSID LEFT JOIN
			tpathOINV V0 ON V0.TRANSID = R2.DOCTRANSID LEFT JOIN
			tpathORIN D0 ON D0.TRANSID = R2.DOCTRANSID LEFT JOIN
			tpathODPO A0 ON A0.TRANSID = R2.DOCTRANSID LEFT JOIN
			tpathVPM3 R3 ON R3.DocNum = R0.DOCNUM left join
			tpathFT_ORCA c1 ON C1.CODE = C0.SLPCODE LEFT JOIN 
			tpathFT_ORCA c2 ON C2.CODE = DC0.SLPCODE LEFT JOIN 
			tpathFT_OHRQ h1 ON c1.[U_Hierarquia] = h1.code LEFT JOIN 
			tpathFT_OHRQ h2 ON c2.[U_Hierarquia] = h2.code LEFT JOIN 
			tpathFT_ORCA W1 ON W1.CODE = V0.SLPCODE LEFT JOIN 
			tpathFT_ORCA W2 ON W2.CODE = D0.SLPCODE LEFT JOIN 
			tpathFT_OHRQ Z1 ON W1.[U_Hierarquia] = Z1.code LEFT JOIN 
			tpathFT_OHRQ Z2 ON W2.[U_Hierarquia] = Z2.code
		WHERE 
			YEAR(R0.DOCDATE) = 2020

end;	  

select * from [MBS].[dbo].[FLUXOP]