--FLUXO DE CAIXA OFICIAL RAISA CONTROLADORIA EM 21.DEZ.2020

DECLARE @DATAREF AS INT = 202008

DECLARE @loop int = (SELECT COUNT(baseid) FROM mbs..bases);
DECLARE @i int = 0; 
DECLARE @empresa nvarchar(MAX);
DECLARE @pathORCT nvarchar(MAX);
DECLARE @pathRCT2 nvarchar(MAX);
DECLARE @pathOINV nvarchar(MAX);
DECLARE @pathORIN nvarchar(MAX);
DECLARE @pathINV1 nvarchar(MAX);
DECLARE @pathRIN1 nvarchar(MAX);
DECLARE @pathDPI1 nvarchar(MAX);
DECLARE @pathDPO1 nvarchar(MAX);
DECLARE @pathODPI nvarchar(MAX);
DECLARE @pathRCT3 nvarchar(MAX);
DECLARE @pathOACT nvarchar(MAX);
DECLARE @pathOVPM nvarchar(MAX);
DECLARE @pathVPM2 nvarchar(MAX);
DECLARE @pathOPCH nvarchar(MAX);
DECLARE @pathORPC nvarchar(MAX);
DECLARE @pathPCH1 nvarchar(MAX);
DECLARE @pathRPC1 nvarchar(MAX);
DECLARE @pathODPO nvarchar(MAX);
DECLARE @pathJDT1 nvarchar(MAX);
DECLARE @pathOJDT nvarchar(MAX);
DECLARE @pathOCRD nvarchar(MAX);
DECLARE @pathOUSR nvarchar(MAX);
DECLARE @pathODPS nvarchar(MAX);
DECLARE @pathFT_ORCA nvarchar(MAX);
DECLARE @pathFT_OHRQ nvarchar(MAX);
DECLARE @pathFluxoMaster nvarchar(MAX);
DECLARE @pathFluxoDetalhe nvarchar(MAX);

DROP TABLE [MBS].[dbo].[FLUXO_DETALHE]
DROP TABLE [MBS].[dbo].[FLUXO_MASTER]

CREATE TABLE [MBS].[dbo].[FLUXO_DETALHE](
	[BASE] [nvarchar](50) NULL,
	[INVTYPE] [int] NULL,
	[LINEID] [int] NULL,
	[COLIGADA] [char](1) NULL,
	[TRANSIDOJDT] [int] NULL,
	[DOCORIGEM] [int] NULL,
	[NFORIGEM] [int] NULL,
	[CODCONTAORIGEM] [nvarchar](20) NULL,
	[NOMCONTAORIGEM] [nvarchar](100) NULL,
	[DTORIGEM] [datetime] NULL,
	[SUPERVISOR] [nvarchar](100) NULL,
	[CODPN] [nvarchar](20) NULL,
	[NOMEPN] [nvarchar](100) NULL,
	[OBSORIGEM] [nvarchar](MAX) NULL,
	[FORMA_PGTO] [varchar](20) NULL
) ON [PRIMARY]

CREATE TABLE [MBS].[dbo].[FLUXO_MASTER](
	[BASE] [nvarchar](50) NULL,
	[FILIAL] [nvarchar](100) NULL,
	[CNPJ] [nvarchar](40) NULL,
	[TRANSID] [int] NULL,
	[EXTREF] [nvarchar](20) NULL,
	[TRANSTYPE] [int] NULL,
	[REFDATE] [datetime] NULL,
	[CONTACOD] [nvarchar](20) NULL,
	[CONTANOME] [nvarchar](100) NULL,
	[LINE_ID] [int] NULL,	
	[VLRTOTAL] [numeric](19, 6) NULL,
	[DEBIT] [numeric](19, 6) NULL,
	[CREDIT] [numeric](19, 6) NULL,
	[SALDO] [numeric](19, 6) NULL,	
	[CONTRAACT] [nvarchar](15) NULL,
	[SHORTNAME] [nvarchar](15) NULL,
	[DEBCRED] [char](1) NULL,
	[DESCRICAO] [nvarchar](MAX) NULL,
	[USUARIO] [nvarchar](MAX) NULL
) ON [PRIMARY]

while @i < @loop
	begin
		set @i = @i + 1;
		set @empresa = (select empresa from mbs..bases where baseid = @i)
		set @pathORCT = CONCAT(N'CREATE SYNONYM tpathORCT FOR ',@empresa,N'.DBO.ORCT');
		set @pathRCT2 = CONCAT(N'CREATE SYNONYM tpathRCT2 FOR ',@empresa,N'.DBO.RCT2');
		set @pathOINV = CONCAT(N'CREATE SYNONYM tpathOINV FOR ',@empresa,N'.DBO.OINV');
		set @pathORIN = CONCAT(N'CREATE SYNONYM tpathORIN FOR ',@empresa,N'.DBO.ORIN');
		set @pathINV1 = CONCAT(N'CREATE SYNONYM tpathINV1 FOR ',@empresa,N'.DBO.INV1');
		set @pathRIN1 = CONCAT(N'CREATE SYNONYM tpathRIN1 FOR ',@empresa,N'.DBO.RIN1');
		set @pathOCRD = CONCAT(N'CREATE SYNONYM tpathOCRD FOR ',@empresa,N'.DBO.OCRD');
		set @pathDPI1 = CONCAT(N'CREATE SYNONYM tpathDPI1 FOR ',@empresa,N'.DBO.DPI1');
		set @pathDPO1 = CONCAT(N'CREATE SYNONYM tpathDPO1 FOR ',@empresa,N'.DBO.DPO1');
		set @pathODPI = CONCAT(N'CREATE SYNONYM tpathODPI FOR ',@empresa,N'.DBO.ODPI');
		set @pathRCT3 = CONCAT(N'CREATE SYNONYM tpathRCT3 FOR ',@empresa,N'.DBO.RCT3');
		set @pathOACT = CONCAT(N'CREATE SYNONYM tpathOACT FOR ',@empresa,N'.DBO.OACT');
		set @pathOVPM = CONCAT(N'CREATE SYNONYM tpathOVPM FOR ',@empresa,N'.DBO.OVPM');
		set @pathVPM2 = CONCAT(N'CREATE SYNONYM tpathVPM2 FOR ',@empresa,N'.DBO.VPM2');
		set @pathOPCH = CONCAT(N'CREATE SYNONYM tpathOPCH FOR ',@empresa,N'.DBO.OPCH');
		set @pathORPC = CONCAT(N'CREATE SYNONYM tpathORPC FOR ',@empresa,N'.DBO.ORPC');
		set @pathPCH1 = CONCAT(N'CREATE SYNONYM tpathPCH1 FOR ',@empresa,N'.DBO.PCH1');
		set @pathRPC1 = CONCAT(N'CREATE SYNONYM tpathRPC1 FOR ',@empresa,N'.DBO.RPC1');
		set @pathODPO = CONCAT(N'CREATE SYNONYM tpathODPO FOR ',@empresa,N'.DBO.ODPO');
		set @pathJDT1 = CONCAT(N'CREATE SYNONYM tpathJDT1 FOR ',@empresa,N'.DBO.JDT1');
		set @pathOJDT = CONCAT(N'CREATE SYNONYM tpathOJDT FOR ',@empresa,N'.DBO.OJDT');
		set @pathOUSR = CONCAT(N'CREATE SYNONYM tpathOUSR FOR ',@empresa,N'.DBO.OUSR');
		set @pathODPS = CONCAT(N'CREATE SYNONYM tpathODPS FOR ',@empresa,N'.DBO.ODPS');
		set @pathFT_ORCA = CONCAT(N'CREATE SYNONYM tpathFT_ORCA FOR ',@empresa,N'.DBO.[@FT_ORCA]');
		set @pathFT_OHRQ = CONCAT(N'CREATE SYNONYM tpathFT_OHRQ FOR ',@empresa,N'.DBO.[@FT_OHRQ]');
		set @pathFluxoMaster = N'CREATE SYNONYM tpathFluxoMaster FOR MBS.DBO.[Fluxo_Master]';
		set @pathFluxoDetalhe = N'CREATE SYNONYM tpathFluxoDetalhe FOR MBS.DBO.[Fluxo_Detalhe]';

		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathORCT') > 0 BEGIN DROP SYNONYM tpathORCT; EXEC(@pathORCT); END ELSE BEGIN exec(@pathORCT); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathRCT2') > 0 BEGIN DROP SYNONYM tpathRCT2; EXEC(@pathRCT2); END ELSE BEGIN exec(@pathRCT2); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathOINV') > 0 BEGIN DROP SYNONYM tpathOINV; EXEC(@pathOINV); END ELSE BEGIN exec(@pathOINV); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathORIN') > 0 BEGIN DROP SYNONYM tpathORIN; EXEC(@pathORIN); END ELSE BEGIN exec(@pathORIN); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathINV1') > 0 BEGIN DROP SYNONYM tpathINV1; EXEC(@pathINV1); END ELSE BEGIN exec(@pathINV1); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathRIN1') > 0 BEGIN DROP SYNONYM tpathRIN1; EXEC(@pathRIN1); END ELSE BEGIN exec(@pathRIN1); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathDPI1') > 0 BEGIN DROP SYNONYM tpathDPI1; EXEC(@pathDPI1); END ELSE BEGIN exec(@pathDPI1); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathDPO1') > 0 BEGIN DROP SYNONYM tpathDPO1; EXEC(@pathDPO1); END ELSE BEGIN exec(@pathDPO1); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathODPI') > 0 BEGIN DROP SYNONYM tpathODPI; EXEC(@pathODPI); END ELSE BEGIN exec(@pathODPI); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathRCT3') > 0 BEGIN DROP SYNONYM tpathRCT3; EXEC(@pathRCT3); END ELSE BEGIN exec(@pathRCT3); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathOACT') > 0 BEGIN DROP SYNONYM tpathOACT; EXEC(@pathOACT); END ELSE BEGIN exec(@pathOACT); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathOVPM') > 0 BEGIN DROP SYNONYM tpathOVPM; EXEC(@pathOVPM); END ELSE BEGIN exec(@pathOVPM); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathVPM2') > 0 BEGIN DROP SYNONYM tpathVPM2; EXEC(@pathVPM2); END ELSE BEGIN exec(@pathVPM2); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathOPCH') > 0 BEGIN DROP SYNONYM tpathOPCH; EXEC(@pathOPCH); END ELSE BEGIN exec(@pathOPCH); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathORPC') > 0 BEGIN DROP SYNONYM tpathORPC; EXEC(@pathORPC); END ELSE BEGIN exec(@pathORPC); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathPCH1') > 0 BEGIN DROP SYNONYM tpathPCH1; EXEC(@pathPCH1); END ELSE BEGIN exec(@pathPCH1); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathOCRD') > 0 BEGIN DROP SYNONYM tpathOCRD; EXEC(@pathOCRD); END ELSE BEGIN exec(@pathOCRD); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathRPC1') > 0 BEGIN DROP SYNONYM tpathRPC1; EXEC(@pathRPC1); END ELSE BEGIN exec(@pathRPC1); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathODPO') > 0 BEGIN DROP SYNONYM tpathODPO; EXEC(@pathODPO); END ELSE BEGIN exec(@pathODPO); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathJDT1') > 0 BEGIN DROP SYNONYM tpathJDT1; EXEC(@pathJDT1); END ELSE BEGIN exec(@pathJDT1); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathOJDT') > 0 BEGIN DROP SYNONYM tpathOJDT; EXEC(@pathOJDT); END ELSE BEGIN exec(@pathOJDT); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathOUSR') > 0 BEGIN DROP SYNONYM tpathOUSR; EXEC(@pathOUSR); END ELSE BEGIN exec(@pathOUSR); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathODPS') > 0 BEGIN DROP SYNONYM tpathODPS; EXEC(@pathODPS); END ELSE BEGIN exec(@pathODPS); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathFT_ORCA') > 0 BEGIN DROP SYNONYM tpathFT_ORCA; EXEC(@pathFT_ORCA); END ELSE BEGIN exec(@pathFT_ORCA); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathFT_OHRQ') > 0 BEGIN DROP SYNONYM tpathFT_OHRQ; EXEC(@pathFT_OHRQ); END ELSE BEGIN exec(@pathFT_OHRQ); END	
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathFluxoMaster') > 0 BEGIN DROP SYNONYM tpathFluxoMaster; EXEC(@pathFluxoMaster); END ELSE BEGIN exec(@pathFluxoMaster); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathFluxoDetalhe') > 0 BEGIN DROP SYNONYM tpathFluxoDetalhe; EXEC(@pathFluxoDetalhe); END ELSE BEGIN exec(@pathFluxoDetalhe); END

--ABASTECE A TABELA DE FLUXO DE CAIXA DO TIPO MASTER
INSERT INTO tpathFluxoMaster
	SELECT 
		@empresa BASE,
		COALESCE(UPPER(i.bplname),REPLACE(@empresa,'sbo','')) FILIAL,
		COALESCE(I.VATREGNUM,'00.000.000/0000-00') cnpjfilial,
		o.TRANSID, 
		O.BASEREF EXTREF, 
		O.TRANSTYPE, 
		O.REFDATE,
		(CASE WHEN (I.SHORTNAME LIKE 'F%' OR I.SHORTNAME LIKE 'C%') THEN I.ACCOUNT ELSE I.SHORTNAME END) contacod, 	
		UPPER(A.AcctName) AS contanome,
		I.LINE_ID, 
		O.SYSTOTAL vlrtotal, 
		I.SYSDEB, 
		I.SYSCRED, 
		(I.SYSDEB - I.SYSCRED) saldo, 
		(CASE WHEN (I.CONTRAACT LIKE 'F%' OR I.CONTRAACT LIKE 'C%') THEN I.ACCOUNT ELSE I.CONTRAACT END) CONTRAACT, 
		(CASE WHEN (I.SHORTNAME LIKE 'F%' OR I.SHORTNAME LIKE 'C%') THEN I.ACCOUNT ELSE I.SHORTNAME END) SHORTNAME, 
		I.DEBCRED,
		I.LINEMEMO, 
		UPPER((U.USER_CODE + ' - ' + U.U_NAME)) USUARIO
	FROM				
		tpathOJDT o INNER JOIN 
		tpathJDT1 i on i.TRANSID = o.TRANSID INNER JOIN 
		tpathOUSR U ON U.USERID = O.USERSIGN LEFT JOIN
		tpathOACT A ON A.AcctCode COLLATE DATABASE_DEFAULT = (CASE WHEN (I.SHORTNAME LIKE 'F%' OR I.SHORTNAME LIKE 'C%') THEN I.ACCOUNT ELSE I.SHORTNAME END)
	WHERE 
		FORMAT(O.REFDATE,'yyyyMM') IN ('202010','202011')

--MANTEM NA TABELA MASTER APENAS AS CONTAS-BANCO
DELETE FROM tpathFluxoMaster WHERE [contacod] NOT like '1.1.01%'

INSERT INTO tpathFluxoDetalhe
SELECT DISTINCT @empresa AS BASE, T3.INVTYPE, T3.InvoiceId, CASE WHEN (select G.GROUPNAME from tpathocrg g where g.groupcode = (select groupcode from tpathocrd r where cardcode = T4.CARDCODE)) LIKE '%ligada%' THEN 'Y' ELSE 'N' END COLIGADA, 
	T1.TRANSID TRANSIDOJDT, T4.DOCENTRY DOCORIGEM, T4.SERIAL NFORIGEM, T0.acctcode CODCONTAORIGEM, UPPER(T5.acctNAME) NOMCONTAORIGEM, T0.DOCDATE DTORIGEM, COALESCE(NULLIF(T7.NAME,''),'SEM_SUPERVISOR') SUPERVISOR, T4.CARDCODE CODPN, T4.CARDNAME NOMEPN, REPLACE(REPLACE(REPLACE(COALESCE(T4.COMMENTS,''),CHAR(13),' '),CHAR(10),' '),CHAR(9),' ') OBSORIGEM,
(SELECT	TOP 1 CASE
			WHEN DdctSumSy > 0 THEN '###DEDUCTION###'
			WHEN CashSumSy > 0 THEN 'DINHEIRO'
			WHEN CredSumSy > 0 THEN 'CARTAO'
			WHEN CheckSumSy> 0 THEN 'CHEQUE'
			WHEN TrsfrSumSy> 0 THEN 'TRANSFERENCIA'
			WHEN NoDocSumSy> 0 THEN '###NO_DOC###'
			ELSE 'X'
		END   FROM tpathORCT ) FORMA_PGTO
FROM 
	tpathINV1 T0 INNER JOIN
	tpathOINV T4 ON T0.DOCENTRY = T4.DOCENTRY INNER JOIN
	tpathFluxoMaster T1 on 1 = 1 INNER JOIN 
	tpathORCT T2 ON T1.EXTREF = T2.DOCNUM inner join
	tpathRCT2 T3 ON T3.docnum = T2.DocEntry AND T0.DOCENTRY = T3.DOCENTRY INNER JOIN
	tpathOACT T5 ON T5.ACCTCODE = T0.ACCTCODE LEFT JOIN 
	[tpathFT_ORCA] T6 ON T6.CODE = T4.SLPCODE LEFT JOIN 
	[tpathFT_OHRQ] T7 ON T6.[U_Hierarquia] = T7.code
WHERE
	T1.[contacod] like '1.1.01%' AND T1.TRANSTYPE = 24 AND T3.invtype = 13

INSERT INTO tpathFluxoDetalhe
SELECT DISTINCT @empresa AS BASE, T3.INVTYPE, T3.InvoiceId, CASE WHEN (select G.GROUPNAME from tpathocrg g where g.groupcode = (select groupcode from tpathocrd r where cardcode = T4.CARDCODE)) LIKE '%ligada%' THEN 'Y' ELSE 'N' END COLIGADA, 
	T1.TRANSID TRANSIDOJDT, T4.DOCENTRY DOCORIGEM, T4.SERIAL NFORIGEM, T0.acctcode CODCONTAORIGEM, UPPER(T5.acctNAME) NOMCONTAORIGEM, T0.DOCDATE DTORIGEM, COALESCE(NULLIF(T7.NAME,''),'SEM_SUPERVISOR') SUPERVISOR, T4.CARDCODE CODPN, T4.CARDNAME NOMEPN, REPLACE(REPLACE(REPLACE(COALESCE(T4.COMMENTS,''),CHAR(13),' '),CHAR(10),' '),CHAR(9),' ') OBSORIGEM,
(SELECT	TOP 1 CASE
			WHEN DdctSumSy > 0 THEN '###DEDUCTION###'
			WHEN CashSumSy > 0 THEN 'DINHEIRO'
			WHEN CredSumSy > 0 THEN 'CARTAO'
			WHEN CheckSumSy> 0 THEN 'CHEQUE'
			WHEN TrsfrSumSy> 0 THEN 'TRANSFERENCIA'
			WHEN NoDocSumSy> 0 THEN '###NO_DOC###'
			ELSE 'X'
		END   FROM tpathORCT ) FORMA_PGTO
FROM 
	tpathRIN1 T0 INNER JOIN
	tpathORIN T4 ON T0.DOCENTRY = T4.DOCENTRY INNER JOIN
	tpathFluxoMaster T1 on 1 = 1 INNER JOIN 
	tpathORCT T2 ON T1.EXTREF = T2.DOCNUM inner join
	tpathRCT2 T3 ON T3.docnum = T2.DocEntry AND T0.DOCENTRY = T3.DOCENTRY INNER JOIN
	tpathOACT T5 ON T5.ACCTCODE = T0.ACCTCODE LEFT JOIN 
	[tpathFT_ORCA] T6 ON T6.CODE = T4.SLPCODE LEFT JOIN 
	[tpathFT_OHRQ] T7 ON T6.[U_Hierarquia] = T7.code
WHERE
	T1.[contacod] like '1.1.01%' AND T1.TRANSTYPE = 24 AND T3.invtype = 14


INSERT INTO tpathFluxoDetalhe
SELECT DISTINCT @empresa AS BASE, T3.INVTYPE, T3.InvoiceId, CASE WHEN (select G.GROUPNAME from tpathocrg g where g.groupcode = (select groupcode from tpathocrd r where cardcode = T4.CARDCODE)) LIKE '%ligada%' THEN 'Y' ELSE 'N' END COLIGADA, 
	T1.TRANSID TRANSIDOJDT, T4.DOCENTRY DOCORIGEM, 0 NFORIGEM, T4.TRSFRACCT CODCONTAORIGEM, UPPER(T5.acctNAME) NOMCONTAORIGEM, T4.TRSFRDATE DTORIGEM, ('SEM_SUPERVISOR') SUPERVISOR, T4.CARDCODE CODPN, T4.CARDNAME NOMEPN, REPLACE(REPLACE(REPLACE(COALESCE(T4.JRNLMEMO,''),CHAR(13),' '),CHAR(10),' '),CHAR(9),' ') OBSORIGEM,
	CASE
			WHEN T4.DdctSumSy > 0 THEN '###DEDUCTION###'
			WHEN T4.CashSumSy > 0 THEN 'DINHEIRO'
			WHEN T4.CredSumSy > 0 THEN 'CARTAO'
			WHEN T4.CheckSumSy> 0 THEN 'CHEQUE'
			WHEN T4.TrsfrSumSy> 0 THEN 'TRANSFERENCIA'
			WHEN T4.NoDocSumSy> 0 THEN '###NO_DOC###'
			ELSE 'X'
		END  FORMA_PGTO
FROM 
	tpathORCT T4 INNER JOIN
	tpathFluxoMaster T1 on 1 = 1 INNER JOIN 
	tpathORCT T2 ON T1.EXTREF = T2.DOCNUM inner join
	tpathRCT2 T3 ON T3.docnum = T2.DocEntry AND T4.TRANSID = T3.DOCENTRY INNER JOIN
	tpathOACT T5 ON T5.ACCTCODE = T4.TRSFRACCT
WHERE
	T1.[contacod] like '1.1.01%' AND T1.TRANSTYPE = 24 AND T3.invtype = 24

INSERT INTO tpathFluxoDetalhe
SELECT DISTINCT @empresa AS BASE, T3.INVTYPE, T3.InvoiceId, CASE WHEN (select G.GROUPNAME from tpathocrg g where g.groupcode = (select groupcode from tpathocrd r where cardcode = T4.CARDCODE)) LIKE '%ligada%' THEN 'Y' ELSE 'N' END COLIGADA, 
	T1.TRANSID TRANSIDOJDT, T4.DOCENTRY DOCORIGEM, 0 NFORIGEM, T0.acctcode CODCONTAORIGEM, UPPER(T5.acctNAME) NOMCONTAORIGEM, T0.DOCDATE DTORIGEM, COALESCE(NULLIF(T7.NAME,''),'SEM_SUPERVISOR') SUPERVISOR, T4.CARDCODE CODPN, T4.CARDNAME NOMEPN, REPLACE(REPLACE(REPLACE(COALESCE(T4.COMMENTS,''),CHAR(13),' '),CHAR(10),' '),CHAR(9),' ') OBSORIGEM,
(SELECT	TOP 1 CASE
			WHEN DdctSumSy > 0 THEN '###DEDUCTION###'
			WHEN CashSumSy > 0 THEN 'DINHEIRO'
			WHEN CredSumSy > 0 THEN 'CARTAO'
			WHEN CheckSumSy> 0 THEN 'CHEQUE'
			WHEN TrsfrSumSy> 0 THEN 'TRANSFERENCIA'
			WHEN NoDocSumSy> 0 THEN '###NO_DOC###'
			ELSE 'X'
		END   FROM tpathORCT ) FORMA_PGTO
FROM 
	tpathDPI1 T0 INNER JOIN
	tpathODPI T4 ON T0.DOCENTRY = T4.DOCENTRY INNER JOIN
	tpathFluxoMaster T1 on 1 = 1 INNER JOIN 
	tpathORCT T2 ON T1.EXTREF = T2.DOCNUM inner join
	tpathRCT2 T3 ON T3.docnum = T2.DocEntry AND T0.DOCENTRY = T3.DOCENTRY INNER JOIN
	tpathOACT T5 ON T5.ACCTCODE = T0.ACCTCODE LEFT JOIN 
	[tpathFT_ORCA] T6 ON T6.CODE = T4.SLPCODE LEFT JOIN 
	[tpathFT_OHRQ] T7 ON T6.[U_Hierarquia] = T7.code
WHERE
	T1.[contacod] like '1.1.01%' AND T1.TRANSTYPE = 24 AND T3.invtype = 203


INSERT INTO tpathFluxoDetalhe
SELECT DISTINCT @empresa AS BASE, T3.INVTYPE, T3.InvoiceId, CASE WHEN (select G.GROUPNAME from tpathocrg g where g.groupcode = (select groupcode from tpathocrd r where cardcode = T4.CARDCODE)) LIKE '%ligada%' THEN 'Y' ELSE 'N' END COLIGADA, 
	T1.TRANSID TRANSIDOJDT, T4.DOCENTRY DOCORIGEM, T4.SERIAL NFORIGEM, T0.acctcode CODCONTAORIGEM, UPPER(T5.acctNAME) NOMCONTAORIGEM, T0.DOCDATE DTORIGEM, COALESCE(NULLIF(T7.NAME,''),'SEM_SUPERVISOR') SUPERVISOR, T4.CARDCODE CODPN, T4.CARDNAME NOMEPN, REPLACE(REPLACE(REPLACE(COALESCE(T4.COMMENTS,''),CHAR(13),' '),CHAR(10),' '),CHAR(9),' ') OBSORIGEM,
(SELECT	TOP 1 CASE
			WHEN DdctSumSy > 0 THEN '###DEDUCTION###'
			WHEN CashSumSy > 0 THEN 'DINHEIRO'
			WHEN CredSumSy > 0 THEN 'CARTAO'
			WHEN CheckSumSy> 0 THEN 'CHEQUE'
			WHEN TrsfrSumSy> 0 THEN 'TRANSFERENCIA'
			WHEN NoDocSumSy> 0 THEN '###NO_DOC###'
			ELSE 'X'
		END   FROM tpathOVPM ) FORMA_PGTO
FROM 
	tpathINV1 T0 INNER JOIN
	tpathOINV T4 ON T0.DOCENTRY = T4.DOCENTRY INNER JOIN
	tpathFluxoMaster T1 on 1 = 1 INNER JOIN 
	tpathOVPM T2 ON T1.EXTREF = T2.DOCNUM inner join
	tpathVPM2 T3 ON T3.docnum = T2.DocEntry AND T0.DOCENTRY = T3.DOCENTRY INNER JOIN
	tpathOACT T5 ON T5.ACCTCODE = T0.ACCTCODE LEFT JOIN 
	[tpathFT_ORCA] T6 ON T6.CODE = T4.SLPCODE LEFT JOIN 
	[tpathFT_OHRQ] T7 ON T6.[U_Hierarquia] = T7.code
WHERE
	T1.[contacod] like '1.1.01%' AND T1.TRANSTYPE = 46 AND T3.invtype = 13

INSERT INTO tpathFluxoDetalhe
SELECT DISTINCT @empresa AS BASE, T3.INVTYPE, T3.InvoiceId, CASE WHEN (select G.GROUPNAME from tpathocrg g where g.groupcode = (select groupcode from tpathocrd r where cardcode = T4.CARDCODE)) LIKE '%ligada%' THEN 'Y' ELSE 'N' END COLIGADA, 
	T1.TRANSID TRANSIDOJDT, T4.DOCENTRY DOCORIGEM, T4.SERIAL NFORIGEM, T0.acctcode CODCONTAORIGEM, UPPER(T5.acctNAME) NOMCONTAORIGEM, T0.DOCDATE DTORIGEM, COALESCE(NULLIF(T7.NAME,''),'SEM_SUPERVISOR') SUPERVISOR, T4.CARDCODE CODPN, T4.CARDNAME NOMEPN, REPLACE(REPLACE(REPLACE(COALESCE(T4.COMMENTS,''),CHAR(13),' '),CHAR(10),' '),CHAR(9),' ') OBSORIGEM,
(SELECT	TOP 1 CASE
			WHEN DdctSumSy > 0 THEN '###DEDUCTION###'
			WHEN CashSumSy > 0 THEN 'DINHEIRO'
			WHEN CredSumSy > 0 THEN 'CARTAO'
			WHEN CheckSumSy> 0 THEN 'CHEQUE'
			WHEN TrsfrSumSy> 0 THEN 'TRANSFERENCIA'
			WHEN NoDocSumSy> 0 THEN '###NO_DOC###'
			ELSE 'X'
		END   FROM tpathOVPM ) FORMA_PGTO
FROM 
	tpathRIN1 T0 INNER JOIN
	tpathORIN T4 ON T0.DOCENTRY = T4.DOCENTRY INNER JOIN
	tpathFluxoMaster T1 on 1 = 1 INNER JOIN 
	tpathOVPM T2 ON T1.EXTREF = T2.DOCNUM inner join
	tpathVPM2 T3 ON T3.docnum = T2.DocEntry AND T0.DOCENTRY = T3.DOCENTRY INNER JOIN
	tpathOACT T5 ON T5.ACCTCODE = T0.ACCTCODE LEFT JOIN 
	[tpathFT_ORCA] T6 ON T6.CODE = T4.SLPCODE LEFT JOIN 
	[tpathFT_OHRQ] T7 ON T6.[U_Hierarquia] = T7.code
WHERE
	T1.[contacod] like '1.1.01%' AND T1.TRANSTYPE = 46 AND T3.invtype = 14


INSERT INTO tpathFluxoDetalhe
SELECT DISTINCT @empresa AS BASE, T3.INVTYPE, T3.InvoiceId, CASE WHEN (select G.GROUPNAME from tpathocrg g where g.groupcode = (select groupcode from tpathocrd r where cardcode = T4.CARDCODE)) LIKE '%ligada%' THEN 'Y' ELSE 'N' END COLIGADA,  
	T1.TRANSID TRANSIDOJDT, T4.DOCENTRY DOCORIGEM, 0 NFORIGEM, 
		CASE
			WHEN T4.CashSumSy > 0 THEN T4.Cashacct 
			WHEN T4.CheckSumSy> 0 THEN T4.Checkacct
			WHEN T4.TrsfrSumSy> 0 THEN T4.Trsfracct
			ELSE T4.BPACT
		END  CODCONTAORIGEM, UPPER(T5.acctNAME) NOMCONTAORIGEM, 
		
		CASE
			WHEN T4.TrsfrSumSy> 0 THEN T4.TrsfrDATE
			ELSE T4.DocDate
		END  DTORIGEM, ('SEM_SUPERVISOR') SUPERVISOR, T4.CARDCODE CODPN, T4.CARDNAME NOMEPN, REPLACE(REPLACE(REPLACE(COALESCE(T4.JRNLMEMO,''),CHAR(13),' '),CHAR(10),' '),CHAR(9),' ') OBSORIGEM,
	CASE
			WHEN T4.DdctSumSy > 0 THEN '###DEDUCTION###'
			WHEN T4.CashSumSy > 0 THEN 'DINHEIRO'
			WHEN T4.CredSumSy > 0 THEN 'CARTAO'
			WHEN T4.CheckSumSy> 0 THEN 'CHEQUE'
			WHEN T4.TrsfrSumSy> 0 THEN 'TRANSFERENCIA'
			WHEN T4.NoDocSumSy> 0 THEN '###NO_DOC###'
			ELSE 'X'
		END  FORMA_PGTO
FROM 
	tpathORCT T4 INNER JOIN
	tpathFluxoMaster T1 on 1 = 1 INNER JOIN 
	tpathOVPM T2 ON T1.EXTREF = T2.DOCNUM inner join
	tpathVPM2 T3 ON T3.docnum = T2.DocEntry AND T4.TRANSID = T3.DOCENTRY INNER JOIN
	tpathOACT T5 ON T5.ACCTCODE = 
							(CASE
								WHEN T4.CashSumSy > 0 THEN T4.Cashacct 
								WHEN T4.CheckSumSy> 0 THEN T4.Checkacct
								WHEN T4.TrsfrSumSy> 0 THEN T4.Trsfracct
								ELSE T4.BPACT
							END)
WHERE
	T1.[contacod] like '1.1.01%' AND T1.TRANSTYPE = 46 AND T3.invtype = 24


INSERT INTO tpathFluxoDetalhe
SELECT DISTINCT @empresa AS BASE, T3.INVTYPE, T3.InvoiceId, CASE WHEN (select G.GROUPNAME from tpathocrg g where g.groupcode = (select groupcode from tpathocrd r where cardcode = T4.CARDCODE)) LIKE '%ligada%' THEN 'Y' ELSE 'N' END COLIGADA,  
	T1.TRANSID TRANSIDOJDT, T4.DOCENTRY DOCORIGEM, 0 NFORIGEM, T0.acctcode CODCONTAORIGEM, UPPER(T5.acctNAME) NOMCONTAORIGEM, T0.DOCDATE DTORIGEM, COALESCE(NULLIF(T7.NAME,''),'SEM_SUPERVISOR') SUPERVISOR, T4.CARDCODE CODPN, T4.CARDNAME NOMEPN, REPLACE(REPLACE(REPLACE(COALESCE(T4.COMMENTS,''),CHAR(13),' '),CHAR(10),' '),CHAR(9),' ') OBSORIGEM,
(SELECT	TOP 1 CASE
			WHEN DdctSumSy > 0 THEN '###DEDUCTION###'
			WHEN CashSumSy > 0 THEN 'DINHEIRO'
			WHEN CredSumSy > 0 THEN 'CARTAO'
			WHEN CheckSumSy> 0 THEN 'CHEQUE'
			WHEN TrsfrSumSy> 0 THEN 'TRANSFERENCIA'
			WHEN NoDocSumSy> 0 THEN '###NO_DOC###'
			ELSE 'X'
		END   FROM tpathOVPM ) FORMA_PGTO
FROM 
	tpathDPO1 T0 INNER JOIN
	tpathODPO T4 ON T0.DOCENTRY = T4.DOCENTRY INNER JOIN
	tpathFluxoMaster T1 on 1 = 1 INNER JOIN 
	tpathOVPM T2 ON T1.EXTREF = T2.DOCNUM inner join
	tpathVPM2 T3 ON T3.docnum = T2.DocEntry AND T0.DOCENTRY = T3.DOCENTRY INNER JOIN
	tpathOACT T5 ON T5.ACCTCODE = T0.ACCTCODE LEFT JOIN 
	[tpathFT_ORCA] T6 ON T6.CODE = T4.SLPCODE LEFT JOIN 
	[tpathFT_OHRQ] T7 ON T6.[U_Hierarquia] = T7.code
WHERE
	T1.[contacod] like '1.1.01%' AND T1.TRANSTYPE = 46 AND T3.invtype = 204


INSERT INTO tpathFluxoDetalhe
SELECT DISTINCT @empresa AS BASE, T3.INVTYPE, T3.InvoiceId, CASE WHEN (select G.GROUPNAME from tpathocrg g where g.groupcode = (select groupcode from tpathocrd r where cardcode = T0.SHORTNAME)) LIKE '%ligada%' THEN 'Y' ELSE 'N' END COLIGADA, 
	T1.TRANSID TRANSIDOJDT, T4.BASEREF DOCORIGEM, 0 NFORIGEM, T0.ACCOUNT CODCONTAORIGEM, UPPER(T5.acctNAME) NOMCONTAORIGEM, T0.REFDATE DTORIGEM, 'SEM_SUPERVISOR' SUPERVISOR, T0.SHORTNAME CODPN, (SELECT CARDNAME FROM TPATHOCRD R WHERE R.CARDCODE = T0.SHORTNAME) NOMEPN, REPLACE(REPLACE(REPLACE(COALESCE(T4.MEMO,''),CHAR(13),' '),CHAR(10),' '),CHAR(9),' ') OBSORIGEM,
'### SEM_PGTO ###' FORMA_PGTO
FROM 
	tpathJDT1 T0 INNER JOIN
	tpathOJDT T4 ON T0.BASEREF = T4.BASEREF INNER JOIN
	tpathFluxoMaster T1 on 1 = 1 INNER JOIN 
	tpathOVPM T2 ON T1.EXTREF = T2.DOCNUM inner join
	tpathVPM2 T3 ON T3.docnum = T2.DocEntry AND T0.BASEREF = T3.DOCENTRY INNER JOIN
	tpathOACT T5 ON T5.ACCTCODE = T0.ACCOUNT
WHERE
	LEFT(T0.SHORTNAME,1) IN ('C','F') AND T1.[contacod] like '1.1.01%' AND T1.TRANSTYPE = 46 AND T3.invtype = 30


INSERT INTO tpathFluxoDetalhe
SELECT DISTINCT @empresa AS BASE, T3.INVTYPE, T3.InvoiceId, CASE WHEN (select G.GROUPNAME from tpathocrg g where g.groupcode = (select groupcode from tpathocrd r where cardcode = T4.CARDCODE)) LIKE '%ligada%' THEN 'Y' ELSE 'N' END COLIGADA,  
	T1.TRANSID TRANSIDOJDT, T4.DOCENTRY DOCORIGEM, T4.SERIAL NFORIGEM, T0.acctcode CODCONTAORIGEM, UPPER(T5.acctNAME) NOMCONTAORIGEM, T0.DOCDATE DTORIGEM, COALESCE(NULLIF(T7.NAME,''),'SEM_SUPERVISOR') SUPERVISOR, T4.CARDCODE CODPN, T4.CARDNAME NOMEPN, REPLACE(REPLACE(REPLACE(COALESCE(T4.COMMENTS,''),CHAR(13),' '),CHAR(10),' '),CHAR(9),' ') OBSORIGEM,
(SELECT	TOP 1 CASE
			WHEN DdctSumSy > 0 THEN '###DEDUCTION###'
			WHEN CashSumSy > 0 THEN 'DINHEIRO'
			WHEN CredSumSy > 0 THEN 'CARTAO'
			WHEN CheckSumSy> 0 THEN 'CHEQUE'
			WHEN TrsfrSumSy> 0 THEN 'TRANSFERENCIA'
			WHEN NoDocSumSy> 0 THEN '###NO_DOC###'
			ELSE 'X'
		END   FROM tpathOVPM ) FORMA_PGTO
FROM 
	tpathPCH1 T0 INNER JOIN
	tpathOPCH T4 ON T0.DOCENTRY = T4.DOCENTRY INNER JOIN
	tpathFluxoMaster T1 on 1 = 1 INNER JOIN 
	tpathOVPM T2 ON T1.EXTREF = T2.DOCNUM inner join
	tpathVPM2 T3 ON T3.docnum = T2.DocEntry AND T0.DOCENTRY = T3.DOCENTRY INNER JOIN
	tpathOACT T5 ON T5.ACCTCODE = T0.ACCTCODE LEFT JOIN 
	[tpathFT_ORCA] T6 ON T6.CODE = T4.SLPCODE LEFT JOIN 
	[tpathFT_OHRQ] T7 ON T6.[U_Hierarquia] = T7.code
WHERE
	T1.[contacod] like '1.1.01%' AND T1.TRANSTYPE = 46 AND T3.invtype = 18


INSERT INTO tpathFluxoDetalhe
SELECT DISTINCT @empresa AS BASE, 13 INVTYPE, T0.LINENUM, CASE WHEN (select G.GROUPNAME from tpathocrg g where g.groupcode = (select groupcode from tpathocrd r where cardcode = T4.CARDCODE)) LIKE '%ligada%' THEN 'Y' ELSE 'N' END COLIGADA, 
	T1.TRANSID TRANSIDOJDT, T4.DOCENTRY DOCORIGEM, T4.SERIAL NFORIGEM, T0.acctcode CODCONTAORIGEM, UPPER(T5.acctNAME) NOMCONTAORIGEM, T0.DOCDATE DTORIGEM, COALESCE(NULLIF(T7.NAME,''),'SEM_SUPERVISOR') SUPERVISOR, T4.CARDCODE CODPN, T4.CARDNAME NOMEPN, REPLACE(REPLACE(REPLACE(COALESCE(T4.COMMENTS,''),CHAR(13),' '),CHAR(10),' '),CHAR(9),' ') OBSORIGEM,
(SELECT	TOP 1 CASE
			WHEN DdctSumSy > 0 THEN '###DEDUCTION###'
			WHEN CashSumSy > 0 THEN 'DINHEIRO'
			WHEN CredSumSy > 0 THEN 'CARTAO'
			WHEN CheckSumSy> 0 THEN 'CHEQUE'
			WHEN TrsfrSumSy> 0 THEN 'TRANSFERENCIA'
			WHEN NoDocSumSy> 0 THEN '###NO_DOC###'
			ELSE 'X'
		END   FROM tpathORCT ) FORMA_PGTO
FROM 
	tpathINV1 T0 INNER JOIN
	tpathOINV T4 ON T0.DOCENTRY = T4.DOCENTRY INNER JOIN
	tpathFluxoMaster T1 on T1.TRANSID = T4.TRANSID INNER JOIN 
	tpathOACT T5 ON T5.ACCTCODE = T0.ACCTCODE LEFT JOIN 
	[tpathFT_ORCA] T6 ON T6.CODE = T4.SLPCODE LEFT JOIN 
	[tpathFT_OHRQ] T7 ON T6.[U_Hierarquia] = T7.code 
WHERE T1.TRANSTYPE = 13 AND T1.[contacod] like '1.1.01%' 

	
INSERT INTO tpathFluxoDetalhe
SELECT DISTINCT @empresa AS BASE, 18 INVTYPE, T0.LINENUM, CASE WHEN (select G.GROUPNAME from tpathocrg g where g.groupcode = (select groupcode from tpathocrd r where cardcode = T4.CARDCODE)) LIKE '%ligada%' THEN 'Y' ELSE 'N' END COLIGADA, 
	T1.TRANSID TRANSIDOJDT, T4.DOCENTRY DOCORIGEM, T4.SERIAL NFORIGEM, T0.acctcode CODCONTAORIGEM, UPPER(T5.acctNAME) NOMCONTAORIGEM, T0.DOCDATE DTORIGEM, COALESCE(NULLIF(T7.NAME,''),'SEM_SUPERVISOR') SUPERVISOR, T4.CARDCODE CODPN, T4.CARDNAME NOMEPN, REPLACE(REPLACE(REPLACE(COALESCE(T4.COMMENTS,''),CHAR(13),' '),CHAR(10),' '),CHAR(9),' ') OBSORIGEM,
(SELECT	TOP 1 CASE
			WHEN DdctSumSy > 0 THEN '###DEDUCTION###'
			WHEN CashSumSy > 0 THEN 'DINHEIRO'
			WHEN CredSumSy > 0 THEN 'CARTAO'
			WHEN CheckSumSy> 0 THEN 'CHEQUE'
			WHEN TrsfrSumSy> 0 THEN 'TRANSFERENCIA'
			WHEN NoDocSumSy> 0 THEN '###NO_DOC###'
			ELSE 'X'
		END   FROM tpathORCT ) FORMA_PGTO
FROM 
	tpathPCH1 T0 INNER JOIN
	tpathOPCH T4 ON T0.DOCENTRY = T4.DOCENTRY INNER JOIN
	tpathFluxoMaster T1 on T1.TRANSID = T4.TRANSID INNER JOIN 
	tpathOACT T5 ON T5.ACCTCODE = T0.ACCTCODE LEFT JOIN 
	[tpathFT_ORCA] T6 ON T6.CODE = T4.SLPCODE LEFT JOIN 
	[tpathFT_OHRQ] T7 ON T6.[U_Hierarquia] = T7.code 
WHERE 
	LEFT(T0.acctcode,1) = '1' AND T1.TRANSTYPE = 18 AND T1.[contacod] like '1.1.01%'


INSERT INTO tpathFluxoDetalhe
SELECT DISTINCT @empresa AS BASE, 25 INVTYPE, 0, 'N', 
	T1.TRANSID TRANSIDOJDT, T4.TRANSABS DOCORIGEM, 0 NFORIGEM, T4.BANCKACCT CODCONTAORIGEM, UPPER(T5.acctNAME) NOMCONTAORIGEM, T4.DEPOSDATE DTORIGEM, 'SEM_SUPERVISOR' SUPERVISOR, '### SEM CODPN ###' CODPN, '### SEM NOMEPN ###' NOMEPN, REPLACE(REPLACE(REPLACE(COALESCE(T4.MEMO,''),CHAR(13),' '),CHAR(10),' '),CHAR(9),' ') OBSORIGEM,
CASE
	WHEN DEPOSTYPE = 'K' THEN 'CHEQUE'
	WHEN DEPOSTYPE = 'C' THEN 'DINHEIRO'
	WHEN DEPOSTYPE = 'V' THEN 'CARTAO'
	WHEN DEPOSTYPE = 'B' THEN 'LETRA_CAMBIO'
	ELSE 'X'
END FORMA_PGTO
FROM 
	tpathODPS T4 INNER JOIN
	tpathFluxoMaster T1 on T1.TRANSID = T4.TRANSABS AND T1.TRANSTYPE = 25 AND T1.[contacod] like '1.1.01%' INNER JOIN 
	tpathOACT T5 ON T5.ACCTCODE = T4.BANCKACCT 


INSERT INTO tpathFluxoDetalhe
SELECT DISTINCT @empresa AS BASE, 30 INVTYPE, T0.LINE_ID, CASE WHEN (select G.GROUPNAME from tpathocrg g where g.groupcode = (select groupcode from tpathocrd r where cardcode = T0.CONTRAACT)) LIKE '%ligada%' THEN 'Y' ELSE 'N' END COLIGADA,  
	T0.TRANSID TRANSIDOJDT, T4.BASEREF DOCORIGEM, 0 NFORIGEM, T0.ACCOUNT CODCONTAORIGEM, UPPER(T5.acctNAME) NOMCONTAORIGEM, T0.REFDATE DTORIGEM, 'SEM_SUPERVISOR' SUPERVISOR, T0.CONTRAACT CODPN, UPPER(T6.acctNAME) NOMEPN, REPLACE(REPLACE(REPLACE(COALESCE(T4.MEMO,''),CHAR(13),' '),CHAR(10),' '),CHAR(9),' ') OBSORIGEM,
'### SEM_PGTO ###' FORMA_PGTO
FROM 
	tpathJDT1 T0 INNER JOIN
	tpathOJDT T4 ON T0.BASEREF = T4.BASEREF INNER JOIN
	tpathFluxoMaster T1 on T1.TRANSID = T0.TRANSID INNER JOIN 
	tpathOACT T5 ON T5.ACCTCODE = T0.Account LEFT JOIN
	tpathOACT T6 ON T6.ACCTCODE = T0.CONTRAACT 
WHERE 
	T0.CONTRAACT like '1.1.01%' AND T0.TRANSTYPE = 30


--complementos essenciais ao funcionamento do fluxo de caixa:

INSERT INTO tpathFluxoDetalhe
SELECT DISTINCT @empresa AS BASE, 46 INVTYPE, 0, CASE WHEN (select G.GROUPNAME from tpathocrg g where g.groupcode = (select groupcode from tpathocrd r where cardcode = T2.CARDCODE)) LIKE '%ligada%' THEN 'Y' ELSE 'N' END COLIGADA,  
	T1.TRANSID TRANSIDOJDT, t2.DOCENTRY DOCORIGEM, 0 NFORIGEM, t2.TRSFRACCT CODCONTAORIGEM, UPPER(T5.acctNAME) NOMCONTAORIGEM, t2.TRSFRDATE DTORIGEM, ('SEM_SUPERVISOR') SUPERVISOR, t2.CARDCODE CODPN, UPPER(T8.acctNAME) NOMEPN, REPLACE(REPLACE(REPLACE(COALESCE(t2.JRNLMEMO,''),CHAR(13),' '),CHAR(10),' '),CHAR(9),' ') OBSORIGEM,
	CASE
			WHEN t2.DdctSumSy > 0 THEN '###DEDUCTION###'
			WHEN t2.CashSumSy > 0 THEN 'DINHEIRO'
			WHEN t2.CredSumSy > 0 THEN 'CARTAO'
			WHEN t2.CheckSumSy> 0 THEN 'CHEQUE'
			WHEN t2.TrsfrSumSy> 0 THEN 'TRANSFERENCIA'
			WHEN t2.NoDocSumSy> 0 THEN '###NO_DOC###'
			ELSE 'X'
		END  FORMA_PGTO
FROM 
	tpathFluxoMaster T1 INNER JOIN 
	tpathOVPM T2 ON T1.EXTREF = T2.DOCNUM left join
	tpathOACT T5 ON T5.ACCTCODE = t2.TRSFRACCT left join
	tpathOACT T8 ON T8.ACCTCODE = t2.CardCode
WHERE
	T1.[contacod] like '1.1.01%' AND T1.TRANSTYPE = 46 and (select top 1 invtype from tpathVPM2 where docnum = t2.docentry) is null

INSERT INTO tpathFluxoDetalhe
SELECT DISTINCT @empresa AS BASE, 24 INVTYPE, 0, CASE WHEN (select G.GROUPNAME from tpathocrg g where g.groupcode = (select groupcode from tpathocrd r where cardcode = T2.CARDCODE)) LIKE '%ligada%' THEN 'Y' ELSE 'N' END COLIGADA,  
	T1.TRANSID TRANSIDOJDT, t2.DOCENTRY DOCORIGEM, 0 NFORIGEM, t2.TRSFRACCT CODCONTAORIGEM, UPPER(T5.acctNAME) NOMCONTAORIGEM, t2.TRSFRDATE DTORIGEM, ('SEM_SUPERVISOR') SUPERVISOR, t2.CARDCODE CODPN, t2.CARDNAME NOMEPN, REPLACE(REPLACE(REPLACE(COALESCE(t2.JRNLMEMO,''),CHAR(13),' '),CHAR(10),' '),CHAR(9),' ') OBSORIGEM,
	CASE
			WHEN t2.DdctSumSy > 0 THEN '###DEDUCTION###'
			WHEN t2.CashSumSy > 0 THEN 'DINHEIRO'
			WHEN t2.CredSumSy > 0 THEN 'CARTAO'
			WHEN t2.CheckSumSy> 0 THEN 'CHEQUE'
			WHEN t2.TrsfrSumSy> 0 THEN 'TRANSFERENCIA'
			WHEN t2.NoDocSumSy> 0 THEN '###NO_DOC###'
			ELSE 'X'
		END  FORMA_PGTO
FROM 
	tpathFluxoMaster T1 INNER JOIN 
	tpathORCT T2 ON T1.EXTREF = T2.DOCNUM left join
	tpathOACT T5 ON T5.ACCTCODE = t2.TRSFRACCT
WHERE
	T1.[contacod] like '1.1.01%' AND T1.TRANSTYPE = 24 and (select top 1 invtype from tpathRCT2 where docnum = t2.docentry) is null

UPDATE tpathFluxoDetalhe SET COLIGADA = 'N' WHERE COLIGADA IS NULL OR COLIGADA = ''

END;

--EXCLUI AS LINHAS DUPLICADAS DOS LANCAMENTOS DOS DETALHES
DELETE FROM tpathFluxoDetalhe WHERE [LINEID] <> 0

--SELECIONA OS VALORES FORMATADOS PARA EXIBICAO NO EXCEL
SELECT 
	 M.[BASE]
	,M.[FILIAL]
	,M.[CNPJ]
	,D.[COLIGADA]
	,M.[TRANSID]
	,M.[EXTREF]
	,M.[TRANSTYPE]
	,CAST(M.[REFDATE] AS DATE) REFDATE
	,M.[CONTACOD]
	,M.[CONTANOME]
	,M.[LINE_ID]
	,M.[CONTRAACT]
	,M.[SHORTNAME]
	,M.[DEBCRED]
	,M.[DESCRICAO]
	,M.[USUARIO]
	,D.[INVTYPE]
	,D.[LINEID]
	,D.[DOCORIGEM]
	,D.[NFORIGEM]
	,D.[CODCONTAORIGEM]
	,D.[NOMCONTAORIGEM]
	,CAST(D.[DTORIGEM] AS DATE) DTORIGEM
	,D.[CODPN]
	,D.[NOMEPN]
	,D.[SUPERVISOR]
	,D.[OBSORIGEM]
	,D.[FORMA_PGTO]
	,CAST(M.[VLRTOTAL] AS FLOAT) [VLRTOTAL]
	,CAST(M.[DEBIT]	AS FLOAT) [DEBITO]
	,CAST(M.[CREDIT] AS FLOAT) [CREDITO]
	,CAST(M.[SALDO]	AS FLOAT) [SALDO]
FROM
	tpathFluxoMaster M LEFT JOIN
	tpathFluxoDetalhe D ON D.TRANSIDOJDT = M.TRANSID AND D.BASE = M.BASE
WHERE
	D.[CODCONTAORIGEM] = (SELECT TOP 1 [CODCONTAORIGEM] FROM tpathFluxoDetalhe WHERE TRANSIDOJDT = M.TRANSID AND BASE = M.BASE) OR D.[CODCONTAORIGEM] IS NULL



SELECT * FROM MBS.DBO.[Fluxo_Master] 
SELECT * FROM MBS.DBO.[Fluxo_Detalhe]