--------------------------------------------------------
--// TEMA: PROJETO INSERE NOVOS CENTROS DE CUSTOS 2020
--// -----------------------------------------------------
--// CRIADO POR: RODRIGO MATOS (CIENTISTA DADOS)
--// VERSAO: 1.0.0		
--// DATA: 18.MAIO.2020
--// SOLIC.: SOLANGE DA MATA
--------------------------------------------------------

--//OBSERVACAO: PRIMEIRO ATUALIZE AS TABELAS DA BASE SBOTESTE2 COLANDO DO EXCEL
	DELETE from SBOTESTE2.DBO.oprc where prccode NOT like 'centr_z%'
	DELETE from SBOTESTE2.DBO.OOCR
	DELETE from SBOTESTE2.DBO.OCR1


--// ATUALIZA TODAS AS TABELAS OPRC //--

BEGIN TRAN
	INSERT INTO SBOA7.DBO.OPRC SELECT * FROM SBOTESTE2.DBO.OPRC WHERE prccode NOT like 'centr_z%'
	INSERT INTO SboChuaChua.DBO.OPRC SELECT * FROM SBOTESTE2.DBO.OPRC WHERE prccode NOT like 'centr_z%'
	INSERT INTO SBODL.DBO.OPRC SELECT * FROM SBOTESTE2.DBO.OPRC WHERE prccode NOT like 'centr_z%'
	INSERT INTO SBOEmpLREZENDE.DBO.OPRC SELECT * FROM SBOTESTE2.DBO.OPRC WHERE prccode NOT like 'centr_z%'
	INSERT INTO SBOEmpreendimentosRZ.DBO.OPRC SELECT * FROM SBOTESTE2.DBO.OPRC WHERE prccode NOT like 'centr_z%'
	INSERT INTO SBOEmpreendimentosSM.DBO.OPRC SELECT * FROM SBOTESTE2.DBO.OPRC WHERE prccode NOT like 'centr_z%'
	INSERT INTO SBOEquilibrium.DBO.OPRC SELECT * FROM SBOTESTE2.DBO.OPRC WHERE prccode NOT like 'centr_z%'
	INSERT INTO SBOGDSMARCAS.DBO.OPRC SELECT * FROM SBOTESTE2.DBO.OPRC WHERE prccode NOT like 'centr_z%'
	INSERT INTO SBOGdsMarcasEU.DBO.OPRC SELECT * FROM SBOTESTE2.DBO.OPRC WHERE prccode NOT like 'centr_z%'
	INSERT INTO SBOInfinix1.DBO.OPRC SELECT * FROM SBOTESTE2.DBO.OPRC WHERE prccode NOT like 'centr_z%'
	INSERT INTO SBOInfinix2.DBO.OPRC SELECT * FROM SBOTESTE2.DBO.OPRC WHERE prccode NOT like 'centr_z%'
	INSERT INTO SBOInnovaBR.DBO.OPRC SELECT * FROM SBOTESTE2.DBO.OPRC WHERE prccode NOT like 'centr_z%'
	INSERT INTO SboInnovaLab.DBO.OPRC SELECT * FROM SBOTESTE2.DBO.OPRC WHERE prccode NOT like 'centr_z%'
	INSERT INTO SBOInnovaPA.DBO.OPRC SELECT * FROM SBOTESTE2.DBO.OPRC WHERE prccode NOT like 'centr_z%'
	INSERT INTO SBOLCA.DBO.OPRC SELECT * FROM SBOTESTE2.DBO.OPRC WHERE prccode NOT like 'centr_z%'
	INSERT INTO SBOLICITAACAO.DBO.OPRC SELECT * FROM SBOTESTE2.DBO.OPRC WHERE prccode NOT like 'centr_z%'
	INSERT INTO SBOML.DBO.OPRC SELECT * FROM SBOTESTE2.DBO.OPRC WHERE prccode NOT like 'centr_z%'
	INSERT INTO SBOMW.DBO.OPRC SELECT * FROM SBOTESTE2.DBO.OPRC WHERE prccode NOT like 'centr_z%'
	INSERT INTO SBONutGynMatriz.DBO.OPRC SELECT * FROM SBOTESTE2.DBO.OPRC WHERE prccode NOT like 'centr_z%'
	INSERT INTO SBONutriexInd.DBO.OPRC SELECT * FROM SBOTESTE2.DBO.OPRC WHERE prccode NOT like 'centr_z%'
	INSERT INTO SboOralls.DBO.OPRC SELECT * FROM SBOTESTE2.DBO.OPRC WHERE prccode NOT like 'centr_z%'
	INSERT INTO SBORZLaboratorios.DBO.OPRC SELECT * FROM SBOTESTE2.DBO.OPRC WHERE prccode NOT like 'centr_z%'
	INSERT INTO SBOVidafarma.DBO.OPRC SELECT * FROM SBOTESTE2.DBO.OPRC WHERE prccode NOT like 'centr_z%'
	INSERT INTO SBOVZ.DBO.OPRC SELECT * FROM SBOTESTE2.DBO.OPRC WHERE prccode NOT like 'centr_z%'
	INSERT INTO SBOZ9.DBO.OPRC SELECT * FROM SBOTESTE2.DBO.OPRC WHERE prccode NOT like 'centr_z%'
ROLLBACK TRAN


--// ATUALIZA TODAS AS TABELAS OOCR //--

BEGIN TRAN
	INSERT INTO SBOA7.DBO.OOCR SELECT * FROM SBOTESTE2.DBO.OOCR
	INSERT INTO SboChuaChua.DBO.OOCR SELECT * FROM SBOTESTE2.DBO.OOCR
	INSERT INTO SBODL.DBO.OOCR SELECT * FROM SBOTESTE2.DBO.OOCR
	INSERT INTO SBOEmpLREZENDE.DBO.OOCR SELECT * FROM SBOTESTE2.DBO.OOCR
	INSERT INTO SBOEmpreendimentosRZ.DBO.OOCR SELECT * FROM SBOTESTE2.DBO.OOCR
	INSERT INTO SBOEmpreendimentosSM.DBO.OOCR SELECT * FROM SBOTESTE2.DBO.OOCR
	INSERT INTO SBOEquilibrium.DBO.OOCR SELECT * FROM SBOTESTE2.DBO.OOCR
	INSERT INTO SBOGDSMARCAS.DBO.OOCR SELECT * FROM SBOTESTE2.DBO.OOCR
	INSERT INTO SBOGdsMarcasEU.DBO.OOCR SELECT * FROM SBOTESTE2.DBO.OOCR
	INSERT INTO SBOInfinix1.DBO.OOCR SELECT * FROM SBOTESTE2.DBO.OOCR
	INSERT INTO SBOInfinix2.DBO.OOCR SELECT * FROM SBOTESTE2.DBO.OOCR
	INSERT INTO SBOInnovaBR.DBO.OOCR SELECT * FROM SBOTESTE2.DBO.OOCR
	INSERT INTO SboInnovaLab.DBO.OOCR SELECT * FROM SBOTESTE2.DBO.OOCR
	INSERT INTO SBOInnovaPA.DBO.OOCR SELECT * FROM SBOTESTE2.DBO.OOCR
	INSERT INTO SBOLCA.DBO.OOCR SELECT * FROM SBOTESTE2.DBO.OOCR
	INSERT INTO SBOLICITAACAO.DBO.OOCR SELECT * FROM SBOTESTE2.DBO.OOCR
	INSERT INTO SBOML.DBO.OOCR SELECT * FROM SBOTESTE2.DBO.OOCR
	INSERT INTO SBOMW.DBO.OOCR SELECT * FROM SBOTESTE2.DBO.OOCR
	INSERT INTO SBONutGynMatriz.DBO.OOCR SELECT * FROM SBOTESTE2.DBO.OOCR
	INSERT INTO SBONutriexInd.DBO.OOCR SELECT * FROM SBOTESTE2.DBO.OOCR
	INSERT INTO SboOralls.DBO.OOCR SELECT * FROM SBOTESTE2.DBO.OOCR
	INSERT INTO SBORZLaboratorios.DBO.OOCR SELECT * FROM SBOTESTE2.DBO.OOCR
	INSERT INTO SBOVidafarma.DBO.OOCR SELECT * FROM SBOTESTE2.DBO.OOCR
	INSERT INTO SBOVZ.DBO.OOCR SELECT * FROM SBOTESTE2.DBO.OOCR
	INSERT INTO SBOZ9.DBO.OOCR SELECT * FROM SBOTESTE2.DBO.OOCR
ROLLBACK TRAN



--// ATUALIZA TODAS AS TABELAS OCR1 //--

BEGIN TRAN
	INSERT INTO SBOA7.DBO.OCR1 SELECT * FROM SBOTESTE2.DBO.OCR1
	INSERT INTO SboChuaChua.DBO.OCR1 SELECT * FROM SBOTESTE2.DBO.OCR1
	INSERT INTO SBODL.DBO.OCR1 SELECT * FROM SBOTESTE2.DBO.OCR1
	INSERT INTO SBOEmpLREZENDE.DBO.OCR1 SELECT * FROM SBOTESTE2.DBO.OCR1
	INSERT INTO SBOEmpreendimentosRZ.DBO.OCR1 SELECT * FROM SBOTESTE2.DBO.OCR1
	INSERT INTO SBOEmpreendimentosSM.DBO.OCR1 SELECT * FROM SBOTESTE2.DBO.OCR1
	INSERT INTO SBOEquilibrium.DBO.OCR1 SELECT * FROM SBOTESTE2.DBO.OCR1
	INSERT INTO SBOGDSMARCAS.DBO.OCR1 SELECT * FROM SBOTESTE2.DBO.OCR1
	INSERT INTO SBOGdsMarcasEU.DBO.OCR1 SELECT * FROM SBOTESTE2.DBO.OCR1
	INSERT INTO SBOInfinix1.DBO.OCR1 SELECT * FROM SBOTESTE2.DBO.OCR1
	INSERT INTO SBOInfinix2.DBO.OCR1 SELECT * FROM SBOTESTE2.DBO.OCR1
	INSERT INTO SBOInnovaBR.DBO.OCR1 SELECT * FROM SBOTESTE2.DBO.OCR1
	INSERT INTO SboInnovaLab.DBO.OCR1 SELECT * FROM SBOTESTE2.DBO.OCR1
	INSERT INTO SBOInnovaPA.DBO.OCR1 SELECT * FROM SBOTESTE2.DBO.OCR1
	INSERT INTO SBOLCA.DBO.OCR1 SELECT * FROM SBOTESTE2.DBO.OCR1
	INSERT INTO SBOLICITAACAO.DBO.OCR1 SELECT * FROM SBOTESTE2.DBO.OCR1
	INSERT INTO SBOML.DBO.OCR1 SELECT * FROM SBOTESTE2.DBO.OCR1
	INSERT INTO SBOMW.DBO.OCR1 SELECT * FROM SBOTESTE2.DBO.OCR1
	INSERT INTO SBONutGynMatriz.DBO.OCR1 SELECT * FROM SBOTESTE2.DBO.OCR1
	INSERT INTO SBONutriexInd.DBO.OCR1 SELECT * FROM SBOTESTE2.DBO.OCR1
	INSERT INTO SboOralls.DBO.OCR1 SELECT * FROM SBOTESTE2.DBO.OCR1
	INSERT INTO SBORZLaboratorios.DBO.OCR1 SELECT * FROM SBOTESTE2.DBO.OCR1
	INSERT INTO SBOVidafarma.DBO.OCR1 SELECT * FROM SBOTESTE2.DBO.OCR1
	INSERT INTO SBOVZ.DBO.OCR1 SELECT * FROM SBOTESTE2.DBO.OCR1
	INSERT INTO SBOZ9.DBO.OCR1 SELECT * FROM SBOTESTE2.DBO.OCR1
ROLLBACK TRAN