--ROBO PARA GERAR O BANCO DE HORAS ATUAL DOS FUNCIONARIOS DE TODAS AS EMPRESAS CADASTRADAS NO FPW NUTRIEX/RENNOVA GYN
--POR RODRIGO MATOS (CIENTISTA DE DADOS) EM 2020-09-22

SELECT 
	 E.EMNOMEMP + ' (' + FORMAT(F.FUCODEMP,'00') + ')' EMPRESA
	,F.FUMATFUNC MATRICULA
	,F.FUNOMFUNC FUNCIONARIO
 	,C.CCDESCRIC CENTRO_CUSTO
	,m.MUDESMUNIC + ', ' + m.muuf CIDADE
	,[BCANOMES] PERIODO
 	,COALESCE(ROUND((SELECT TOP 1 [BCSALDOINI] FROM [FPW5].[dbo].[BANCOHOR] WHERE [BCANOMES] = B.[BCANOMES]-1 AND BCEMPSIS = E.EMCODEMP AND BCMATRICULA = F.FUMATFUNC),2),0) [--> SALDO_ANT]
    ,ROUND([BCHRCOMP],2) [(-) SALDO_COMP]
    ,ROUND([BCHREXTRA],2) [(+) SALDO_HEXTRA]
	,ROUND([BCSALDOINI],2) [(=) SALDO_BCH]
FROM 
	[FPW5].[dbo].[BANCOHOR] b inner join
	[FPW5].[dbo].funciona F on f.FUMATFUNC = b.BCMATRICULA and f.FUCODEMP = b.BCEMPSIS INNER JOIN
	[FPW5].[dbo].empresas e on e.EMCODEMP = b.BCEMPSIS INNER JOIN
	[FPW5].[dbo].MUNICIP m on m.MUCODMUNIC = f.FUCODMUNIC LEFT JOIN 
	[FPW5].[dbo].[CENCUSTO] C ON C.[CCCODIGO] = F.[FUCENTRCUS] AND C.[CCCODEMP] = b.BCEMPSIS 
where bcanomes = CAST(FORMAT(GETDATE(),'yyyyMM') AS INT)




