drop table mbs..xxx
drop table mbs..yyy

CREATE TABLE mbs.[dbo].[xxx](
	[BASE] [nvarchar](55) NULL,
	[DOCNFETransp] [int] NULL,
	[DOCRECEBTransp] [int] NULL,
	[NFNumTRANSP] [int] NULL,
	[NFNumSAIDANutriexOLD] [nvarchar](400) NULL,
	[NFNumSAIDANutriexNEW] [nvarchar](400) NULL,
	[TRANSACAO] [int] NULL,
	[DTCTE] [nvarchar](4000) NULL,
	[CTENum] [int] NULL,
	[DTDOC] [nvarchar](4000) NULL,
	[COD] [nvarchar](15) NULL,
	[FORNECEDOR] [nvarchar](100) NULL,
	[CANCELADA?] [char](5) NULL,
	[PROJETO] [nvarchar](100) NULL,
	[ITEM] [nvarchar](50) NULL,
	[DESCRICAO] [nvarchar](100) NULL,
	[VLRFATURA] [float] NULL
) ON [PRIMARY]


CREATE TABLE mbs.[dbo].[yyy](
	[BASE] [nvarchar](55) NULL,
	[DOCNFETransp] [int] NULL,
	[DOCRECEBTransp] [int] NULL,
	[NFNumTRANSP] [int] NULL,
	[TRANSACAO] [int] NULL,
	[DTCTE] [nvarchar](4000) NULL,
	[CTENum] [int] NULL,
	[DTDOC] [nvarchar](4000) NULL,
	[COD] [nvarchar](15) NULL,
	[FORNECEDOR] [nvarchar](100) NULL,
	[CANCELADA?] [char](5) NULL,
	[PROJETO] [nvarchar](100) NULL,
	[ITEM] [nvarchar](50) NULL,
	[DESCRICAO] [nvarchar](100) NULL,
	[VLRFATURA] [float] NULL,
	[NFNumSAIDANutriexOLD] [nvarchar](400) NULL,
	[NFNumSAIDANutriexNEW] [nvarchar](400) NULL
) ON [PRIMARY]

insert into mbs..xxx
	select 'SBOA7' BASE, o.docentry DOCNFETransp, p.baseentry DOCRECEBTransp, o.serial NFNumTRANSP, REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),';',' ') [NFNumSAIDANutriexOLD], replace(replace(case when left(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),1) = '|' then substring(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),2,len(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')))) else mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')) end,'|',';'),';;',';') NFNumSAIDANutriexNEW, o.transid TRANSACAO, FORMAT(n.TAXDATE,'yyyy/MM') DTCTE, n.serial CTENum, FORMAT(o.docdate,'yyyy/MM') DTDOC, o.cardcode COD, O.CARDNAME FORNECEDOR, o.canceled [CANCELADA?], j.prjname PROJETO, p.itemcode ITEM, p.dscription DESCRICAO, cast(p.linetotal as float) VLRFATURA from SBOA7..pch1 p inner join SBOA7..opch o on o.docentry = p.docentry inner join SBOA7..opdn n on n.docentry = p.baseentry left join SBOA7..oprj j on j.PrjCode = o.project where p.dscription like '%frete%' and YEAR(N.TAXDATE) = 2020 AND o.canceled <> 'C' UNION
	select 'SboChuaChua' BASE, o.docentry DOCNFETransp, p.baseentry DOCRECEBTransp, o.serial NFNumTRANSP, REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),';',' ') [NFNumSAIDANutriexOLD], replace(replace(case when left(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),1) = '|' then substring(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),2,len(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')))) else mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')) end,'|',';'),';;',';') NFNumSAIDANutriexNEW, o.transid TRANSACAO, FORMAT(n.TAXDATE,'yyyy/MM') DTCTE, n.serial CTENum, FORMAT(o.docdate,'yyyy/MM') DTDOC, o.cardcode COD, O.CARDNAME FORNECEDOR, o.canceled [CANCELADA?], j.prjname PROJETO, p.itemcode ITEM, p.dscription DESCRICAO, cast(p.linetotal as float) VLRFATURA from SboChuaChua..pch1 p inner join SboChuaChua..opch o on o.docentry = p.docentry inner join SboChuaChua..opdn n on n.docentry = p.baseentry left join SboChuaChua..oprj j on j.PrjCode = o.project where p.dscription like '%frete%' and YEAR(N.TAXDATE) = 2020 AND o.canceled <> 'C' UNION ALL 
	select 'SBODL' BASE, o.docentry DOCNFETransp, p.baseentry DOCRECEBTransp, o.serial NFNumTRANSP, REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),';',' ') [NFNumSAIDANutriexOLD], replace(replace(case when left(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),1) = '|' then substring(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),2,len(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')))) else mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')) end,'|',';'),';;',';') NFNumSAIDANutriexNEW, o.transid TRANSACAO, FORMAT(n.TAXDATE,'yyyy/MM') DTCTE, n.serial CTENum, FORMAT(o.docdate,'yyyy/MM') DTDOC, o.cardcode COD, O.CARDNAME FORNECEDOR, o.canceled [CANCELADA?], j.prjname PROJETO, p.itemcode ITEM, p.dscription DESCRICAO, cast(p.linetotal as float) VLRFATURA from SBODL..pch1 p inner join SBODL..opch o on o.docentry = p.docentry inner join SBODL..opdn n on n.docentry = p.baseentry left join SBODL..oprj j on j.PrjCode = o.project where p.dscription like '%frete%' and YEAR(N.TAXDATE) = 2020 AND o.canceled <> 'C' UNION ALL 
	select 'SBOEmpLREZENDE' BASE, o.docentry DOCNFETransp, p.baseentry DOCRECEBTransp, o.serial NFNumTRANSP, REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),';',' ') [NFNumSAIDANutriexOLD], replace(replace(case when left(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),1) = '|' then substring(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),2,len(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')))) else mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')) end,'|',';'),';;',';') NFNumSAIDANutriexNEW, o.transid TRANSACAO, FORMAT(n.TAXDATE,'yyyy/MM') DTCTE, n.serial CTENum, FORMAT(o.docdate,'yyyy/MM') DTDOC, o.cardcode COD, O.CARDNAME FORNECEDOR, o.canceled [CANCELADA?], j.prjname PROJETO, p.itemcode ITEM, p.dscription DESCRICAO, cast(p.linetotal as float) VLRFATURA from SBOEmpLREZENDE..pch1 p inner join SBOEmpLREZENDE..opch o on o.docentry = p.docentry inner join SBOEmpLREZENDE..opdn n on n.docentry = p.baseentry left join SBOEmpLREZENDE..oprj j on j.PrjCode = o.project where p.dscription like '%frete%' and YEAR(N.TAXDATE) = 2020 AND o.canceled <> 'C' UNION ALL 
	select 'SBOEmpreendimentosRZ' BASE, o.docentry DOCNFETransp, p.baseentry DOCRECEBTransp, o.serial NFNumTRANSP, REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),';',' ') [NFNumSAIDANutriexOLD], replace(replace(case when left(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),1) = '|' then substring(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),2,len(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')))) else mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')) end,'|',';'),';;',';') NFNumSAIDANutriexNEW, o.transid TRANSACAO, FORMAT(n.TAXDATE,'yyyy/MM') DTCTE, n.serial CTENum, FORMAT(o.docdate,'yyyy/MM') DTDOC, o.cardcode COD, O.CARDNAME FORNECEDOR, o.canceled [CANCELADA?], j.prjname PROJETO, p.itemcode ITEM, p.dscription DESCRICAO, cast(p.linetotal as float) VLRFATURA from SBOEmpreendimentosRZ..pch1 p inner join SBOEmpreendimentosRZ..opch o on o.docentry = p.docentry inner join SBOEmpreendimentosRZ..opdn n on n.docentry = p.baseentry left join SBOEmpreendimentosRZ..oprj j on j.PrjCode = o.project where p.dscription like '%frete%' and YEAR(N.TAXDATE) = 2020 AND o.canceled <> 'C' UNION ALL 
	select 'SBOEmpreendimentosSM' BASE, o.docentry DOCNFETransp, p.baseentry DOCRECEBTransp, o.serial NFNumTRANSP, REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),';',' ') [NFNumSAIDANutriexOLD], replace(replace(case when left(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),1) = '|' then substring(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),2,len(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')))) else mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')) end,'|',';'),';;',';') NFNumSAIDANutriexNEW, o.transid TRANSACAO, FORMAT(n.TAXDATE,'yyyy/MM') DTCTE, n.serial CTENum, FORMAT(o.docdate,'yyyy/MM') DTDOC, o.cardcode COD, O.CARDNAME FORNECEDOR, o.canceled [CANCELADA?], j.prjname PROJETO, p.itemcode ITEM, p.dscription DESCRICAO, cast(p.linetotal as float) VLRFATURA from SBOEmpreendimentosSM..pch1 p inner join SBOEmpreendimentosSM..opch o on o.docentry = p.docentry inner join SBOEmpreendimentosSM..opdn n on n.docentry = p.baseentry left join SBOEmpreendimentosSM..oprj j on j.PrjCode = o.project where p.dscription like '%frete%' and YEAR(N.TAXDATE) = 2020 AND o.canceled <> 'C' UNION ALL 
	select 'SBOEquilibrium' BASE, o.docentry DOCNFETransp, p.baseentry DOCRECEBTransp, o.serial NFNumTRANSP, REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),';',' ') [NFNumSAIDANutriexOLD], replace(replace(case when left(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),1) = '|' then substring(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),2,len(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')))) else mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')) end,'|',';'),';;',';') NFNumSAIDANutriexNEW, o.transid TRANSACAO, FORMAT(n.TAXDATE,'yyyy/MM') DTCTE, n.serial CTENum, FORMAT(o.docdate,'yyyy/MM') DTDOC, o.cardcode COD, O.CARDNAME FORNECEDOR, o.canceled [CANCELADA?], j.prjname PROJETO, p.itemcode ITEM, p.dscription DESCRICAO, cast(p.linetotal as float) VLRFATURA from SBOEquilibrium..pch1 p inner join SBOEquilibrium..opch o on o.docentry = p.docentry inner join SBOEquilibrium..opdn n on n.docentry = p.baseentry left join SBOEquilibrium..oprj j on j.PrjCode = o.project where p.dscription like '%frete%' and YEAR(N.TAXDATE) = 2020 AND o.canceled <> 'C' UNION ALL 
	select 'SBOGDSMARCAS' BASE, o.docentry DOCNFETransp, p.baseentry DOCRECEBTransp, o.serial NFNumTRANSP, REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),';',' ') [NFNumSAIDANutriexOLD], replace(replace(case when left(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),1) = '|' then substring(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),2,len(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')))) else mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')) end,'|',';'),';;',';') NFNumSAIDANutriexNEW, o.transid TRANSACAO, FORMAT(n.TAXDATE,'yyyy/MM') DTCTE, n.serial CTENum, FORMAT(o.docdate,'yyyy/MM') DTDOC, o.cardcode COD, O.CARDNAME FORNECEDOR, o.canceled [CANCELADA?], j.prjname PROJETO, p.itemcode ITEM, p.dscription DESCRICAO, cast(p.linetotal as float) VLRFATURA from SBOGDSMARCAS..pch1 p inner join SBOGDSMARCAS..opch o on o.docentry = p.docentry inner join SBOGDSMARCAS..opdn n on n.docentry = p.baseentry left join SBOGDSMARCAS..oprj j on j.PrjCode = o.project where p.dscription like '%frete%' and YEAR(N.TAXDATE) = 2020 AND o.canceled <> 'C' UNION ALL 
	select 'SBOGdsMarcasEU' BASE, o.docentry DOCNFETransp, p.baseentry DOCRECEBTransp, o.serial NFNumTRANSP, REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),';',' ') [NFNumSAIDANutriexOLD], replace(replace(case when left(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),1) = '|' then substring(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),2,len(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')))) else mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')) end,'|',';'),';;',';') NFNumSAIDANutriexNEW, o.transid TRANSACAO, FORMAT(n.TAXDATE,'yyyy/MM') DTCTE, n.serial CTENum, FORMAT(o.docdate,'yyyy/MM') DTDOC, o.cardcode COD, O.CARDNAME FORNECEDOR, o.canceled [CANCELADA?], j.prjname PROJETO, p.itemcode ITEM, p.dscription DESCRICAO, cast(p.linetotal as float) VLRFATURA from SBOGdsMarcasEU..pch1 p inner join SBOGdsMarcasEU..opch o on o.docentry = p.docentry inner join SBOGdsMarcasEU..opdn n on n.docentry = p.baseentry left join SBOGdsMarcasEU..oprj j on j.PrjCode = o.project where p.dscription like '%frete%' and YEAR(N.TAXDATE) = 2020 AND o.canceled <> 'C' UNION ALL 
	select 'SBOInfinix1' BASE, o.docentry DOCNFETransp, p.baseentry DOCRECEBTransp, o.serial NFNumTRANSP, REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),';',' ') [NFNumSAIDANutriexOLD], replace(replace(case when left(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),1) = '|' then substring(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),2,len(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')))) else mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')) end,'|',';'),';;',';') NFNumSAIDANutriexNEW, o.transid TRANSACAO, FORMAT(n.TAXDATE,'yyyy/MM') DTCTE, n.serial CTENum, FORMAT(o.docdate,'yyyy/MM') DTDOC, o.cardcode COD, O.CARDNAME FORNECEDOR, o.canceled [CANCELADA?], j.prjname PROJETO, p.itemcode ITEM, p.dscription DESCRICAO, cast(p.linetotal as float) VLRFATURA from SBOInfinix1..pch1 p inner join SBOInfinix1..opch o on o.docentry = p.docentry inner join SBOInfinix1..opdn n on n.docentry = p.baseentry left join SBOInfinix1..oprj j on j.PrjCode = o.project where p.dscription like '%frete%' and YEAR(N.TAXDATE) = 2020 AND o.canceled <> 'C' UNION ALL 
	select 'SBOInfinix2' BASE, o.docentry DOCNFETransp, p.baseentry DOCRECEBTransp, o.serial NFNumTRANSP, REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),';',' ') [NFNumSAIDANutriexOLD], replace(replace(case when left(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),1) = '|' then substring(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),2,len(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')))) else mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')) end,'|',';'),';;',';') NFNumSAIDANutriexNEW, o.transid TRANSACAO, FORMAT(n.TAXDATE,'yyyy/MM') DTCTE, n.serial CTENum, FORMAT(o.docdate,'yyyy/MM') DTDOC, o.cardcode COD, O.CARDNAME FORNECEDOR, o.canceled [CANCELADA?], j.prjname PROJETO, p.itemcode ITEM, p.dscription DESCRICAO, cast(p.linetotal as float) VLRFATURA from SBOInfinix2..pch1 p inner join SBOInfinix2..opch o on o.docentry = p.docentry inner join SBOInfinix2..opdn n on n.docentry = p.baseentry left join SBOInfinix2..oprj j on j.PrjCode = o.project where p.dscription like '%frete%' and YEAR(N.TAXDATE) = 2020 AND o.canceled <> 'C' UNION ALL 
	select 'SBOInnovaBR' BASE, o.docentry DOCNFETransp, p.baseentry DOCRECEBTransp, o.serial NFNumTRANSP, REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),';',' ') [NFNumSAIDANutriexOLD], replace(replace(case when left(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),1) = '|' then substring(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),2,len(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')))) else mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')) end,'|',';'),';;',';') NFNumSAIDANutriexNEW, o.transid TRANSACAO, FORMAT(n.TAXDATE,'yyyy/MM') DTCTE, n.serial CTENum, FORMAT(o.docdate,'yyyy/MM') DTDOC, o.cardcode COD, O.CARDNAME FORNECEDOR, o.canceled [CANCELADA?], j.prjname PROJETO, p.itemcode ITEM, p.dscription DESCRICAO, cast(p.linetotal as float) VLRFATURA from SBOInnovaBR..pch1 p inner join SBOInnovaBR..opch o on o.docentry = p.docentry inner join SBOInnovaBR..opdn n on n.docentry = p.baseentry left join SBOInnovaBR..oprj j on j.PrjCode = o.project where p.dscription like '%frete%' and YEAR(N.TAXDATE) = 2020 AND o.canceled <> 'C' UNION ALL 
	select 'SboInnovaLab' BASE, o.docentry DOCNFETransp, p.baseentry DOCRECEBTransp, o.serial NFNumTRANSP, REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),';',' ') [NFNumSAIDANutriexOLD], replace(replace(case when left(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),1) = '|' then substring(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),2,len(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')))) else mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')) end,'|',';'),';;',';') NFNumSAIDANutriexNEW, o.transid TRANSACAO, FORMAT(n.TAXDATE,'yyyy/MM') DTCTE, n.serial CTENum, FORMAT(o.docdate,'yyyy/MM') DTDOC, o.cardcode COD, O.CARDNAME FORNECEDOR, o.canceled [CANCELADA?], j.prjname PROJETO, p.itemcode ITEM, p.dscription DESCRICAO, cast(p.linetotal as float) VLRFATURA from SboInnovaLab..pch1 p inner join SboInnovaLab..opch o on o.docentry = p.docentry inner join SboInnovaLab..opdn n on n.docentry = p.baseentry left join SboInnovaLab..oprj j on j.PrjCode = o.project where p.dscription like '%frete%' and YEAR(N.TAXDATE) = 2020 AND o.canceled <> 'C' UNION ALL 
	select 'SBOInnovaPA' BASE, o.docentry DOCNFETransp, p.baseentry DOCRECEBTransp, o.serial NFNumTRANSP, REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),';',' ') [NFNumSAIDANutriexOLD], replace(replace(case when left(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),1) = '|' then substring(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),2,len(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')))) else mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')) end,'|',';'),';;',';') NFNumSAIDANutriexNEW, o.transid TRANSACAO, FORMAT(n.TAXDATE,'yyyy/MM') DTCTE, n.serial CTENum, FORMAT(o.docdate,'yyyy/MM') DTDOC, o.cardcode COD, O.CARDNAME FORNECEDOR, o.canceled [CANCELADA?], j.prjname PROJETO, p.itemcode ITEM, p.dscription DESCRICAO, cast(p.linetotal as float) VLRFATURA from SBOInnovaPA..pch1 p inner join SBOInnovaPA..opch o on o.docentry = p.docentry inner join SBOInnovaPA..opdn n on n.docentry = p.baseentry left join SBOInnovaPA..oprj j on j.PrjCode = o.project where p.dscription like '%frete%' and YEAR(N.TAXDATE) = 2020 AND o.canceled <> 'C' UNION ALL 
	select 'SBOLCA' BASE, o.docentry DOCNFETransp, p.baseentry DOCRECEBTransp, o.serial NFNumTRANSP, REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),';',' ') [NFNumSAIDANutriexOLD], replace(replace(case when left(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),1) = '|' then substring(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),2,len(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')))) else mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')) end,'|',';'),';;',';') NFNumSAIDANutriexNEW, o.transid TRANSACAO, FORMAT(n.TAXDATE,'yyyy/MM') DTCTE, n.serial CTENum, FORMAT(o.docdate,'yyyy/MM') DTDOC, o.cardcode COD, O.CARDNAME FORNECEDOR, o.canceled [CANCELADA?], j.prjname PROJETO, p.itemcode ITEM, p.dscription DESCRICAO, cast(p.linetotal as float) VLRFATURA from SBOLCA..pch1 p inner join SBOLCA..opch o on o.docentry = p.docentry inner join SBOLCA..opdn n on n.docentry = p.baseentry left join SBOLCA..oprj j on j.PrjCode = o.project where p.dscription like '%frete%' and YEAR(N.TAXDATE) = 2020 AND o.canceled <> 'C' UNION ALL 
	select 'SBOLICITAACAO' BASE, o.docentry DOCNFETransp, p.baseentry DOCRECEBTransp, o.serial NFNumTRANSP, REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),';',' ') [NFNumSAIDANutriexOLD], replace(replace(case when left(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),1) = '|' then substring(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),2,len(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')))) else mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')) end,'|',';'),';;',';') NFNumSAIDANutriexNEW, o.transid TRANSACAO, FORMAT(n.TAXDATE,'yyyy/MM') DTCTE, n.serial CTENum, FORMAT(o.docdate,'yyyy/MM') DTDOC, o.cardcode COD, O.CARDNAME FORNECEDOR, o.canceled [CANCELADA?], j.prjname PROJETO, p.itemcode ITEM, p.dscription DESCRICAO, cast(p.linetotal as float) VLRFATURA from SBOLICITAACAO..pch1 p inner join SBOLICITAACAO..opch o on o.docentry = p.docentry inner join SBOLICITAACAO..opdn n on n.docentry = p.baseentry left join SBOLICITAACAO..oprj j on j.PrjCode = o.project where p.dscription like '%frete%' and YEAR(N.TAXDATE) = 2020 AND o.canceled <> 'C' UNION ALL 
	select 'SBOML' BASE, o.docentry DOCNFETransp, p.baseentry DOCRECEBTransp, o.serial NFNumTRANSP, REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),';',' ') [NFNumSAIDANutriexOLD], replace(replace(case when left(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),1) = '|' then substring(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),2,len(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')))) else mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')) end,'|',';'),';;',';') NFNumSAIDANutriexNEW, o.transid TRANSACAO, FORMAT(n.TAXDATE,'yyyy/MM') DTCTE, n.serial CTENum, FORMAT(o.docdate,'yyyy/MM') DTDOC, o.cardcode COD, O.CARDNAME FORNECEDOR, o.canceled [CANCELADA?], j.prjname PROJETO, p.itemcode ITEM, p.dscription DESCRICAO, cast(p.linetotal as float) VLRFATURA from SBOML..pch1 p inner join SBOML..opch o on o.docentry = p.docentry inner join SBOML..opdn n on n.docentry = p.baseentry left join SBOML..oprj j on j.PrjCode = o.project where p.dscription like '%frete%' and YEAR(N.TAXDATE) = 2020 AND o.canceled <> 'C' UNION ALL 
	select 'SBOMW' BASE, o.docentry DOCNFETransp, p.baseentry DOCRECEBTransp, o.serial NFNumTRANSP, REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),';',' ') [NFNumSAIDANutriexOLD], replace(replace(case when left(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),1) = '|' then substring(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),2,len(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')))) else mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')) end,'|',';'),';;',';') NFNumSAIDANutriexNEW, o.transid TRANSACAO, FORMAT(n.TAXDATE,'yyyy/MM') DTCTE, n.serial CTENum, FORMAT(o.docdate,'yyyy/MM') DTDOC, o.cardcode COD, O.CARDNAME FORNECEDOR, o.canceled [CANCELADA?], j.prjname PROJETO, p.itemcode ITEM, p.dscription DESCRICAO, cast(p.linetotal as float) VLRFATURA from SBOMW..pch1 p inner join SBOMW..opch o on o.docentry = p.docentry inner join SBOMW..opdn n on n.docentry = p.baseentry left join SBOMW..oprj j on j.PrjCode = o.project where p.dscription like '%frete%' and YEAR(N.TAXDATE) = 2020 AND o.canceled <> 'C' UNION ALL 
	select 'SBONutGynMatriz' BASE, o.docentry DOCNFETransp, p.baseentry DOCRECEBTransp, o.serial NFNumTRANSP, REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),';',' ') [NFNumSAIDANutriexOLD], replace(replace(case when left(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),1) = '|' then substring(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),2,len(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')))) else mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')) end,'|',';'),';;',';') NFNumSAIDANutriexNEW, o.transid TRANSACAO, FORMAT(n.TAXDATE,'yyyy/MM') DTCTE, n.serial CTENum, FORMAT(o.docdate,'yyyy/MM') DTDOC, o.cardcode COD, O.CARDNAME FORNECEDOR, o.canceled [CANCELADA?], j.prjname PROJETO, p.itemcode ITEM, p.dscription DESCRICAO, cast(p.linetotal as float) VLRFATURA from SBONutGynMatriz..pch1 p inner join SBONutGynMatriz..opch o on o.docentry = p.docentry inner join SBONutGynMatriz..opdn n on n.docentry = p.baseentry left join SBONutGynMatriz..oprj j on j.PrjCode = o.project where p.dscription like '%frete%' and YEAR(N.TAXDATE) = 2020 AND o.canceled <> 'C' UNION ALL 
	select 'SBONutriexInd' BASE, o.docentry DOCNFETransp, p.baseentry DOCRECEBTransp, o.serial NFNumTRANSP, REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),';',' ') [NFNumSAIDANutriexOLD], replace(replace(case when left(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),1) = '|' then substring(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),2,len(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')))) else mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')) end,'|',';'),';;',';') NFNumSAIDANutriexNEW, o.transid TRANSACAO, FORMAT(n.TAXDATE,'yyyy/MM') DTCTE, n.serial CTENum, FORMAT(o.docdate,'yyyy/MM') DTDOC, o.cardcode COD, O.CARDNAME FORNECEDOR, o.canceled [CANCELADA?], j.prjname PROJETO, p.itemcode ITEM, p.dscription DESCRICAO, cast(p.linetotal as float) VLRFATURA from SBONutriexInd..pch1 p inner join SBONutriexInd..opch o on o.docentry = p.docentry inner join SBONutriexInd..opdn n on n.docentry = p.baseentry left join SBONutriexInd..oprj j on j.PrjCode = o.project where p.dscription like '%frete%' and YEAR(N.TAXDATE) = 2020 AND o.canceled <> 'C' UNION ALL 
	select 'SboOralls' BASE, o.docentry DOCNFETransp, p.baseentry DOCRECEBTransp, o.serial NFNumTRANSP, REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),';',' ') [NFNumSAIDANutriexOLD], replace(replace(case when left(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),1) = '|' then substring(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),2,len(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')))) else mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')) end,'|',';'),';;',';') NFNumSAIDANutriexNEW, o.transid TRANSACAO, FORMAT(n.TAXDATE,'yyyy/MM') DTCTE, n.serial CTENum, FORMAT(o.docdate,'yyyy/MM') DTDOC, o.cardcode COD, O.CARDNAME FORNECEDOR, o.canceled [CANCELADA?], j.prjname PROJETO, p.itemcode ITEM, p.dscription DESCRICAO, cast(p.linetotal as float) VLRFATURA from SboOralls..pch1 p inner join SboOralls..opch o on o.docentry = p.docentry inner join SboOralls..opdn n on n.docentry = p.baseentry left join SboOralls..oprj j on j.PrjCode = o.project where p.dscription like '%frete%' and YEAR(N.TAXDATE) = 2020 AND o.canceled <> 'C' UNION ALL 
	select 'SBORZLaboratorios' BASE, o.docentry DOCNFETransp, p.baseentry DOCRECEBTransp, o.serial NFNumTRANSP, REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),';',' ') [NFNumSAIDANutriexOLD], replace(replace(case when left(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),1) = '|' then substring(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),2,len(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')))) else mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')) end,'|',';'),';;',';') NFNumSAIDANutriexNEW, o.transid TRANSACAO, FORMAT(n.TAXDATE,'yyyy/MM') DTCTE, n.serial CTENum, FORMAT(o.docdate,'yyyy/MM') DTDOC, o.cardcode COD, O.CARDNAME FORNECEDOR, o.canceled [CANCELADA?], j.prjname PROJETO, p.itemcode ITEM, p.dscription DESCRICAO, cast(p.linetotal as float) VLRFATURA from SBORZLaboratorios..pch1 p inner join SBORZLaboratorios..opch o on o.docentry = p.docentry inner join SBORZLaboratorios..opdn n on n.docentry = p.baseentry left join SBORZLaboratorios..oprj j on j.PrjCode = o.project where p.dscription like '%frete%' and YEAR(N.TAXDATE) = 2020 AND o.canceled <> 'C' UNION ALL 
	select 'SBOVidafarma' BASE, o.docentry DOCNFETransp, p.baseentry DOCRECEBTransp, o.serial NFNumTRANSP, REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),';',' ') [NFNumSAIDANutriexOLD], replace(replace(case when left(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),1) = '|' then substring(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),2,len(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')))) else mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')) end,'|',';'),';;',';') NFNumSAIDANutriexNEW, o.transid TRANSACAO, FORMAT(n.TAXDATE,'yyyy/MM') DTCTE, n.serial CTENum, FORMAT(o.docdate,'yyyy/MM') DTDOC, o.cardcode COD, O.CARDNAME FORNECEDOR, o.canceled [CANCELADA?], j.prjname PROJETO, p.itemcode ITEM, p.dscription DESCRICAO, cast(p.linetotal as float) VLRFATURA from SBOVidafarma..pch1 p inner join SBOVidafarma..opch o on o.docentry = p.docentry inner join SBOVidafarma..opdn n on n.docentry = p.baseentry left join SBOVidafarma..oprj j on j.PrjCode = o.project where p.dscription like '%frete%' and YEAR(N.TAXDATE) = 2020 AND o.canceled <> 'C' UNION ALL 
	select 'SBOVZ' BASE, o.docentry DOCNFETransp, p.baseentry DOCRECEBTransp, o.serial NFNumTRANSP, REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),';',' ') [NFNumSAIDANutriexOLD], replace(replace(case when left(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),1) = '|' then substring(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),2,len(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')))) else mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')) end,'|',';'),';;',';') NFNumSAIDANutriexNEW, o.transid TRANSACAO, FORMAT(n.TAXDATE,'yyyy/MM') DTCTE, n.serial CTENum, FORMAT(o.docdate,'yyyy/MM') DTDOC, o.cardcode COD, O.CARDNAME FORNECEDOR, o.canceled [CANCELADA?], j.prjname PROJETO, p.itemcode ITEM, p.dscription DESCRICAO, cast(p.linetotal as float) VLRFATURA from SBOVZ..pch1 p inner join SBOVZ..opch o on o.docentry = p.docentry inner join SBOVZ..opdn n on n.docentry = p.baseentry left join SBOVZ..oprj j on j.PrjCode = o.project where p.dscription like '%frete%' and YEAR(N.TAXDATE) = 2020 AND o.canceled <> 'C' UNION ALL 
	select 'SBOZ9' BASE, o.docentry DOCNFETransp, p.baseentry DOCRECEBTransp, o.serial NFNumTRANSP, REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),';',' ') [NFNumSAIDANutriexOLD], replace(replace(case when left(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),1) = '|' then substring(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')),2,len(mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')))) else mbs.dbo.getnumbers(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(UPPER(COALESCE(N.COMMENTS,'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),'NF',''),'-',' '),'.',''),'/',' '),',',' '),'  ',' '),' ','|'),' E ','|')) end,'|',';'),';;',';') NFNumSAIDANutriexNEW, o.transid TRANSACAO, FORMAT(n.TAXDATE,'yyyy/MM') DTCTE, n.serial CTENum, FORMAT(o.docdate,'yyyy/MM') DTDOC, o.cardcode COD, O.CARDNAME FORNECEDOR, o.canceled [CANCELADA?], j.prjname PROJETO, p.itemcode ITEM, p.dscription DESCRICAO, cast(p.linetotal as float) VLRFATURA from SBOZ9..pch1 p inner join SBOZ9..opch o on o.docentry = p.docentry inner join SBOZ9..opdn n on n.docentry = p.baseentry left join SBOZ9..oprj j on j.PrjCode = o.project where p.dscription like '%frete%' and YEAR(N.TAXDATE) = 2020 AND o.canceled <> 'C'

INSERT INTO mbs..yyy
	SELECT [BASE]
		  ,[DOCNFETransp]
		  ,[DOCRECEBTransp]
		  ,[NFNumTRANSP]
		  ,[TRANSACAO]
		  ,[DTCTE]
		  ,[CTENum]
		  ,[DTDOC]
		  ,[COD]
		  ,[FORNECEDOR]
		  ,[CANCELADA?]
		  ,COALESCE([PROJETO],'') PROJETO
		  ,[ITEM]
		  ,REPLACE(REPLACE(REPLACE(UPPER(COALESCE([DESCRICAO],'')),CHAR(13),' '),CHAR(10),' '),CHAR(9),' ') [DESCRICAO]
		  ,[VLRFATURA]
		  ,[NFNumSAIDANutriexOLD]
		  ,case
			when (case
				when CHARINDEX(';',right((case when CHARINDEX(';',[NFNumSAIDANutriexNEW]) <= 3 then substring([NFNumSAIDANutriexNEW],CHARINDEX(';',[NFNumSAIDANutriexNEW])+1,len([NFNumSAIDANutriexNEW])) else [NFNumSAIDANutriexNEW] end),2)) = 1 
				then substring(case when CHARINDEX(';',[NFNumSAIDANutriexNEW]) <= 3 then substring([NFNumSAIDANutriexNEW],CHARINDEX(';',[NFNumSAIDANutriexNEW])+1,len([NFNumSAIDANutriexNEW])) else [NFNumSAIDANutriexNEW] end,1,len(case when CHARINDEX(';',[NFNumSAIDANutriexNEW]) <= 3 then substring([NFNumSAIDANutriexNEW],CHARINDEX(';',[NFNumSAIDANutriexNEW])+1,len([NFNumSAIDANutriexNEW])) else [NFNumSAIDANutriexNEW] end)-2) else [NFNumSAIDANutriexNEW] end) = '' then mbs.dbo.getnumbers([NFNumSAIDANutriexOLD]) 
				else 
					(case
					when CHARINDEX(';',right((case when CHARINDEX(';',[NFNumSAIDANutriexNEW]) <= 3 then substring([NFNumSAIDANutriexNEW],CHARINDEX(';',[NFNumSAIDANutriexNEW])+1,len([NFNumSAIDANutriexNEW])) else [NFNumSAIDANutriexNEW] end),2)) = 1 
					then substring(case when CHARINDEX(';',[NFNumSAIDANutriexNEW]) <= 3 then substring([NFNumSAIDANutriexNEW],CHARINDEX(';',[NFNumSAIDANutriexNEW])+1,len([NFNumSAIDANutriexNEW])) else [NFNumSAIDANutriexNEW] end,1,len(case when CHARINDEX(';',[NFNumSAIDANutriexNEW]) <= 3 then substring([NFNumSAIDANutriexNEW],CHARINDEX(';',[NFNumSAIDANutriexNEW])+1,len([NFNumSAIDANutriexNEW])) else [NFNumSAIDANutriexNEW] end)-2) else [NFNumSAIDANutriexNEW] end) end [NFNumSAIDANutriexNEW]
	  FROM [Mbs].[dbo].[xxx] 


SELECT [BASE]
      ,[DOCNFETransp]
      ,[DOCRECEBTransp]
      ,[NFNumTRANSP]
      ,[TRANSACAO]
      ,[DTCTE]
      ,[CTENum]
      ,[DTDOC]
      ,[COD]
      ,[FORNECEDOR]
      ,[CANCELADA?]
      ,[PROJETO]
      ,[ITEM]
      ,[DESCRICAO]
      ,[VLRFATURA]
      ,[NFNumSAIDANutriexOLD]
	  ,CASE WHEN (CHARINDEX(';',RIGHT([NFNumSAIDANutriexNEW],1)) = 1) THEN SUBSTRING([NFNumSAIDANutriexNEW],1,LEN([NFNumSAIDANutriexNEW])-1) ELSE [NFNumSAIDANutriexNEW] END [NFNumSAIDANutriexNEW]
  FROM [Mbs].[dbo].[yyy] 