DECLARE @dataref VARCHAR(MAX) = '202007'; 
DECLARE @texto NVARCHAR(MAX);

DELETE FROM MBS..FOLHAONLINE

--==== GERA O FOLHA ONLINE PARA O TIPO DECIMO TERCEIRO (REALIZADA AO FINAL DE CADA ANO APENAS) =====================

INSERT INTO MBS..FOLHAONLINE
	SELECT
	 E.[EMNOMEMP] AS EMPRESA
	,L.[LODESCLOT] AS FILIAL
	,CONCAT(FORMAT(F.FUMATFUNC,'000'),' - ',F.FUNOMFUNC COLLATE DATABASE_DEFAULT) AS NOME 
	,C.CCDESCRIC AS CENTRO_CUSTO
	,A.[AFVALOR] AS PROJETO
	,S.[STDESCSITU] AS SITUACAO		--, F.FUCODCAGED AS CAGED, F.FUDTSUCECESS AS DTSUCESSAO --ESSE FILTRO DEMONSTRA OS FUNCIONARIOS QUE ENTRARAM TRANSFERIDOS DE OUTRA EMPRESA
	,V.VADTREFER AS DATAREF
	--,FORMAT(V.VACODEVENT,'00000') AS EVENTO_COD
	,CONCAT(FORMAT(V.VACODEVENT,'00000'),' - ',T.[EVDESCOMPL] COLLATE DATABASE_DEFAULT) AS EVENTO_NOM
	,CASE
		WHEN T.EVINDEVENT = 'D' THEN CAST(-V.VAVALEVENT AS FLOAT)
		WHEN T.EVINDEVENT = 'P' THEN CAST(V.VAVALEVENT AS FLOAT)
		ELSE CAST(V.VAVALEVENT AS FLOAT) 
	 END AS VALOR
	,CASE
		WHEN T.EVINDEVENT = 'D' THEN 'DESCONTO'
		WHEN T.EVINDEVENT = 'P' THEN 'PROVENTO'
		WHEN T.EVINDEVENT = 'R' THEN 'RESULTADO'
		ELSE T.EVINDEVENT 
	 END AS TIPO_FOLHA
	 ,F.FUMATFUNC AS MATFUNC
	 ,E.[EMCODEMP] AS EMPCODE
	 ,F.FUTIPOADMS AS TIPOADM
	 ,W.TIPO_SAP AS TIPO_SAP
	 ,CASE
			WHEN (E.[EMNOMEMP] = 'NUTRIEX IMPORTAÇAO E EXPORTAÇAO DE PROD NUTRICIONAIS E FARMOQUIMICOS LTDA' OR E.[EMNOMEMP] = 'ACAO OPERADORA FACTOR LTDA - ME') THEN W.CONTA_NPH
			WHEN H.TABELA = 'IND_DIR' THEN W.CONTA_IND_DIR
			WHEN H.TABELA = 'IND_IND' THEN W.CONTA_IND_IND
			ELSE W.CONTA_GERAL
	  END AS CONTA_CONTABIL
	 ,'DECIMO' AS FOLHA_TIPO
	 ,COALESCE(H.TABELA,'GERAL') AS TABELA, 'BASE' AS BASE, 0 AS ID, 1 AS BPLID, 'FILIAL' AS BPLNAME, '00000000000000' AS BPLCNPJ, 0 AS JDT1_NUMBER
	FROM [FPW5].[DBO].[VALANO] V
		INNER JOIN [FPW5].[DBO].[FUNCIONA] F ON V.VACODEMP = F.FUCODEMP AND V.VAMATFUNC = F.FUMATFUNC
		INNER JOIN [FPW5].[dbo].[EMPRESAS] E ON E.[EMCODEMP] = F.FUCODEMP
		INNER JOIN [FPW5].[dbo].[EVENTOS] T ON T.[EVCODEVENT] = V.VACODEVENT
		INNER JOIN [FPW5].[dbo].[SITUACAO] S ON S.[STCODSITU] = F.FUCODSITU
		INNER JOIN [FPW5].[dbo].[LOTACOES] L ON L.[LOCODEMP] = E.[EMCODEMP] AND L.[LOCODLOT] = F.FUCODLOT
		LEFT JOIN [FPW5].[dbo].[CENCUSTO] C ON C.[CCCODIGO] = F.[FUCENTRCUS] AND C.[CCCODEMP] = F.[FUCODEMP]
		LEFT JOIN [FPW5].[dbo].[ATRIBFUN] A ON A.AFCODEMP = E.EMCODEMP AND A.AFMATFUNC = F.FUMATFUNC AND A.AFCODATRIB = 1
		LEFT JOIN MBS.[dbo].FOLHA_TABELA H ON H.EMPRESA = E.[EMNOMEMP] AND H.CENTROCUSTO = C.CCDESCRIC
		LEFT JOIN MBS.[dbo].FOLHA_CONTA_CONTABIL W ON W.CODIGO_FOLHA = V.VACODEVENT
	WHERE V.VADTREFER LIKE @dataref AND VACODFOLHA = 4 AND V.VACODEMP <> 1 AND V.VACODEMP <> 13 AND T.EVINDEVENT <> 'R' AND  NOT (F.FUCODCAGED = 70 AND LEFT(F.FUDTSUCECESS,6) = CONCAT(LEFT(V.VADTREFER,4),FORMAT(RIGHT(V.VADTREFER,2)+1,'00')))



--==== GERA O FOLHA ONLINE PARA O TIPO MENSAL =====================

INSERT INTO MBS..FOLHAONLINE
	SELECT
	 E.[EMNOMEMP] AS EMPRESA
	,L.[LODESCLOT] AS FILIAL
	,CONCAT(FORMAT(F.FUMATFUNC,'000'),' - ',F.FUNOMFUNC COLLATE DATABASE_DEFAULT) AS NOME 
	,C.CCDESCRIC AS CENTRO_CUSTO
	,A.[AFVALOR] AS PROJETO
	,S.[STDESCSITU] AS SITUACAO		--, F.FUCODCAGED AS CAGED, F.FUDTSUCECESS AS DTSUCESSAO --ESSE FILTRO DEMONSTRA OS FUNCIONARIOS QUE ENTRARAM TRANSFERIDOS DE OUTRA EMPRESA
	,V.VADTREFER AS DATAREF
	--,FORMAT(V.VACODEVENT,'00000') AS EVENTO_COD
	,CONCAT(FORMAT(V.VACODEVENT,'00000'),' - ',T.[EVDESCOMPL] COLLATE DATABASE_DEFAULT) AS EVENTO_NOM
	,CASE
		WHEN T.EVINDEVENT = 'D' THEN CAST(-V.VAVALEVENT AS FLOAT)
		WHEN T.EVINDEVENT = 'P' THEN CAST(V.VAVALEVENT AS FLOAT)
		ELSE CAST(V.VAVALEVENT AS FLOAT) 
	 END AS VALOR
	,CASE
		WHEN T.EVINDEVENT = 'D' THEN 'DESCONTO'
		WHEN T.EVINDEVENT = 'P' THEN 'PROVENTO'
		WHEN T.EVINDEVENT = 'R' THEN 'RESULTADO'
		ELSE T.EVINDEVENT 
	 END AS TIPO_FOLHA
	 ,F.FUMATFUNC AS MATFUNC
	 ,E.[EMCODEMP] AS EMPCODE
	 ,F.FUTIPOADMS AS TIPOADM
	 ,W.TIPO_SAP AS TIPO_SAP
	 ,CASE
			WHEN (E.[EMNOMEMP] = 'NUTRIEX IMPORTAÇAO E EXPORTAÇAO DE PROD NUTRICIONAIS E FARMOQUIMICOS LTDA' OR E.[EMNOMEMP] = 'ACAO OPERADORA FACTOR LTDA - ME') THEN W.CONTA_NPH
			WHEN H.TABELA = 'IND_DIR' THEN W.CONTA_IND_DIR
			WHEN H.TABELA = 'IND_IND' THEN W.CONTA_IND_IND
			ELSE W.CONTA_GERAL
	  END AS CONTA_CONTABIL
	 ,'MENSAL' AS FOLHA_TIPO
	 ,COALESCE(H.TABELA,'GERAL') AS TABELA, 'BASE' AS BASE, 0 AS ID, 1 AS BPLID, 'FILIAL' AS BPLNAME, '00000000000000' AS BPLCNPJ, 0 AS JDT1_NUMBER
	FROM [FPW5].[DBO].[VALANO] V
		INNER JOIN [FPW5].[DBO].[FUNCIONA] F ON V.VACODEMP = F.FUCODEMP AND V.VAMATFUNC = F.FUMATFUNC
		INNER JOIN [FPW5].[dbo].[EMPRESAS] E ON E.[EMCODEMP] = F.FUCODEMP
		INNER JOIN [FPW5].[dbo].[EVENTOS] T ON T.[EVCODEVENT] = V.VACODEVENT
		INNER JOIN [FPW5].[dbo].[SITUACAO] S ON S.[STCODSITU] = F.FUCODSITU
		INNER JOIN [FPW5].[dbo].[LOTACOES] L ON L.[LOCODEMP] = E.[EMCODEMP] AND L.[LOCODLOT] = F.FUCODLOT
		LEFT JOIN [FPW5].[dbo].[CENCUSTO] C ON C.[CCCODIGO] = F.[FUCENTRCUS] AND C.[CCCODEMP] = F.[FUCODEMP]
		LEFT JOIN [FPW5].[dbo].[ATRIBFUN] A ON A.AFCODEMP = E.EMCODEMP AND A.AFMATFUNC = F.FUMATFUNC AND A.AFCODATRIB = 1
		LEFT JOIN MBS.[dbo].FOLHA_TABELA H ON H.EMPRESA = E.[EMNOMEMP] AND H.CENTROCUSTO = C.CCDESCRIC
		LEFT JOIN MBS.[dbo].FOLHA_CONTA_CONTABIL W ON W.CODIGO_FOLHA = V.VACODEVENT
	WHERE V.VADTREFER LIKE @dataref AND VACODFOLHA = 1 AND V.VACODEMP <> 1 AND V.VACODEMP <> 13 AND T.EVINDEVENT <> 'R' AND  NOT (F.FUCODCAGED = 70 AND LEFT(F.FUDTSUCECESS,6) = CONCAT(LEFT(V.VADTREFER,4),FORMAT(RIGHT(V.VADTREFER,2)+1,'00')))

--============== GERA A FOLHA TOTALIZADORA PARA ENGLOBAR OS CALCULOS DAS DIFERENCAS SINDICAIS COM AUMENTOS ANTERIORES DEVIDOS ===============
INSERT INTO MBS..FOLHAONLINE
SELECT
	 E.[EMNOMEMP] AS EMPRESA
	,L.[LODESCLOT] AS FILIAL
	,CONCAT(FORMAT(F.FUMATFUNC,'000'),' - ',F.FUNOMFUNC COLLATE DATABASE_DEFAULT) AS NOME 
	,C.CCDESCRIC AS CENTRO_CUSTO
	,A.[AFVALOR] AS PROJETO
	,S.[STDESCSITU] AS SITUACAO		--, F.FUCODCAGED AS CAGED, F.FUDTSUCECESS AS DTSUCESSAO --ESSE FILTRO DEMONSTRA OS FUNCIONARIOS QUE ENTRARAM TRANSFERIDOS DE OUTRA EMPRESA
	,V.VADTREFER AS DATAREF
	--,FORMAT(V.VACODEVENT,'00000') AS EVENTO_COD
	,CONCAT(FORMAT(V.VACODEVENT,'00000'),' - ',T.[EVDESCOMPL] COLLATE DATABASE_DEFAULT) AS EVENTO_NOM
	,CASE
		WHEN T.EVINDEVENT = 'D' THEN CAST(-V.VAVALEVENT AS FLOAT)
		WHEN T.EVINDEVENT = 'P' THEN CAST(V.VAVALEVENT AS FLOAT)
		ELSE CAST(V.VAVALEVENT AS FLOAT) 
	 END AS VALOR
	,CASE
		WHEN T.EVINDEVENT = 'D' THEN 'DESCONTO'
		WHEN T.EVINDEVENT = 'P' THEN 'PROVENTO'
		WHEN T.EVINDEVENT = 'R' THEN 'RESULTADO'
		ELSE T.EVINDEVENT 
	 END AS TIPO_FOLHA
	 ,F.FUMATFUNC AS MATFUNC
	 ,E.[EMCODEMP] AS EMPCODE
	 ,F.FUTIPOADMS AS TIPOADM
	 ,W.TIPO_SAP AS TIPO_SAP
	 ,CASE
			WHEN (E.[EMNOMEMP] = 'NUTRIEX IMPORTAÇAO E EXPORTAÇAO DE PROD NUTRICIONAIS E FARMOQUIMICOS LTDA' OR E.[EMNOMEMP] = 'ACAO OPERADORA FACTOR LTDA - ME') THEN W.CONTA_NPH
			WHEN H.TABELA = 'IND_DIR' THEN W.CONTA_IND_DIR
			WHEN H.TABELA = 'IND_IND' THEN W.CONTA_IND_IND
			ELSE W.CONTA_GERAL
	  END AS CONTA_CONTABIL
	 ,'TOTALM' AS FOLHA_TIPO
	 ,COALESCE(H.TABELA,'GERAL') AS TABELA, 'BASE' AS BASE, 0 AS ID, 1 AS BPLID, 'FILIAL' AS BPLNAME, '00000000000000' AS BPLCNPJ, 0 AS JDT1_NUMBER
	FROM [FPW5].[DBO].[VALANO] V
		INNER JOIN [FPW5].[DBO].[FUNCIONA] F ON V.VACODEMP = F.FUCODEMP AND V.VAMATFUNC = F.FUMATFUNC
		INNER JOIN [FPW5].[dbo].[EMPRESAS] E ON E.[EMCODEMP] = F.FUCODEMP
		INNER JOIN [FPW5].[dbo].[EVENTOS] T ON T.[EVCODEVENT] = V.VACODEVENT
		INNER JOIN [FPW5].[dbo].[SITUACAO] S ON S.[STCODSITU] = F.FUCODSITU
		INNER JOIN [FPW5].[dbo].[LOTACOES] L ON L.[LOCODEMP] = E.[EMCODEMP] AND L.[LOCODLOT] = F.FUCODLOT
		LEFT JOIN [FPW5].[dbo].[CENCUSTO] C ON C.[CCCODIGO] = F.[FUCENTRCUS] AND C.[CCCODEMP] = F.[FUCODEMP]
		LEFT JOIN [FPW5].[dbo].[ATRIBFUN] A ON A.AFCODEMP = E.EMCODEMP AND A.AFMATFUNC = F.FUMATFUNC AND A.AFCODATRIB = 1
		LEFT JOIN MBS.[dbo].FOLHA_TABELA H ON H.EMPRESA = E.[EMNOMEMP] AND H.CENTROCUSTO = C.CCDESCRIC
		LEFT JOIN MBS.[dbo].FOLHA_CONTA_CONTABIL W ON W.CODIGO_FOLHA = V.VACODEVENT
	WHERE V.VADTREFER LIKE @dataref AND VACODFOLHA = 120 AND V.VACODEMP <> 1 AND V.VACODEMP <> 13 AND T.EVINDEVENT <> 'R' AND  NOT (F.FUCODCAGED = 70 AND LEFT(F.FUDTSUCECESS,6) = CONCAT(LEFT(V.VADTREFER,4),FORMAT(RIGHT(V.VADTREFER,2)+1,'00')))

--=============  ATUALIZA LOTACOES TROCADAS QDO OPERACAO DE MUDANCA DE MATRIZ PARA FILIAL E VICE-VERSA SE DER LOGO APOS O ENCERRAMENTO DA FOLHA =============

--UPDATE [Mbs].[dbo].[FOLHAONLINE]
--	SET FILIAL = (SELECT L.LODESCLOT FROM [FPW5].[dbo].[LOTACOES] L WHERE L.[LOCODEMP] = (SELECT TOP 1 O.[OFCODEMP] FROM [Mbs].[dbo].[FOLHAONLINE] F INNER JOIN [FPW5].[dbo].[OCORFUNC] O ON F.TIPOADM = 4 AND O.[OFMATFUNC] = F.MATFUNC AND LEFT(O.[OFDTINIOCO],4)=LEFT(F.DATAREF,4) AND O.[OFCODOCORR] = 1003 AND O.[OFCODEMP] = F.EMPCODE) AND L.[LOCODLOT] = (SELECT TOP 1 O.[OFCODLTANT] FROM [Mbs].[dbo].[FOLHAONLINE] F INNER JOIN [FPW5].[dbo].[OCORFUNC] O ON F.TIPOADM = 4 AND O.[OFMATFUNC] = F.MATFUNC AND LEFT(O.[OFDTINIOCO],4)=LEFT(F.DATAREF,4) AND O.[OFCODOCORR] = 1003 AND O.[OFCODEMP] = F.EMPCODE))
--	WHERE 
--		TIPOADM = 4 AND 
--		MATFUNC = (SELECT TOP 1 O.[OFMATFUNC] FROM [Mbs].[dbo].[FOLHAONLINE] F INNER JOIN [FPW5].[dbo].[OCORFUNC] O ON F.TIPOADM = 4 AND O.[OFMATFUNC] = F.MATFUNC AND LEFT(O.[OFDTINIOCO],4)=LEFT(F.DATAREF,4) AND O.[OFCODOCORR] = 1003 AND O.[OFCODEMP] = F.EMPCODE) AND
--		EMPCODE = (SELECT TOP 1 O.OFCODEMP FROM [Mbs].[dbo].[FOLHAONLINE] F INNER JOIN [FPW5].[dbo].[OCORFUNC] O ON F.TIPOADM = 4 AND O.[OFMATFUNC] = F.MATFUNC AND LEFT(O.[OFDTINIOCO],4)=LEFT(F.DATAREF,4) AND O.[OFCODOCORR] = 1003 AND O.[OFCODEMP] = F.EMPCODE)

--=============  GERA A FOLHA ONLINE PARA O TIPO PROLABORE =============

INSERT INTO MBS..FOLHAONLINE
	SELECT 
	 E.[EMNOMEMP] AS EMPRESA
	,L.[LODESCLOT] AS FILIAL
	,CONCAT(FORMAT(F.FUMATFUNC,'000'),' - ',F.FUNOMFUNC COLLATE DATABASE_DEFAULT) AS NOME 
	,C.CCDESCRIC AS CENTRO_CUSTO
	,A.[AFVALOR] AS PROJETO
	,S.[STDESCSITU] AS SITUACAO		--, F.FUCODCAGED AS CAGED, F.FUDTSUCECESS AS DTSUCESSAO --ESSE FILTRO DEMONSTRA OS FUNCIONARIOS QUE ENTRARAM TRANSFERIDOS DE OUTRA EMPRESA
	,V.VADTREFER AS DATAREF
	--,FORMAT(V.VACODEVENT,'00000') AS EVENTO_COD
	,CONCAT(FORMAT(V.VACODEVENT,'00000'),' - ',T.[EVDESCOMPL] COLLATE DATABASE_DEFAULT) AS EVENTO_NOM
	,CASE
		WHEN T.EVINDEVENT = 'D' THEN CAST(-V.VAVALEVENT AS FLOAT)
		WHEN T.EVINDEVENT = 'P' THEN CAST(V.VAVALEVENT AS FLOAT)
		ELSE CAST(V.VAVALEVENT AS FLOAT) 
	 END AS VALOR
	,CASE
		WHEN T.EVINDEVENT = 'D' THEN 'DESCONTO'
		WHEN T.EVINDEVENT = 'P' THEN 'PROVENTO'
		WHEN T.EVINDEVENT = 'R' THEN 'RESULTADO'
		ELSE T.EVINDEVENT 
	 END AS TIPO_FOLHA
	 ,F.FUMATFUNC AS MATFUNC
	 ,E.[EMCODEMP] AS EMPCODE
	 ,F.FUTIPOADMS AS TIPOADM
	 ,W.TIPO_SAP AS TIPO_SAP
	 ,CASE
			WHEN (E.[EMNOMEMP] = 'NUTRIEX IMPORTAÇAO E EXPORTAÇAO DE PROD NUTRICIONAIS E FARMOQUIMICOS LTDA' OR E.[EMNOMEMP] = 'ACAO OPERADORA FACTOR LTDA - ME') THEN W.CONTA_NPH
			WHEN H.TABELA = 'IND_DIR' THEN W.CONTA_IND_DIR
			WHEN H.TABELA = 'IND_IND' THEN W.CONTA_IND_IND
			ELSE W.CONTA_GERAL
	  END AS CONTA_CONTABIL
	 ,'PROLABORE' AS FOLHA_TIPO
	 ,COALESCE(H.TABELA,'GERAL') AS TABELA, 'BASE' AS BASE, 0 AS ID, 1 AS BPLID, 'FILIAL' AS BPLNAME, '00000000000000' AS BPLCNPJ, 0 AS JDT1_NUMBER
	FROM [FPW5].[DBO].[VALANO] V
		INNER JOIN [FPW5].[DBO].[FUNCIONA] F ON V.VACODEMP = F.FUCODEMP AND V.VAMATFUNC = F.FUMATFUNC
		INNER JOIN [FPW5].[dbo].[EMPRESAS] E ON E.[EMCODEMP] = F.FUCODEMP
		INNER JOIN [FPW5].[dbo].[EVENTOS] T ON T.[EVCODEVENT] = V.VACODEVENT
		INNER JOIN [FPW5].[dbo].[SITUACAO] S ON S.[STCODSITU] = F.FUCODSITU
		INNER JOIN [FPW5].[dbo].[LOTACOES] L ON L.[LOCODEMP] = E.[EMCODEMP] AND L.[LOCODLOT] = F.FUCODLOT
		LEFT JOIN [FPW5].[dbo].[CENCUSTO] C ON C.[CCCODIGO] = F.[FUCENTRCUS] AND C.[CCCODEMP] = F.[FUCODEMP]
		LEFT JOIN [FPW5].[dbo].[ATRIBFUN] A ON A.AFCODEMP = E.EMCODEMP AND A.AFMATFUNC = F.FUMATFUNC AND A.AFCODATRIB = 1
		LEFT JOIN MBS.[dbo].FOLHA_TABELA H ON H.EMPRESA = E.[EMNOMEMP] AND H.CENTROCUSTO = C.CCDESCRIC
		LEFT JOIN MBS.[dbo].FOLHA_CONTA_CONTABIL W ON W.CODIGO_FOLHA = V.VACODEVENT
	WHERE V.VADTREFER LIKE @dataref AND VACODFOLHA = 12 AND V.VACODEMP <> 1 AND V.VACODEMP <> 13  AND T.EVINDEVENT <> 'R' AND  NOT (F.FUCODCAGED = 70 AND LEFT(F.FUDTSUCECESS,6) = CONCAT(LEFT(V.VADTREFER,4),FORMAT(RIGHT(V.VADTREFER,2)+1,'00')))


--=============  GERA A FOLHA ONLINE PARA O TIPO RESCISAO  =============

INSERT INTO MBS..FOLHAONLINE
	SELECT 
	 E.[EMNOMEMP] AS EMPRESA
	,L.[LODESCLOT] AS FILIAL
	,CONCAT(FORMAT(F.FUMATFUNC,'000'),' - ',F.FUNOMFUNC COLLATE DATABASE_DEFAULT) AS NOME 
	,C.CCDESCRIC AS CENTRO_CUSTO
	,A.[AFVALOR] AS PROJETO
	,S.[STDESCSITU] AS SITUACAO		--, F.FUCODCAGED AS CAGED, F.FUDTSUCECESS AS DTSUCESSAO --ESSE FILTRO DEMONSTRA OS FUNCIONARIOS QUE ENTRARAM TRANSFERIDOS DE OUTRA EMPRESA
	,V.VADTREFER AS DATAREF
	--,FORMAT(V.VACODEVENT,'00000') AS EVENTO_COD
	,CONCAT(FORMAT(V.VACODEVENT,'00000'),' - ',T.[EVDESCOMPL] COLLATE DATABASE_DEFAULT) AS EVENTO_NOM
	,CASE
		WHEN T.EVINDEVENT = 'D' THEN CAST(-V.VAVALEVENT AS FLOAT)
		WHEN T.EVINDEVENT = 'P' THEN CAST(V.VAVALEVENT AS FLOAT)
		ELSE CAST(V.VAVALEVENT AS FLOAT) 
	 END AS VALOR
	,CASE
		WHEN T.EVINDEVENT = 'D' THEN 'DESCONTO'
		WHEN T.EVINDEVENT = 'P' THEN 'PROVENTO'
		WHEN T.EVINDEVENT = 'R' THEN 'RESULTADO'
		ELSE T.EVINDEVENT 
	 END AS TIPO_FOLHA
	 ,F.FUMATFUNC AS MATFUNC
	 ,E.[EMCODEMP] AS EMPCODE
	 ,F.FUTIPOADMS AS TIPOADM
	 ,W.TIPO_SAP AS TIPO_SAP
	 ,CASE
			WHEN (E.[EMNOMEMP] = 'NUTRIEX IMPORTAÇAO E EXPORTAÇAO DE PROD NUTRICIONAIS E FARMOQUIMICOS LTDA' OR E.[EMNOMEMP] = 'ACAO OPERADORA FACTOR LTDA - ME') THEN W.CONTA_NPH
			WHEN H.TABELA = 'IND_DIR' THEN W.CONTA_IND_DIR
			WHEN H.TABELA = 'IND_IND' THEN W.CONTA_IND_IND
			ELSE W.CONTA_GERAL
	  END AS CONTA_CONTABIL
	 ,'RESCISAO' AS FOLHA_TIPO
	 ,COALESCE(H.TABELA,'GERAL') AS TABELA, 'BASE' AS BASE, 0 AS ID, 1 AS BPLID, 'FILIAL' AS BPLNAME, '00000000000000' AS BPLCNPJ, 0 AS JDT1_NUMBER
	FROM [FPW5].[DBO].[VALANO] V
		INNER JOIN [FPW5].[DBO].[FUNCIONA] F ON V.VACODEMP = F.FUCODEMP AND V.VAMATFUNC = F.FUMATFUNC
		INNER JOIN [FPW5].[dbo].[EMPRESAS] E ON E.[EMCODEMP] = F.FUCODEMP
		INNER JOIN [FPW5].[dbo].[EVENTOS] T ON T.[EVCODEVENT] = V.VACODEVENT
		INNER JOIN [FPW5].[dbo].[SITUACAO] S ON S.[STCODSITU] = F.FUCODSITU
		INNER JOIN [FPW5].[dbo].[LOTACOES] L ON L.[LOCODEMP] = E.[EMCODEMP] AND L.[LOCODLOT] = F.FUCODLOT
		LEFT JOIN [FPW5].[dbo].[CENCUSTO] C ON C.[CCCODIGO] = F.[FUCENTRCUS] AND C.[CCCODEMP] = F.[FUCODEMP]
		LEFT JOIN [FPW5].[dbo].[ATRIBFUN] A ON A.AFCODEMP = E.EMCODEMP AND A.AFMATFUNC = F.FUMATFUNC AND A.AFCODATRIB = 1
		LEFT JOIN MBS.[dbo].FOLHA_TABELA H ON H.EMPRESA = E.[EMNOMEMP] AND H.CENTROCUSTO = C.CCDESCRIC
		LEFT JOIN MBS.[dbo].FOLHA_CONTA_CONTABIL W ON W.CODIGO_FOLHA = V.VACODEVENT
	WHERE V.VADTREFER LIKE @dataref AND (VACODFOLHA = 5 OR VACODFOLHA = 7 OR VACODFOLHA = 8) AND V.VACODEMP <> 1 AND V.VACODEMP <> 13  AND T.EVINDEVENT <> 'R' AND  NOT (F.FUCODCAGED = 70 AND LEFT(F.FUDTSUCECESS,6) = CONCAT(LEFT(V.VADTREFER,4),FORMAT(RIGHT(V.VADTREFER,2)+1,'00')))


--=============  GERA A FOLHA ONLINE PARA O TIPO PROVISAO FERIAS  =============

INSERT INTO MBS..FOLHAONLINE
	SELECT 
	 E.[EMNOMEMP] AS EMPRESA
	,L.[LODESCLOT] AS FILIAL
	,CONCAT(FORMAT(F.FUMATFUNC,'000'),' - ',F.FUNOMFUNC COLLATE DATABASE_DEFAULT) AS NOME 
	,C.CCDESCRIC AS CENTRO_CUSTO
	,A.[AFVALOR] AS PROJETO
	,S.[STDESCSITU] AS SITUACAO		--, F.FUCODCAGED AS CAGED, F.FUDTSUCECESS AS DTSUCESSAO --ESSE FILTRO DEMONSTRA OS FUNCIONARIOS QUE ENTRARAM TRANSFERIDOS DE OUTRA EMPRESA
	,V.VADTREFER AS DATAREF
	--,FORMAT(V.VACODEVENT,'00000') AS EVENTO_COD
	,CONCAT(FORMAT(V.VACODEVENT,'00000'),' - ',T.[EVDESCOMPL] COLLATE DATABASE_DEFAULT) AS EVENTO_NOM
	,CASE
		WHEN T.EVINDEVENT = 'D' THEN CAST(-V.VAVALEVENT AS FLOAT)
		WHEN T.EVINDEVENT = 'P' THEN CAST(V.VAVALEVENT AS FLOAT)
		WHEN T.EVINDEVENT = 'R' THEN
			CASE
				WHEN V.VACODEVENT = 25730 THEN CAST(-V.VAVALEVENT AS FLOAT)	 --'PROV_FER_1/3_AJUSTE_NEG'
				WHEN V.VACODEVENT = 26250 THEN CAST(-V.VAVALEVENT AS FLOAT)	 --'PROV_FER_FGTS_AJUSTE_NEG'
				WHEN V.VACODEVENT = 25860 THEN CAST(-V.VAVALEVENT AS FLOAT)	 --'PROV_FER_INSS_AJUSTE_NEG'
				WHEN V.VACODEVENT = 25080 THEN CAST(-V.VAVALEVENT AS FLOAT)	 --'PROV_FER_AJUSTE_NEG'
				WHEN V.VACODEVENT = 25600 THEN CAST(-V.VAVALEVENT AS FLOAT)	 --'PROV_FER_FGTS_AJUSTE_NEG'
				WHEN V.VACODEVENT = 25210 THEN CAST(-V.VAVALEVENT AS FLOAT)	 --'PROV_FER_INSS_AJUSTE_NEG'
				WHEN V.VACODEVENT = 25725 THEN CAST(-V.VAVALEVENT AS FLOAT)	 --'PROV_FER_1/3_BAIXA'
				WHEN V.VACODEVENT = 26245 THEN CAST(-V.VAVALEVENT AS FLOAT)	 --'PROV_FER_FGTS_BAIXA'
				WHEN V.VACODEVENT = 25855 THEN CAST(-V.VAVALEVENT AS FLOAT)	 --'PROV_FER_INSS_BAIXA'
				WHEN V.VACODEVENT = 25075 THEN CAST(-V.VAVALEVENT AS FLOAT)	 --'PROV_FER_BAIXA'
				WHEN V.VACODEVENT = 25595 THEN CAST(-V.VAVALEVENT AS FLOAT)	 --'PROV_FER_FGTS_BAIXA'
				WHEN V.VACODEVENT = 25205 THEN CAST(-V.VAVALEVENT AS FLOAT)	 --'PROV_FER_INSS_BAIXA'
				ELSE CAST(V.VAVALEVENT AS FLOAT) 
			END
		ELSE CAST(V.VAVALEVENT AS FLOAT) 
	 END AS VALOR
	,CASE
		WHEN T.EVINDEVENT = 'D' THEN 'DESCONTO'
		WHEN T.EVINDEVENT = 'P' THEN 'PROVENTO'
		WHEN T.EVINDEVENT = 'R' THEN 'RESULTADO'
		ELSE T.EVINDEVENT 
	 END AS TIPO_FOLHA
	 ,F.FUMATFUNC AS MATFUNC
	 ,E.[EMCODEMP] AS EMPCODE
	 ,F.FUTIPOADMS AS TIPOADM
	 ,W.TIPO_SAP AS TIPO_SAP
	 ,CASE
			WHEN (E.[EMNOMEMP] = 'NUTRIEX IMPORTAÇAO E EXPORTAÇAO DE PROD NUTRICIONAIS E FARMOQUIMICOS LTDA' OR E.[EMNOMEMP] = 'ACAO OPERADORA FACTOR LTDA - ME') THEN W.CONTA_NPH
			WHEN H.TABELA = 'IND_DIR' THEN W.CONTA_IND_DIR
			WHEN H.TABELA = 'IND_IND' THEN W.CONTA_IND_IND
			ELSE W.CONTA_GERAL
	  END AS CONTA_CONTABIL
	 ,CASE
			WHEN V.VACODEVENT = 25650 THEN 'PROV_FER_1/3_ACUM_MES_ANT'
			WHEN V.VACODEVENT = 26170 THEN 'PROV_FER_FGTS_ACUM_MES_ANT'
			WHEN V.VACODEVENT = 25780 THEN 'PROV_FER_INSS_ACUM_MES_ANT'
			WHEN V.VACODEVENT = 25000 THEN 'PROV_FER_ACUM_MES_ANT'
			WHEN V.VACODEVENT = 25520 THEN 'PROV_FER_FGTS_ACUM_MES_ANT'
			WHEN V.VACODEVENT = 25130 THEN 'PROV_FER_INSS_ACUM_MES_ANT'
			WHEN V.VACODEVENT = 26190 THEN 'PROV_FER_FGTS_PROVISAO_DO_MES'
			WHEN V.VACODEVENT = 25800 THEN 'PROV_FER_INSS_PROVISAO_DO_MES'
			WHEN V.VACODEVENT = 25670 THEN 'PROV_FER_1/3_PROVISAO_DO_MES'
			WHEN V.VACODEVENT = 25540 THEN 'PROV_FER_FGTS_PROVISAO_DO_MES'
			WHEN V.VACODEVENT = 25150 THEN 'PROV_FER_INSS_PROVISAO_DO_MES'
			WHEN V.VACODEVENT = 25020 THEN 'PROV_FER_PROVISAO_DO_MES'
			WHEN V.VACODEVENT = 25685 THEN 'PROV_FER_1/3_AJUSTE_POS'
			WHEN V.VACODEVENT = 26205 THEN 'PROV_FER_FGTS_AJUSTE_POS'
			WHEN V.VACODEVENT = 25815 THEN 'PROV_FER_INSS_AJUSTE_POS'
			WHEN V.VACODEVENT = 25035 THEN 'PROV_FER_AJUSTE_POS'
			WHEN V.VACODEVENT = 25555 THEN 'PROV_FER_FGTS_AJUSTE_POS'
			WHEN V.VACODEVENT = 25165 THEN 'PROV_FER_INSS_AJUSTE_POS'
			WHEN V.VACODEVENT = 25730 THEN 'PROV_FER_1/3_AJUSTE_NEG'
			WHEN V.VACODEVENT = 26250 THEN 'PROV_FER_FGTS_AJUSTE_NEG'
			WHEN V.VACODEVENT = 25860 THEN 'PROV_FER_INSS_AJUSTE_NEG'
			WHEN V.VACODEVENT = 25080 THEN 'PROV_FER_AJUSTE_NEG'
			WHEN V.VACODEVENT = 25600 THEN 'PROV_FER_FGTS_AJUSTE_NEG'
			WHEN V.VACODEVENT = 25210 THEN 'PROV_FER_INSS_AJUSTE_NEG'
			WHEN V.VACODEVENT = 25725 THEN 'PROV_FER_1/3_BAIXA'
			WHEN V.VACODEVENT = 26245 THEN 'PROV_FER_FGTS_BAIXA'
			WHEN V.VACODEVENT = 25855 THEN 'PROV_FER_INSS_BAIXA'
			WHEN V.VACODEVENT = 25075 THEN 'PROV_FER_BAIXA'
			WHEN V.VACODEVENT = 25595 THEN 'PROV_FER_FGTS_BAIXA'
			WHEN V.VACODEVENT = 25205 THEN 'PROV_FER_INSS_BAIXA'
			WHEN V.VACODEVENT = 25750 THEN 'PROV_FER_1/3_ACUM'
			WHEN V.VACODEVENT = 26270 THEN 'PROV_FER_FGTS_ACUM'
			WHEN V.VACODEVENT = 25880 THEN 'PROV_FER_INSS_ACUM'
			WHEN V.VACODEVENT = 25100 THEN 'PROV_FER_ACUM'
			WHEN V.VACODEVENT = 25620 THEN 'PROV_FER_FGTS_ACUM'
			WHEN V.VACODEVENT = 25230 THEN 'PROV_FER_INSS_ACUM'
	ELSE FORMAT(V.VACODEVENT,'00000')
	END AS FOLHA_TIPO
	 ,COALESCE(H.TABELA,'GERAL') AS TABELA, 'BASE' AS BASE, 0 AS ID, 1 AS BPLID, 'FILIAL' AS BPLNAME, '00000000000000' AS BPLCNPJ, 0 AS JDT1_NUMBER
	FROM [FPW5].[DBO].[VALANO] V
		INNER JOIN [FPW5].[DBO].[FUNCIONA] F ON V.VACODEMP = F.FUCODEMP AND V.VAMATFUNC = F.FUMATFUNC
		INNER JOIN [FPW5].[dbo].[EMPRESAS] E ON E.[EMCODEMP] = F.FUCODEMP
		INNER JOIN [FPW5].[dbo].[EVENTOS] T ON T.[EVCODEVENT] = V.VACODEVENT
		INNER JOIN [FPW5].[dbo].[SITUACAO] S ON S.[STCODSITU] = F.FUCODSITU
		INNER JOIN [FPW5].[dbo].[LOTACOES] L ON L.[LOCODEMP] = E.[EMCODEMP] AND L.[LOCODLOT] = F.FUCODLOT
		LEFT JOIN [FPW5].[dbo].[CENCUSTO] C ON C.[CCCODIGO] = F.[FUCENTRCUS] AND C.[CCCODEMP] = F.[FUCODEMP]
		LEFT JOIN [FPW5].[dbo].[ATRIBFUN] A ON A.AFCODEMP = E.EMCODEMP AND A.AFMATFUNC = F.FUMATFUNC AND A.AFCODATRIB = 1
		LEFT JOIN MBS.[dbo].FOLHA_TABELA H ON H.EMPRESA = E.[EMNOMEMP] AND H.CENTROCUSTO = C.CCDESCRIC
		LEFT JOIN MBS.[dbo].FOLHA_CONTA_CONTABIL W ON W.CODIGO_FOLHA = V.VACODEVENT
	WHERE V.VADTREFER LIKE @dataref AND (VACODFOLHA = 16) AND V.VACODEMP <> 1 AND V.VACODEMP <> 13  AND  NOT (F.FUCODCAGED = 70 AND LEFT(F.FUDTSUCECESS,6) = CONCAT(LEFT(V.VADTREFER,4),FORMAT(RIGHT(V.VADTREFER,2)+1,'00')))
		 AND (CASE
					WHEN V.VACODEVENT = 25650 THEN 'PROV_FER_1/3_ACUM_MES_ANT'
					WHEN V.VACODEVENT = 26170 THEN 'PROV_FER_FGTS_ACUM_MES_ANT'
					WHEN V.VACODEVENT = 25780 THEN 'PROV_FER_INSS_ACUM_MES_ANT'
					WHEN V.VACODEVENT = 25000 THEN 'PROV_FER_ACUM_MES_ANT'
					WHEN V.VACODEVENT = 25520 THEN 'PROV_FER_FGTS_ACUM_MES_ANT'
					WHEN V.VACODEVENT = 25130 THEN 'PROV_FER_INSS_ACUM_MES_ANT'
					WHEN V.VACODEVENT = 26190 THEN 'PROV_FER_FGTS_PROVISAO_DO_MES'
					WHEN V.VACODEVENT = 25800 THEN 'PROV_FER_INSS_PROVISAO_DO_MES'
					WHEN V.VACODEVENT = 25670 THEN 'PROV_FER_1/3_PROVISAO_DO_MES'
					WHEN V.VACODEVENT = 25540 THEN 'PROV_FER_FGTS_PROVISAO_DO_MES'
					WHEN V.VACODEVENT = 25150 THEN 'PROV_FER_INSS_PROVISAO_DO_MES'
					WHEN V.VACODEVENT = 25020 THEN 'PROV_FER_PROVISAO_DO_MES'
					WHEN V.VACODEVENT = 25685 THEN 'PROV_FER_1/3_AJUSTE_POS'
					WHEN V.VACODEVENT = 26205 THEN 'PROV_FER_FGTS_AJUSTE_POS'
					WHEN V.VACODEVENT = 25815 THEN 'PROV_FER_INSS_AJUSTE_POS'
					WHEN V.VACODEVENT = 25035 THEN 'PROV_FER_AJUSTE_POS'
					WHEN V.VACODEVENT = 25555 THEN 'PROV_FER_FGTS_AJUSTE_POS'
					WHEN V.VACODEVENT = 25165 THEN 'PROV_FER_INSS_AJUSTE_POS'
					WHEN V.VACODEVENT = 25730 THEN 'PROV_FER_1/3_AJUSTE_NEG'
					WHEN V.VACODEVENT = 26250 THEN 'PROV_FER_FGTS_AJUSTE_NEG'
					WHEN V.VACODEVENT = 25860 THEN 'PROV_FER_INSS_AJUSTE_NEG'
					WHEN V.VACODEVENT = 25080 THEN 'PROV_FER_AJUSTE_NEG'
					WHEN V.VACODEVENT = 25600 THEN 'PROV_FER_FGTS_AJUSTE_NEG'
					WHEN V.VACODEVENT = 25210 THEN 'PROV_FER_INSS_AJUSTE_NEG'
					WHEN V.VACODEVENT = 25725 THEN 'PROV_FER_1/3_BAIXA'
					WHEN V.VACODEVENT = 26245 THEN 'PROV_FER_FGTS_BAIXA'
					WHEN V.VACODEVENT = 25855 THEN 'PROV_FER_INSS_BAIXA'
					WHEN V.VACODEVENT = 25075 THEN 'PROV_FER_BAIXA'
					WHEN V.VACODEVENT = 25595 THEN 'PROV_FER_FGTS_BAIXA'
					WHEN V.VACODEVENT = 25205 THEN 'PROV_FER_INSS_BAIXA'
					WHEN V.VACODEVENT = 25750 THEN 'PROV_FER_1/3_ACUM'
					WHEN V.VACODEVENT = 26270 THEN 'PROV_FER_FGTS_ACUM'
					WHEN V.VACODEVENT = 25880 THEN 'PROV_FER_INSS_ACUM'
					WHEN V.VACODEVENT = 25100 THEN 'PROV_FER_ACUM'
					WHEN V.VACODEVENT = 25620 THEN 'PROV_FER_FGTS_ACUM'
					WHEN V.VACODEVENT = 25230 THEN 'PROV_FER_INSS_ACUM'
				ELSE FORMAT(V.VACODEVENT,'00000')
				END) LIKE 'PROV%'



--=============  GERA A FOLHA ONLINE PARA O TIPO PROVISAO DECIMO TERCEIRO  =============


INSERT INTO MBS..FOLHAONLINE
	SELECT 
	 E.[EMNOMEMP] AS EMPRESA
	,L.[LODESCLOT] AS FILIAL
	,CONCAT(FORMAT(F.FUMATFUNC,'000'),' - ',F.FUNOMFUNC COLLATE DATABASE_DEFAULT) AS NOME 
	,C.CCDESCRIC AS CENTRO_CUSTO
	,A.[AFVALOR] AS PROJETO
	,S.[STDESCSITU] AS SITUACAO		--, F.FUCODCAGED AS CAGED, F.FUDTSUCECESS AS DTSUCESSAO --ESSE FILTRO DEMONSTRA OS FUNCIONARIOS QUE ENTRARAM TRANSFERIDOS DE OUTRA EMPRESA
	,V.VADTREFER AS DATAREF
	--,FORMAT(V.VACODEVENT,'00000') AS EVENTO_COD
	,CONCAT(FORMAT(V.VACODEVENT,'00000'),' - ',T.[EVDESCOMPL] COLLATE DATABASE_DEFAULT) AS EVENTO_NOM
	,CASE
		WHEN T.EVINDEVENT = 'D' THEN CAST(-V.VAVALEVENT AS FLOAT)
		WHEN T.EVINDEVENT = 'P' THEN CAST(V.VAVALEVENT AS FLOAT)
		WHEN T.EVINDEVENT = 'R' THEN
			CASE
				WHEN V.VACODEVENT = 26765 THEN CAST(-V.VAVALEVENT AS FLOAT)    --PROV_13_AJUSTE_NEGATIVO'
				WHEN V.VACODEVENT = 27205 THEN CAST(-V.VAVALEVENT AS FLOAT)    --PROV_13_FGTS_AJUSTE_NEGATIVO'
				WHEN V.VACODEVENT = 26875 THEN CAST(-V.VAVALEVENT AS FLOAT)    --PROV_13_INSS_AJUSTE_NEGATIVO'
				WHEN V.VACODEVENT = 26760 THEN CAST(-V.VAVALEVENT AS FLOAT)    --PROV_13_BAIXA'
				WHEN V.VACODEVENT = 27200 THEN CAST(-V.VAVALEVENT AS FLOAT)    --PROV_13_FGTS_BAIXA'
				WHEN V.VACODEVENT = 26870 THEN CAST(-V.VAVALEVENT AS FLOAT)    --PROV_13_INSS_BAIXA'
				ELSE CAST(V.VAVALEVENT AS FLOAT) 
			END
		ELSE CAST(V.VAVALEVENT AS FLOAT) 
	 END AS VALOR
	,CASE
		WHEN T.EVINDEVENT = 'D' THEN 'DESCONTO'
		WHEN T.EVINDEVENT = 'P' THEN 'PROVENTO'
		WHEN T.EVINDEVENT = 'R' THEN 'RESULTADO'
		ELSE T.EVINDEVENT 
	 END AS TIPO_FOLHA
	 ,F.FUMATFUNC AS MATFUNC
	 ,E.[EMCODEMP] AS EMPCODE
	 ,F.FUTIPOADMS AS TIPOADM
	 ,W.TIPO_SAP AS TIPO_SAP
	 ,CASE
			WHEN (E.[EMNOMEMP] = 'NUTRIEX IMPORTAÇAO E EXPORTAÇAO DE PROD NUTRICIONAIS E FARMOQUIMICOS LTDA' OR E.[EMNOMEMP] = 'ACAO OPERADORA FACTOR LTDA - ME') THEN W.CONTA_NPH
			WHEN H.TABELA = 'IND_DIR' THEN W.CONTA_IND_DIR
			WHEN H.TABELA = 'IND_IND' THEN W.CONTA_IND_IND
			ELSE W.CONTA_GERAL
	  END AS CONTA_CONTABIL
	 ,CASE
			WHEN V.VACODEVENT = 26700 THEN 'PROV_13_ACUMULADO_MES_ANTERIOR'
			WHEN V.VACODEVENT = 27140 THEN 'PROV_13_FGTS_ACUM_MES_ANTERIOR'
			WHEN V.VACODEVENT = 26810 THEN 'PROV_13_INSS_ACUM_MES_ANTERIOR'
			WHEN V.VACODEVENT = 26710 THEN 'PROV_13_PROVISAO_DO_MES'
			WHEN V.VACODEVENT = 27150 THEN 'PROV_13_FGTS_PROVISAO_DO_MES'
			WHEN V.VACODEVENT = 26820 THEN 'PROV_13_INSS_PROVISAO_DO_MES'
			WHEN V.VACODEVENT = 26720 THEN 'PROV_13_AJUSTE_POSITIVO'
			WHEN V.VACODEVENT = 27160 THEN 'PROV_13_FGTS_AJUSTE_POSITIVO'
			WHEN V.VACODEVENT = 26830 THEN 'PROV_13_INSS_AJUSTE_POSITIVO'
			WHEN V.VACODEVENT = 26765 THEN 'PROV_13_AJUSTE_NEGATIVO'
			WHEN V.VACODEVENT = 27205 THEN 'PROV_13_FGTS_AJUSTE_NEGATIVO'
			WHEN V.VACODEVENT = 26875 THEN 'PROV_13_INSS_AJUSTE_NEGATIVO'
			WHEN V.VACODEVENT = 26760 THEN 'PROV_13_BAIXA'
			WHEN V.VACODEVENT = 27200 THEN 'PROV_13_FGTS_BAIXA'
			WHEN V.VACODEVENT = 26870 THEN 'PROV_13_INSS_BAIXA'
			WHEN V.VACODEVENT = 26785 THEN 'PROV_13_ACUMULADO'
			WHEN V.VACODEVENT = 27225 THEN 'PROV_13_FGTS_ACUMULADO'
			WHEN V.VACODEVENT = 26895 THEN 'PROV_13_INSS_ACUMULADO'
			ELSE FORMAT(V.VACODEVENT,'00000')
	END AS FOLHA_TIPO
	 ,COALESCE(H.TABELA,'GERAL') AS TABELA, 'BASE' AS BASE, 0 AS ID, 1 AS BPLID, 'FILIAL' AS BPLNAME, '00000000000000' AS BPLCNPJ, 0 AS JDT1_NUMBER
	FROM [FPW5].[DBO].[VALANO] V
		INNER JOIN [FPW5].[DBO].[FUNCIONA] F ON V.VACODEMP = F.FUCODEMP AND V.VAMATFUNC = F.FUMATFUNC
		INNER JOIN [FPW5].[dbo].[EMPRESAS] E ON E.[EMCODEMP] = F.FUCODEMP
		INNER JOIN [FPW5].[dbo].[EVENTOS] T ON T.[EVCODEVENT] = V.VACODEVENT
		INNER JOIN [FPW5].[dbo].[SITUACAO] S ON S.[STCODSITU] = F.FUCODSITU
		INNER JOIN [FPW5].[dbo].[LOTACOES] L ON L.[LOCODEMP] = E.[EMCODEMP] AND L.[LOCODLOT] = F.FUCODLOT
		LEFT JOIN [FPW5].[dbo].[CENCUSTO] C ON C.[CCCODIGO] = F.[FUCENTRCUS] AND C.[CCCODEMP] = F.[FUCODEMP]
		LEFT JOIN [FPW5].[dbo].[ATRIBFUN] A ON A.AFCODEMP = E.EMCODEMP AND A.AFMATFUNC = F.FUMATFUNC AND A.AFCODATRIB = 1
		LEFT JOIN MBS.[dbo].FOLHA_TABELA H ON H.EMPRESA = E.[EMNOMEMP] AND H.CENTROCUSTO = C.CCDESCRIC
		LEFT JOIN MBS.[dbo].FOLHA_CONTA_CONTABIL W ON W.CODIGO_FOLHA = V.VACODEVENT
	WHERE V.VADTREFER LIKE @dataref AND (VACODFOLHA = 16) AND V.VACODEMP <> 1 AND V.VACODEMP <> 13  AND  NOT (F.FUCODCAGED = 70 AND LEFT(F.FUDTSUCECESS,6) = CONCAT(LEFT(V.VADTREFER,4),FORMAT(RIGHT(V.VADTREFER,2)+1,'00')))
		 AND (CASE
					WHEN V.VACODEVENT = 26700 THEN 'PROV_13_ACUMULADO_MES_ANTERIOR'
					WHEN V.VACODEVENT = 27140 THEN 'PROV_13_FGTS_ACUM_MES_ANTERIOR'
					WHEN V.VACODEVENT = 26810 THEN 'PROV_13_INSS_ACUM_MES_ANTERIOR'
					WHEN V.VACODEVENT = 26710 THEN 'PROV_13_PROVISAO_DO_MES'
					WHEN V.VACODEVENT = 27150 THEN 'PROV_13_FGTS_PROVISAO_DO_MES'
					WHEN V.VACODEVENT = 26820 THEN 'PROV_13_INSS_PROVISAO_DO_MES'
					WHEN V.VACODEVENT = 26720 THEN 'PROV_13_AJUSTE_POSITIVO'
					WHEN V.VACODEVENT = 27160 THEN 'PROV_13_FGTS_AJUSTE_POSITIVO'
					WHEN V.VACODEVENT = 26830 THEN 'PROV_13_INSS_AJUSTE_POSITIVO'
					WHEN V.VACODEVENT = 26765 THEN 'PROV_13_AJUSTE_NEGATIVO'
					WHEN V.VACODEVENT = 27205 THEN 'PROV_13_FGTS_AJUSTE_NEGATIVO'
					WHEN V.VACODEVENT = 26875 THEN 'PROV_13_INSS_AJUSTE_NEGATIVO'
					WHEN V.VACODEVENT = 26760 THEN 'PROV_13_BAIXA'
					WHEN V.VACODEVENT = 27200 THEN 'PROV_13_FGTS_BAIXA'
					WHEN V.VACODEVENT = 26870 THEN 'PROV_13_INSS_BAIXA'
					WHEN V.VACODEVENT = 26785 THEN 'PROV_13_ACUMULADO'
					WHEN V.VACODEVENT = 27225 THEN 'PROV_13_FGTS_ACUMULADO'
					WHEN V.VACODEVENT = 26895 THEN 'PROV_13_INSS_ACUMULADO'
					ELSE FORMAT(V.VACODEVENT,'00000')
				 END) LIKE 'PROV%'


--============================= FOLHA MENSAL PARA GERAR APENAS OS EVENTOS DE RESULTADO 10990 E ACRESCENTA-LOS A TABELA ================================

INSERT INTO MBS..FOLHAONLINE
	SELECT
	 E.[EMNOMEMP] AS EMPRESA
	,L.[LODESCLOT] AS FILIAL
	,CONCAT(FORMAT(F.FUMATFUNC,'000'),' - ',F.FUNOMFUNC COLLATE DATABASE_DEFAULT) AS NOME 
	,C.CCDESCRIC AS CENTRO_CUSTO
	,A.[AFVALOR] AS PROJETO
	,S.[STDESCSITU] AS SITUACAO		--, F.FUCODCAGED AS CAGED, F.FUDTSUCECESS AS DTSUCESSAO --ESSE FILTRO DEMONSTRA OS FUNCIONARIOS QUE ENTRARAM TRANSFERIDOS DE OUTRA EMPRESA
	,V.VADTREFER AS DATAREF
	--,FORMAT(V.VACODEVENT,'00000') AS EVENTO_COD
	,CONCAT(FORMAT(V.VACODEVENT,'00000'),' - ',T.[EVDESCOMPL] COLLATE DATABASE_DEFAULT) AS EVENTO_NOM
	,CASE
		WHEN T.EVINDEVENT = 'D' THEN CAST(-V.VAVALEVENT AS FLOAT)
		WHEN T.EVINDEVENT = 'P' THEN CAST(V.VAVALEVENT AS FLOAT)
		ELSE CAST(V.VAVALEVENT AS FLOAT) 
	 END AS VALOR
	,CASE
		WHEN T.EVINDEVENT = 'D' THEN 'DESCONTO'
		WHEN T.EVINDEVENT = 'P' THEN 'PROVENTO'
		WHEN T.EVINDEVENT = 'R' THEN 'RESULTADO'
		ELSE T.EVINDEVENT 
	 END AS TIPO_FOLHA
	 ,F.FUMATFUNC AS MATFUNC
	 ,E.[EMCODEMP] AS EMPCODE
	 ,F.FUTIPOADMS AS TIPOADM
	 ,W.TIPO_SAP AS TIPO_SAP
	 ,CASE
			WHEN (E.[EMNOMEMP] = 'NUTRIEX IMPORTAÇAO E EXPORTAÇAO DE PROD NUTRICIONAIS E FARMOQUIMICOS LTDA' OR E.[EMNOMEMP] = 'ACAO OPERADORA FACTOR LTDA - ME') THEN W.CONTA_NPH
			WHEN H.TABELA = 'IND_DIR' THEN W.CONTA_IND_DIR
			WHEN H.TABELA = 'IND_IND' THEN W.CONTA_IND_IND
			ELSE W.CONTA_GERAL
	  END AS CONTA_CONTABIL
	 ,'MENSAL' AS FOLHA_TIPO
	 ,COALESCE(H.TABELA,'GERAL') AS TABELA, 'BASE' AS BASE, 0 AS ID, 1 AS BPLID, 'FILIAL' AS BPLNAME, '00000000000000' AS BPLCNPJ, 0 AS JDT1_NUMBER
	FROM [FPW5].[DBO].[VALANO] V
		INNER JOIN [FPW5].[DBO].[FUNCIONA] F ON V.VACODEMP = F.FUCODEMP AND V.VAMATFUNC = F.FUMATFUNC
		INNER JOIN [FPW5].[dbo].[EMPRESAS] E ON E.[EMCODEMP] = F.FUCODEMP
		INNER JOIN [FPW5].[dbo].[EVENTOS] T ON T.[EVCODEVENT] = V.VACODEVENT
		INNER JOIN [FPW5].[dbo].[SITUACAO] S ON S.[STCODSITU] = F.FUCODSITU
		INNER JOIN [FPW5].[dbo].[LOTACOES] L ON L.[LOCODEMP] = E.[EMCODEMP] AND L.[LOCODLOT] = F.FUCODLOT
		LEFT JOIN [FPW5].[dbo].[CENCUSTO] C ON C.[CCCODIGO] = F.[FUCENTRCUS] AND C.[CCCODEMP] = F.[FUCODEMP]
		LEFT JOIN [FPW5].[dbo].[ATRIBFUN] A ON A.AFCODEMP = E.EMCODEMP AND A.AFMATFUNC = F.FUMATFUNC AND A.AFCODATRIB = 1
		LEFT JOIN MBS.[dbo].FOLHA_TABELA H ON H.EMPRESA = E.[EMNOMEMP] AND H.CENTROCUSTO = C.CCDESCRIC
		LEFT JOIN MBS.[dbo].FOLHA_CONTA_CONTABIL W ON W.CODIGO_FOLHA = V.VACODEVENT
	WHERE V.VADTREFER LIKE @dataref AND VACODFOLHA = 1 AND V.VACODEMP <> 1 AND V.VACODEMP <> 13 AND V.VACODEVENT = 10990 AND NOT (F.FUCODCAGED = 70 AND LEFT(F.FUDTSUCECESS,6) = CONCAT(LEFT(V.VADTREFER,4),FORMAT(RIGHT(V.VADTREFER,2)+1,'00')))



--============================= FOLHA TOTALIZADORA PARA GERAR APENAS OS EVENTOS DE RESULTADO 10990 E ACRESCENTA-LOS A TABELA - DIFERENCAS SINDICAIS ================================

INSERT INTO MBS..FOLHAONLINE
SELECT
	 E.[EMNOMEMP] AS EMPRESA
	,L.[LODESCLOT] AS FILIAL
	,CONCAT(FORMAT(F.FUMATFUNC,'000'),' - ',F.FUNOMFUNC COLLATE DATABASE_DEFAULT) AS NOME 
	,C.CCDESCRIC AS CENTRO_CUSTO
	,A.[AFVALOR] AS PROJETO
	,S.[STDESCSITU] AS SITUACAO		--, F.FUCODCAGED AS CAGED, F.FUDTSUCECESS AS DTSUCESSAO --ESSE FILTRO DEMONSTRA OS FUNCIONARIOS QUE ENTRARAM TRANSFERIDOS DE OUTRA EMPRESA
	,V.VADTREFER AS DATAREF
	--,FORMAT(V.VACODEVENT,'00000') AS EVENTO_COD
	,CONCAT(FORMAT(V.VACODEVENT,'00000'),' - ',T.[EVDESCOMPL] COLLATE DATABASE_DEFAULT) AS EVENTO_NOM
	,CASE
		WHEN T.EVINDEVENT = 'D' THEN CAST(-V.VAVALEVENT AS FLOAT)
		WHEN T.EVINDEVENT = 'P' THEN CAST(V.VAVALEVENT AS FLOAT)
		ELSE CAST(V.VAVALEVENT AS FLOAT) 
	 END AS VALOR
	,CASE
		WHEN T.EVINDEVENT = 'D' THEN 'DESCONTO'
		WHEN T.EVINDEVENT = 'P' THEN 'PROVENTO'
		WHEN T.EVINDEVENT = 'R' THEN 'RESULTADO'
		ELSE T.EVINDEVENT 
	 END AS TIPO_FOLHA
	 ,F.FUMATFUNC AS MATFUNC
	 ,E.[EMCODEMP] AS EMPCODE
	 ,F.FUTIPOADMS AS TIPOADM
	 ,W.TIPO_SAP AS TIPO_SAP
	 ,CASE
			WHEN (E.[EMNOMEMP] = 'NUTRIEX IMPORTAÇAO E EXPORTAÇAO DE PROD NUTRICIONAIS E FARMOQUIMICOS LTDA' OR E.[EMNOMEMP] = 'ACAO OPERADORA FACTOR LTDA - ME') THEN W.CONTA_NPH
			WHEN H.TABELA = 'IND_DIR' THEN W.CONTA_IND_DIR
			WHEN H.TABELA = 'IND_IND' THEN W.CONTA_IND_IND
			ELSE W.CONTA_GERAL
	  END AS CONTA_CONTABIL
	 ,'TOTALM' AS FOLHA_TIPO
	 ,COALESCE(H.TABELA,'GERAL') AS TABELA, 'BASE' AS BASE, 0 AS ID, 1 AS BPLID, 'FILIAL' AS BPLNAME, '00000000000000' AS BPLCNPJ, 0 AS JDT1_NUMBER
	FROM [FPW5].[DBO].[VALANO] V
		INNER JOIN [FPW5].[DBO].[FUNCIONA] F ON V.VACODEMP = F.FUCODEMP AND V.VAMATFUNC = F.FUMATFUNC
		INNER JOIN [FPW5].[dbo].[EMPRESAS] E ON E.[EMCODEMP] = F.FUCODEMP
		INNER JOIN [FPW5].[dbo].[EVENTOS] T ON T.[EVCODEVENT] = V.VACODEVENT
		INNER JOIN [FPW5].[dbo].[SITUACAO] S ON S.[STCODSITU] = F.FUCODSITU
		INNER JOIN [FPW5].[dbo].[LOTACOES] L ON L.[LOCODEMP] = E.[EMCODEMP] AND L.[LOCODLOT] = F.FUCODLOT
		LEFT JOIN [FPW5].[dbo].[CENCUSTO] C ON C.[CCCODIGO] = F.[FUCENTRCUS] AND C.[CCCODEMP] = F.[FUCODEMP]
		LEFT JOIN [FPW5].[dbo].[ATRIBFUN] A ON A.AFCODEMP = E.EMCODEMP AND A.AFMATFUNC = F.FUMATFUNC AND A.AFCODATRIB = 1
		LEFT JOIN MBS.[dbo].FOLHA_TABELA H ON H.EMPRESA = E.[EMNOMEMP] AND H.CENTROCUSTO = C.CCDESCRIC
		LEFT JOIN MBS.[dbo].FOLHA_CONTA_CONTABIL W ON W.CODIGO_FOLHA = V.VACODEVENT
	WHERE V.VADTREFER LIKE @dataref AND VACODFOLHA = 120 AND V.VACODEMP <> 1 AND V.VACODEMP <> 13 AND V.VACODEVENT = 10990 AND NOT (F.FUCODCAGED = 70 AND LEFT(F.FUDTSUCECESS,6) = CONCAT(LEFT(V.VADTREFER,4),FORMAT(RIGHT(V.VADTREFER,2)+1,'00')))

--=============  ATUALIZA LOTACOES TROCADAS QDO OPERACAO DE MUDANCA DE MATRIZ PARA FILIAL E VICE-VERSA SE DER LOGO APOS O ENCERRAMENTO DA FOLHA =============

--UPDATE [Mbs].[dbo].[FOLHAONLINE]
--	SET FILIAL = (SELECT L.LODESCLOT FROM [FPW5].[dbo].[LOTACOES] L WHERE L.[LOCODEMP] = (SELECT TOP 1 O.[OFCODEMP] FROM [Mbs].[dbo].[FOLHAONLINE] F INNER JOIN [FPW5].[dbo].[OCORFUNC] O ON F.TIPOADM = 4 AND O.[OFMATFUNC] = F.MATFUNC AND LEFT(O.[OFDTINIOCO],4)=LEFT(F.DATAREF,4) AND O.[OFCODOCORR] = 1003 AND O.[OFCODEMP] = F.EMPCODE) AND L.[LOCODLOT] = (SELECT TOP 1 O.[OFCODLTANT] FROM [Mbs].[dbo].[FOLHAONLINE] F INNER JOIN [FPW5].[dbo].[OCORFUNC] O ON F.TIPOADM = 4 AND O.[OFMATFUNC] = F.MATFUNC AND LEFT(O.[OFDTINIOCO],4)=LEFT(F.DATAREF,4) AND O.[OFCODOCORR] = 1003 AND O.[OFCODEMP] = F.EMPCODE))
--	WHERE 
--		TIPOADM = 4 AND 
--		MATFUNC = (SELECT TOP 1 O.[OFMATFUNC] FROM [Mbs].[dbo].[FOLHAONLINE] F INNER JOIN [FPW5].[dbo].[OCORFUNC] O ON F.TIPOADM = 4 AND O.[OFMATFUNC] = F.MATFUNC AND LEFT(O.[OFDTINIOCO],4)=LEFT(F.DATAREF,4) AND O.[OFCODOCORR] = 1003 AND O.[OFCODEMP] = F.EMPCODE) AND
--		EMPCODE = (SELECT TOP 1 O.OFCODEMP FROM [Mbs].[dbo].[FOLHAONLINE] F INNER JOIN [FPW5].[dbo].[OCORFUNC] O ON F.TIPOADM = 4 AND O.[OFMATFUNC] = F.MATFUNC AND LEFT(O.[OFDTINIOCO],4)=LEFT(F.DATAREF,4) AND O.[OFCODOCORR] = 1003 AND O.[OFCODEMP] = F.EMPCODE)


--============================= FOLHA PROLABORE PARA GERAR APENAS OS EVENTOS DE RESULTADO 10990 E ACRESCENTA-LOS A TABELA ================================

INSERT INTO MBS..FOLHAONLINE
	SELECT 
	 E.[EMNOMEMP] AS EMPRESA
	,L.[LODESCLOT] AS FILIAL
	,CONCAT(FORMAT(F.FUMATFUNC,'000'),' - ',F.FUNOMFUNC COLLATE DATABASE_DEFAULT) AS NOME 
	,C.CCDESCRIC AS CENTRO_CUSTO
	,A.[AFVALOR] AS PROJETO
	,S.[STDESCSITU] AS SITUACAO		--, F.FUCODCAGED AS CAGED, F.FUDTSUCECESS AS DTSUCESSAO --ESSE FILTRO DEMONSTRA OS FUNCIONARIOS QUE ENTRARAM TRANSFERIDOS DE OUTRA EMPRESA
	,V.VADTREFER AS DATAREF
	--,FORMAT(V.VACODEVENT,'00000') AS EVENTO_COD
	,CONCAT(FORMAT(V.VACODEVENT,'00000'),' - ',T.[EVDESCOMPL] COLLATE DATABASE_DEFAULT) AS EVENTO_NOM
	,CASE
		WHEN T.EVINDEVENT = 'D' THEN CAST(-V.VAVALEVENT AS FLOAT)
		WHEN T.EVINDEVENT = 'P' THEN CAST(V.VAVALEVENT AS FLOAT)
		ELSE CAST(V.VAVALEVENT AS FLOAT) 
	 END AS VALOR
	,CASE
		WHEN T.EVINDEVENT = 'D' THEN 'DESCONTO'
		WHEN T.EVINDEVENT = 'P' THEN 'PROVENTO'
		WHEN T.EVINDEVENT = 'R' THEN 'RESULTADO'
		ELSE T.EVINDEVENT 
	 END AS TIPO_FOLHA
	 ,F.FUMATFUNC AS MATFUNC
	 ,E.[EMCODEMP] AS EMPCODE
	 ,F.FUTIPOADMS AS TIPOADM
	 ,W.TIPO_SAP AS TIPO_SAP
	 ,CASE
			WHEN (E.[EMNOMEMP] = 'NUTRIEX IMPORTAÇAO E EXPORTAÇAO DE PROD NUTRICIONAIS E FARMOQUIMICOS LTDA' OR E.[EMNOMEMP] = 'ACAO OPERADORA FACTOR LTDA - ME') THEN W.CONTA_NPH
			WHEN H.TABELA = 'IND_DIR' THEN W.CONTA_IND_DIR
			WHEN H.TABELA = 'IND_IND' THEN W.CONTA_IND_IND
			ELSE W.CONTA_GERAL
	  END AS CONTA_CONTABIL
	 ,'PROLABORE' AS FOLHA_TIPO
	 ,COALESCE(H.TABELA,'GERAL') AS TABELA, 'BASE' AS BASE, 0 AS ID, 1 AS BPLID, 'FILIAL' AS BPLNAME, '00000000000000' AS BPLCNPJ, 0 AS JDT1_NUMBER
	FROM [FPW5].[DBO].[VALANO] V
		INNER JOIN [FPW5].[DBO].[FUNCIONA] F ON V.VACODEMP = F.FUCODEMP AND V.VAMATFUNC = F.FUMATFUNC
		INNER JOIN [FPW5].[dbo].[EMPRESAS] E ON E.[EMCODEMP] = F.FUCODEMP
		INNER JOIN [FPW5].[dbo].[EVENTOS] T ON T.[EVCODEVENT] = V.VACODEVENT
		INNER JOIN [FPW5].[dbo].[SITUACAO] S ON S.[STCODSITU] = F.FUCODSITU
		INNER JOIN [FPW5].[dbo].[LOTACOES] L ON L.[LOCODEMP] = E.[EMCODEMP] AND L.[LOCODLOT] = F.FUCODLOT
		LEFT JOIN [FPW5].[dbo].[CENCUSTO] C ON C.[CCCODIGO] = F.[FUCENTRCUS] AND C.[CCCODEMP] = F.[FUCODEMP]
		LEFT JOIN [FPW5].[dbo].[ATRIBFUN] A ON A.AFCODEMP = E.EMCODEMP AND A.AFMATFUNC = F.FUMATFUNC AND A.AFCODATRIB = 1
		LEFT JOIN MBS.[dbo].FOLHA_TABELA H ON H.EMPRESA = E.[EMNOMEMP] AND H.CENTROCUSTO = C.CCDESCRIC
		LEFT JOIN MBS.[dbo].FOLHA_CONTA_CONTABIL W ON W.CODIGO_FOLHA = V.VACODEVENT
	WHERE V.VADTREFER LIKE @dataref AND VACODFOLHA = 12 AND V.VACODEMP <> 1 AND V.VACODEMP <> 13  AND V.VACODEVENT = 10990  AND  NOT (F.FUCODCAGED = 70 AND LEFT(F.FUDTSUCECESS,6) = CONCAT(LEFT(V.VADTREFER,4),FORMAT(RIGHT(V.VADTREFER,2)+1,'00')))
				

--============================= FOLHA RESCISAO PARA GERAR APENAS OS EVENTOS DE RESULTADO 10990 E ACRESCENTA-LOS A TABELA ================================

INSERT INTO MBS..FOLHAONLINE
	SELECT 
	 E.[EMNOMEMP] AS EMPRESA
	,L.[LODESCLOT] AS FILIAL
	,CONCAT(FORMAT(F.FUMATFUNC,'000'),' - ',F.FUNOMFUNC COLLATE DATABASE_DEFAULT) AS NOME 
	,C.CCDESCRIC AS CENTRO_CUSTO
	,A.[AFVALOR] AS PROJETO
	,S.[STDESCSITU] AS SITUACAO		--, F.FUCODCAGED AS CAGED, F.FUDTSUCECESS AS DTSUCESSAO --ESSE FILTRO DEMONSTRA OS FUNCIONARIOS QUE ENTRARAM TRANSFERIDOS DE OUTRA EMPRESA
	,V.VADTREFER AS DATAREF
	--,FORMAT(V.VACODEVENT,'00000') AS EVENTO_COD
	,CONCAT(FORMAT(V.VACODEVENT,'00000'),' - ',T.[EVDESCOMPL] COLLATE DATABASE_DEFAULT) AS EVENTO_NOM
	,CASE
		WHEN T.EVINDEVENT = 'D' THEN CAST(-V.VAVALEVENT AS FLOAT)
		WHEN T.EVINDEVENT = 'P' THEN CAST(V.VAVALEVENT AS FLOAT)
		ELSE CAST(V.VAVALEVENT AS FLOAT) 
	 END AS VALOR
	,CASE
		WHEN T.EVINDEVENT = 'D' THEN 'DESCONTO'
		WHEN T.EVINDEVENT = 'P' THEN 'PROVENTO'
		WHEN T.EVINDEVENT = 'R' THEN 'RESULTADO'
		ELSE T.EVINDEVENT 
	 END AS TIPO_FOLHA
	 ,F.FUMATFUNC AS MATFUNC
	 ,E.[EMCODEMP] AS EMPCODE
	 ,F.FUTIPOADMS AS TIPOADM
	 ,W.TIPO_SAP AS TIPO_SAP
	 ,CASE
			WHEN (E.[EMNOMEMP] = 'NUTRIEX IMPORTAÇAO E EXPORTAÇAO DE PROD NUTRICIONAIS E FARMOQUIMICOS LTDA' OR E.[EMNOMEMP] = 'ACAO OPERADORA FACTOR LTDA - ME') THEN W.CONTA_NPH
			WHEN H.TABELA = 'IND_DIR' THEN W.CONTA_IND_DIR
			WHEN H.TABELA = 'IND_IND' THEN W.CONTA_IND_IND
			ELSE W.CONTA_GERAL
	  END AS CONTA_CONTABIL
	 ,'RESCISAO' AS FOLHA_TIPO
	 ,COALESCE(H.TABELA,'GERAL') AS TABELA, 'BASE' AS BASE, 0 AS ID, 1 AS BPLID, 'FILIAL' AS BPLNAME, '00000000000000' AS BPLCNPJ, 0 AS JDT1_NUMBER
	FROM [FPW5].[DBO].[VALANO] V
		INNER JOIN [FPW5].[DBO].[FUNCIONA] F ON V.VACODEMP = F.FUCODEMP AND V.VAMATFUNC = F.FUMATFUNC
		INNER JOIN [FPW5].[dbo].[EMPRESAS] E ON E.[EMCODEMP] = F.FUCODEMP
		INNER JOIN [FPW5].[dbo].[EVENTOS] T ON T.[EVCODEVENT] = V.VACODEVENT
		INNER JOIN [FPW5].[dbo].[SITUACAO] S ON S.[STCODSITU] = F.FUCODSITU
		INNER JOIN [FPW5].[dbo].[LOTACOES] L ON L.[LOCODEMP] = E.[EMCODEMP] AND L.[LOCODLOT] = F.FUCODLOT
		LEFT JOIN [FPW5].[dbo].[CENCUSTO] C ON C.[CCCODIGO] = F.[FUCENTRCUS] AND C.[CCCODEMP] = F.[FUCODEMP]
		LEFT JOIN [FPW5].[dbo].[ATRIBFUN] A ON A.AFCODEMP = E.EMCODEMP AND A.AFMATFUNC = F.FUMATFUNC AND A.AFCODATRIB = 1
		LEFT JOIN MBS.[dbo].FOLHA_TABELA H ON H.EMPRESA = E.[EMNOMEMP] AND H.CENTROCUSTO = C.CCDESCRIC
		LEFT JOIN MBS.[dbo].FOLHA_CONTA_CONTABIL W ON W.CODIGO_FOLHA = V.VACODEVENT
	WHERE V.VADTREFER LIKE @dataref AND (VACODFOLHA = 5 OR VACODFOLHA = 7 OR VACODFOLHA = 8) AND V.VACODEMP <> 1 AND V.VACODEMP <> 13  AND V.VACODEVENT = 10990 AND  NOT (F.FUCODCAGED = 70 AND LEFT(F.FUDTSUCECESS,6) = CONCAT(LEFT(V.VADTREFER,4),FORMAT(RIGHT(V.VADTREFER,2)+1,'00')))



	--============================= FOLHA DECIMO TERCEIRO PARA GERAR APENAS OS EVENTOS DE RESULTADO 10990 E ACRESCENTA-LOS A TABELA ================================

INSERT INTO MBS..FOLHAONLINE
	SELECT
	 E.[EMNOMEMP] AS EMPRESA
	,L.[LODESCLOT] AS FILIAL
	,CONCAT(FORMAT(F.FUMATFUNC,'000'),' - ',F.FUNOMFUNC COLLATE DATABASE_DEFAULT) AS NOME 
	,C.CCDESCRIC AS CENTRO_CUSTO
	,A.[AFVALOR] AS PROJETO
	,S.[STDESCSITU] AS SITUACAO		--, F.FUCODCAGED AS CAGED, F.FUDTSUCECESS AS DTSUCESSAO --ESSE FILTRO DEMONSTRA OS FUNCIONARIOS QUE ENTRARAM TRANSFERIDOS DE OUTRA EMPRESA
	,V.VADTREFER AS DATAREF
	--,FORMAT(V.VACODEVENT,'00000') AS EVENTO_COD
	,CONCAT(FORMAT(V.VACODEVENT,'00000'),' - ',T.[EVDESCOMPL] COLLATE DATABASE_DEFAULT) AS EVENTO_NOM
	,CASE
		WHEN T.EVINDEVENT = 'D' THEN CAST(-V.VAVALEVENT AS FLOAT)
		WHEN T.EVINDEVENT = 'P' THEN CAST(V.VAVALEVENT AS FLOAT)
		ELSE CAST(V.VAVALEVENT AS FLOAT) 
	 END AS VALOR
	,CASE
		WHEN T.EVINDEVENT = 'D' THEN 'DESCONTO'
		WHEN T.EVINDEVENT = 'P' THEN 'PROVENTO'
		WHEN T.EVINDEVENT = 'R' THEN 'RESULTADO'
		ELSE T.EVINDEVENT 
	 END AS TIPO_FOLHA
	 ,F.FUMATFUNC AS MATFUNC
	 ,E.[EMCODEMP] AS EMPCODE
	 ,F.FUTIPOADMS AS TIPOADM
	 ,W.TIPO_SAP AS TIPO_SAP
	 ,CASE
			WHEN (E.[EMNOMEMP] = 'NUTRIEX IMPORTAÇAO E EXPORTAÇAO DE PROD NUTRICIONAIS E FARMOQUIMICOS LTDA' OR E.[EMNOMEMP] = 'ACAO OPERADORA FACTOR LTDA - ME') THEN W.CONTA_NPH
			WHEN H.TABELA = 'IND_DIR' THEN W.CONTA_IND_DIR
			WHEN H.TABELA = 'IND_IND' THEN W.CONTA_IND_IND
			ELSE W.CONTA_GERAL
	  END AS CONTA_CONTABIL
	 ,'DECIMO' AS FOLHA_TIPO
	 ,COALESCE(H.TABELA,'GERAL') AS TABELA, 'BASE' AS BASE, 0 AS ID, 1 AS BPLID, 'FILIAL' AS BPLNAME, '00000000000000' AS BPLCNPJ, 0 AS JDT1_NUMBER
	FROM [FPW5].[DBO].[VALANO] V
		INNER JOIN [FPW5].[DBO].[FUNCIONA] F ON V.VACODEMP = F.FUCODEMP AND V.VAMATFUNC = F.FUMATFUNC
		INNER JOIN [FPW5].[dbo].[EMPRESAS] E ON E.[EMCODEMP] = F.FUCODEMP
		INNER JOIN [FPW5].[dbo].[EVENTOS] T ON T.[EVCODEVENT] = V.VACODEVENT
		INNER JOIN [FPW5].[dbo].[SITUACAO] S ON S.[STCODSITU] = F.FUCODSITU
		INNER JOIN [FPW5].[dbo].[LOTACOES] L ON L.[LOCODEMP] = E.[EMCODEMP] AND L.[LOCODLOT] = F.FUCODLOT
		LEFT JOIN [FPW5].[dbo].[CENCUSTO] C ON C.[CCCODIGO] = F.[FUCENTRCUS] AND C.[CCCODEMP] = F.[FUCODEMP]
		LEFT JOIN [FPW5].[dbo].[ATRIBFUN] A ON A.AFCODEMP = E.EMCODEMP AND A.AFMATFUNC = F.FUMATFUNC AND A.AFCODATRIB = 1
		LEFT JOIN MBS.[dbo].FOLHA_TABELA H ON H.EMPRESA = E.[EMNOMEMP] AND H.CENTROCUSTO = C.CCDESCRIC
		LEFT JOIN MBS.[dbo].FOLHA_CONTA_CONTABIL W ON W.CODIGO_FOLHA = V.VACODEVENT
	WHERE V.VADTREFER LIKE @dataref AND VACODFOLHA = 4 AND V.VACODEMP <> 1 AND V.VACODEMP <> 13 AND V.VACODEVENT = 10990 AND NOT (F.FUCODCAGED = 70 AND LEFT(F.FUDTSUCECESS,6) = CONCAT(LEFT(V.VADTREFER,4),FORMAT(RIGHT(V.VADTREFER,2)+1,'00')))



--============= ATUALIZAR NOME BANCO DE DADOS =============

UPDATE MBS..FOLHAONLINE
	SET DATABASE_NAME = 
					CASE
						WHEN EMPRESA = 'A7 DISTRIBUIDORA DE MEDICAMENTOS EIRELI' THEN 'SBOA7'
						WHEN EMPRESA = 'CHUA CHUA SERVIÇOS E FRANQUIAS LTDA' THEN 'SboChuaChua'
						WHEN EMPRESA = 'DL DISTRIBUIDORA DE MEDICAMENTOS EIRELI' THEN 'SBODL'
						WHEN EMPRESA = 'EMPREENDIMENTOS E PARTICIPAÇOES RZ LTDA' THEN 'SBOEmpreendimentosRZ'
						WHEN EMPRESA = 'EMPREENDIMENTOS E PARTICIPAÇOES SM LTDA' THEN 'SBOEmpreendimentosSM'
						WHEN EMPRESA = 'EQUILIBRIUM DISTRIBUIDORA DE MEDICAMENTOS EIRELI' THEN 'SBOEquilibrium'
						WHEN EMPRESA = 'BELA CARIOCA DISTRIBUIDORA DE COSMETICOS LTDA' THEN 'SBOGDSMARCAS'
						WHEN EMPRESA = 'INNOVAPHARMA LABORAT MANIPULAÇÃO' THEN 'SboInnovaLab'
						WHEN EMPRESA = 'ACAO OPERADORA FACTOR LTDA - ME' THEN 'SBOLICITAACAO'
						WHEN EMPRESA = 'EMPREENDIMENTOS E PARTICIPAÇOES DA MATA LTDA' THEN 'SBOMW'
						WHEN EMPRESA = 'MW DISTRIBUIDORA DE MEDICAMENTOS EIRELI' THEN 'SBOMW'
						WHEN EMPRESA = 'NUTRIEX INDUSTRIA NUTRACEUTICOS LTDA' THEN 'SBOMW'
						WHEN EMPRESA = 'NUTRIEX IMPORTAÇAO E EXPORTAÇAO DE PROD NUTRICIONAIS E FARMOQUIMICOS LTDA' THEN 'SBONutGynMatriz'
						WHEN EMPRESA = 'NUTRIEX INDUSTRIA DE COSMETICOS LTDA' THEN 'SBONutriexInd'
						WHEN EMPRESA = 'ORALLS IMP. E EXP. COMERCIAL LTDA' THEN 'SboOralls'
						WHEN EMPRESA = 'VDM OPERAÇÕES LOGISTICAS EIRELI' THEN 'SBOVidafarma'
						WHEN EMPRESA = 'EMPREENDIMENTOS E PARTICIPAÇOES ZAIDEN LTDA' THEN 'SBOZ9'
						WHEN EMPRESA = 'EMPREENDIMENTOS E PARTICIPAÇOES L REZENDE LTDA' THEN 'SBOEmpLREZENDE'
						WHEN EMPRESA = 'INNOVAPHARMA BRASIL FARMACEUTICA' THEN 'SBOInnovaBR'
					ELSE EMPRESA END,
	
	DATABASE_ID =
					CASE
						WHEN EMPRESA = 'A7 DISTRIBUIDORA DE MEDICAMENTOS EIRELI' THEN 41
						WHEN EMPRESA = 'CHUA CHUA SERVIÇOS E FRANQUIAS LTDA' THEN 70
						WHEN EMPRESA = 'DL DISTRIBUIDORA DE MEDICAMENTOS EIRELI' THEN 87
						WHEN EMPRESA = 'EMPREENDIMENTOS E PARTICIPAÇOES RZ LTDA' THEN 77
						WHEN EMPRESA = 'EMPREENDIMENTOS E PARTICIPAÇOES SM LTDA' THEN 78
						WHEN EMPRESA = 'EQUILIBRIUM DISTRIBUIDORA DE MEDICAMENTOS EIRELI' THEN 27
						WHEN EMPRESA = 'BELA CARIOCA DISTRIBUIDORA DE COSMETICOS LTDA' THEN 64
						WHEN EMPRESA = 'INNOVAPHARMA LABORAT MANIPULAÇÃO' THEN 68
						WHEN EMPRESA = 'ACAO OPERADORA FACTOR LTDA - ME' THEN 29
						WHEN EMPRESA = 'EMPREENDIMENTOS E PARTICIPAÇOES DA MATA LTDA' THEN 6
						WHEN EMPRESA = 'MW DISTRIBUIDORA DE MEDICAMENTOS EIRELI' THEN 6
						WHEN EMPRESA = 'NUTRIEX INDUSTRIA NUTRACEUTICOS LTDA' THEN 6
						WHEN EMPRESA = 'NUTRIEX IMPORTAÇAO E EXPORTAÇAO DE PROD NUTRICIONAIS E FARMOQUIMICOS LTDA' THEN 33
						WHEN EMPRESA = 'NUTRIEX INDUSTRIA DE COSMETICOS LTDA' THEN 34
						WHEN EMPRESA = 'ORALLS IMP. E EXP. COMERCIAL LTDA' THEN 72
						WHEN EMPRESA = 'VDM OPERAÇÕES LOGISTICAS EIRELI' THEN 7
						WHEN EMPRESA = 'EMPREENDIMENTOS E PARTICIPAÇOES ZAIDEN LTDA' THEN 37
						WHEN EMPRESA = 'EMPREENDIMENTOS E PARTICIPAÇOES L REZENDE LTDA' THEN 91
						WHEN EMPRESA = 'INNOVAPHARMA BRASIL FARMACEUTICA' THEN 92
					ELSE 0 END,
		BPLID =
				CASE
					WHEN FILIAL = 'A7 DISTRIBUIDORA DE MEDICAMENTOS EIRELI - MTZ' THEN 1
					WHEN FILIAL = 'A7 DISTRIBUIDORA DE MEDICAMENTOS EIRELI - FL2' THEN 3
					WHEN FILIAL = 'CHUA CHUA SERVIÇOS E FRANQUIAS LTDA' THEN 1
					WHEN FILIAL = 'DL DISTRIBUIDORA DE MEDICAMENTOS EIRELI' THEN 1
					WHEN FILIAL = 'EMPREENDIMENTOS E PARTICIPAÇOES RZ LTDA' THEN 1
					WHEN FILIAL = 'EMPREENDIMENTOS E PARTICIPAÇOES SM LTDA' THEN 1
					WHEN FILIAL = 'EQUILIBRIUM DIST. DE MEDICAMENTOS EIRELI MTZ' THEN 1
					WHEN FILIAL = 'EQUILIBRIUM DIST. DE MEDICAMENTOS EIRELI FL1' THEN 2
					WHEN FILIAL = 'BELA CARIOCA DISTRIBUIDORA DE COSMETICOS LTDA' THEN 3
					WHEN FILIAL = 'INNOVAPHARMA LABORAT E MANIPULAÇÃO LTDA - MTZ' THEN 1
					WHEN FILIAL = 'ACAO OPERADORA FACTOR LTDA - ME' THEN 1
					WHEN FILIAL = 'NUTRIEX INDUSTRIA DE NUTRACEUTICOS LTDA' THEN 3
					WHEN FILIAL = 'MW DISTRIBUIDORA DE MEDICAMENTOS EIRELI MTZ' THEN 1
					WHEN FILIAL = 'EMPREENDIMENTOS E PARTICIPAÇOES DA MATA LTDA' THEN 5
					WHEN FILIAL = 'MW DISTRIBUIDORA DE MEDICAMENTOS EIRELI FL3' THEN 10
					WHEN FILIAL = 'NUTRIEX IMP E EXP PROD NUT E FARMO LTDA - MTZ' THEN 1
					WHEN FILIAL = 'NUTRIEX INDUSTRIA DE COSMETICOS LTDA - MTZ' THEN 1
					WHEN FILIAL = 'NUTRIEX INDUSTRIA DE COSMETICOS LTDA - FL1' THEN 11
					WHEN FILIAL = 'ORALLS IMPORT E EXPORT COMERCIAL LTDA - MTZ' THEN 1
					WHEN FILIAL = 'ORALLS IMPORT E EXPORT COMERCIAL LTDA - FL2' THEN 1
					WHEN FILIAL = 'VDM OPERAÇÕES LOGISTICAS EIRELI MTZ' THEN 1
					WHEN FILIAL = 'EMPREENDIMENTOS E PARTICIPAÇOES ZAIDEN LTDA' THEN 1
					WHEN FILIAL = 'EMPREENDIMENTOS E PARTICIPACOES L REZENDE MTZ' THEN 1
					WHEN FILIAL = 'INNOVAPHARMA BRASIL FARMACEUTICA' THEN 1
				ELSE 1 END,

		BPLNAME =
				CASE
					WHEN FILIAL = 'A7 DISTRIBUIDORA DE MEDICAMENTOS EIRELI - MTZ' THEN 'A7 Distribuidora'
					WHEN FILIAL = 'A7 DISTRIBUIDORA DE MEDICAMENTOS EIRELI - FL2' THEN 'A7 BSB'
					WHEN FILIAL = 'CHUA CHUA SERVIÇOS E FRANQUIAS LTDA' THEN 'Padrão'
					WHEN FILIAL = 'DL DISTRIBUIDORA DE MEDICAMENTOS EIRELI' THEN 'Padrão'
					WHEN FILIAL = 'EMPREENDIMENTOS E PARTICIPAÇOES RZ LTDA' THEN 'Padrão'
					WHEN FILIAL = 'EMPREENDIMENTOS E PARTICIPAÇOES SM LTDA' THEN 'Padrão'
					WHEN FILIAL = 'EQUILIBRIUM DIST. DE MEDICAMENTOS EIRELI MTZ' THEN 'Equilibrium'
					WHEN FILIAL = 'EQUILIBRIUM DIST. DE MEDICAMENTOS EIRELI FL1' THEN 'Equilibrium F01'
					WHEN FILIAL = 'BELA CARIOCA DISTRIBUIDORA DE COSMETICOS LTDA' THEN 'BELA CARIOCA'
					WHEN FILIAL = 'INNOVAPHARMA LABORAT E MANIPULAÇÃO LTDA - MTZ' THEN 'Padrão'
					WHEN FILIAL = 'ACAO OPERADORA FACTOR LTDA - ME' THEN 'Licitaação Software Ltda - ME'
					WHEN FILIAL = 'NUTRIEX INDUSTRIA DE NUTRACEUTICOS LTDA' THEN 'Nutriex Nutracêutica'
					WHEN FILIAL = 'MW DISTRIBUIDORA DE MEDICAMENTOS EIRELI MTZ' THEN 'MW Matriz'
					WHEN FILIAL = 'EMPREENDIMENTOS E PARTICIPAÇOES DA MATA LTDA' THEN 'XDM'
					WHEN FILIAL = 'MW DISTRIBUIDORA DE MEDICAMENTOS EIRELI FL3' THEN 'MW Filial 04'
					WHEN FILIAL = 'NUTRIEX IMP E EXP PROD NUT E FARMO LTDA - MTZ' THEN 'Nutriex NPH'
					WHEN FILIAL = 'NUTRIEX INDUSTRIA DE COSMETICOS LTDA - MTZ' THEN 'Nutriex  Cosmética'
					WHEN FILIAL = 'NUTRIEX INDUSTRIA DE COSMETICOS LTDA - FL1' THEN 'Nutriex Cosmética - Filial 01'
					WHEN FILIAL = 'ORALLS IMPORT E EXPORT COMERCIAL LTDA - MTZ' THEN 'Padrão'
					WHEN FILIAL = 'ORALLS IMPORT E EXPORT COMERCIAL LTDA - FL2' THEN 'Padrão'
					WHEN FILIAL = 'VDM OPERAÇÕES LOGISTICAS EIRELI MTZ' THEN 'VDM - Operações Logísticas'
					WHEN FILIAL = 'EMPREENDIMENTOS E PARTICIPAÇOES ZAIDEN LTDA' THEN 'Z9'
					WHEN FILIAL = 'EMPREENDIMENTOS E PARTICIPACOES L REZENDE MTZ' THEN 'Padrão'
					WHEN FILIAL = 'INNOVAPHARMA BRASIL FARMACEUTICA' THEN 'Padrão'
				ELSE 'PADRÃO' END,

		BPLCNPJ =
				CASE		
					WHEN FILIAL = 'A7 DISTRIBUIDORA DE MEDICAMENTOS EIRELI - MTZ' THEN '12.664.453/0001-00'
					WHEN FILIAL = 'A7 DISTRIBUIDORA DE MEDICAMENTOS EIRELI - FL2' THEN '12.664.453/0003-63'
					WHEN FILIAL = 'CHUA CHUA SERVIÇOS E FRANQUIAS LTDA' THEN '21.619.645/0001-87'
					WHEN FILIAL = 'DL DISTRIBUIDORA DE MEDICAMENTOS EIRELI' THEN '31.556.536/0001-11'
					WHEN FILIAL = 'EMPREENDIMENTOS E PARTICIPAÇOES RZ LTDA' THEN '29.108.266/0001-34'
					WHEN FILIAL = 'EMPREENDIMENTOS E PARTICIPAÇOES SM LTDA' THEN '29.147.450/0001-93'
					WHEN FILIAL = 'EQUILIBRIUM DIST. DE MEDICAMENTOS EIRELI MTZ' THEN '07.642.426/0001-98'
					WHEN FILIAL = 'EQUILIBRIUM DIST. DE MEDICAMENTOS EIRELI FL1' THEN '07.642.426/0002-79'
					WHEN FILIAL = 'BELA CARIOCA DISTRIBUIDORA DE COSMETICOS LTDA' THEN '27.970.197/0001-48'
					WHEN FILIAL = 'INNOVAPHARMA LABORAT E MANIPULAÇÃO LTDA - MTZ' THEN '28.846.752/0001-97'
					WHEN FILIAL = 'ACAO OPERADORA FACTOR LTDA - ME' THEN '06.216.586/0001-02'
					WHEN FILIAL = 'NUTRIEX INDUSTRIA DE NUTRACEUTICOS LTDA' THEN '22.966.065/0001-29'
					WHEN FILIAL = 'MW DISTRIBUIDORA DE MEDICAMENTOS EIRELI MTZ' THEN '14.459.413/0001-43'
					WHEN FILIAL = 'EMPREENDIMENTOS E PARTICIPAÇOES DA MATA LTDA' THEN '18.964.194/0001-00'
					WHEN FILIAL = 'MW DISTRIBUIDORA DE MEDICAMENTOS EIRELI FL3' THEN '14.459.413/0004-96'
					WHEN FILIAL = 'NUTRIEX IMP E EXP PROD NUT E FARMO LTDA - MTZ' THEN '06.172.459/0001-59'
					WHEN FILIAL = 'NUTRIEX INDUSTRIA DE COSMETICOS LTDA - MTZ' THEN '15.058.160/0001-69'
					WHEN FILIAL = 'NUTRIEX INDUSTRIA DE COSMETICOS LTDA - FL1' THEN '15.058.160/0002-40'
					WHEN FILIAL = 'ORALLS IMPORT E EXPORT COMERCIAL LTDA - MTZ' THEN '04.980.028/0001-93'
					WHEN FILIAL = 'ORALLS IMPORT E EXPORT COMERCIAL LTDA - FL2' THEN '04.980.028/0003-55'
					WHEN FILIAL = 'VDM OPERAÇÕES LOGISTICAS EIRELI MTZ' THEN '06.219.757/0001-57'
					WHEN FILIAL = 'EMPREENDIMENTOS E PARTICIPAÇOES ZAIDEN LTDA' THEN '19.237.613/0001-75'
					WHEN FILIAL = 'EMPREENDIMENTOS E PARTICIPACOES L REZENDE MTZ' THEN '34.306.557/0001-77'
					WHEN FILIAL = 'INNOVAPHARMA BRASIL FARMACEUTICA' THEN '34.771.518/0001-40'
				ELSE '00000000000000' END,
			
			EVENTO =
				CASE
					WHEN (FOLHA_TIPO = 'PROLABORE' AND EVENTO LIKE '10990 - %') THEN '10990 - PROLABORE LIQUIDO'
					WHEN (FOLHA_TIPO = 'RESCISAO' AND EVENTO LIKE '10990 - %') THEN '10990 - RESCISAO LIQUIDA'
					WHEN ((FOLHA_TIPO = 'MENSAL' OR FOLHA_TIPO = 'TOTALM') AND EVENTO LIKE '10990 - %') THEN '10990 - SALARIO LIQUIDO'
					WHEN (FOLHA_TIPO = 'DECIMO' AND EVENTO LIKE '10990 - %') THEN '10990 - DECIMO LIQUIDO'
					ELSE EVENTO END,
			
			CONTA_CONTABIL = 
				CASE
					WHEN (FOLHA_TIPO = 'DECIMO' AND EVENTO LIKE '10990 - %' AND (EMPRESA = 'NUTRIEX IMPORTAÇAO E EXPORTAÇAO DE PROD NUTRICIONAIS E FARMOQUIMICOS LTDA' OR EMPRESA = 'ACAO OPERADORA FACTOR LTDA - ME')) THEN '1.1.02.04.10.2'
					WHEN (FOLHA_TIPO = 'PROLABORE' AND EVENTO LIKE '10990 - %' AND TABELA = 'NPH') THEN '2.1.05.01.04'
					WHEN (FOLHA_TIPO = 'RESCISAO' AND EVENTO LIKE '10990 - %' AND TABELA = 'NPH') THEN '2.1.05.01.07'
					WHEN ((FOLHA_TIPO = 'MENSAL' OR FOLHA_TIPO = 'TOTALM') AND EVENTO LIKE '10990 - %' AND TABELA = 'NPH') THEN '2.1.05.01.01'
					WHEN (FOLHA_TIPO = 'DECIMO' AND EVENTO LIKE '10990 - %' AND (EMPRESA NOT LIKE 'NUTRIEX IMPORTAÇAO E EXPORTAÇAO DE PROD NUTRICIONAIS E FARMOQUIMICOS LTDA' AND EMPRESA NOT LIKE 'ACAO OPERADORA FACTOR LTDA - ME')) THEN '1.1.03.05.02'
					WHEN (FOLHA_TIPO = 'PROLABORE' AND EVENTO LIKE '10990 - %' AND TABELA <> 'NPH') THEN '2.1.01.01.04'
					WHEN (FOLHA_TIPO = 'RESCISAO' AND EVENTO LIKE '10990 - %' AND TABELA <> 'NPH') THEN '2.1.01.01.05'
					WHEN ((FOLHA_TIPO = 'MENSAL' OR FOLHA_TIPO = 'TOTALM') AND EVENTO LIKE '10990 - %' AND TABELA <> 'NPH') THEN '2.1.01.01.01'
					ELSE [CONTA_CONTABIL] END

UPDATE MBS..FOLHAONLINE
	SET TABELA = 
		CASE WHEN DATABASE_NAME LIKE '%GYN%' OR DATABASE_NAME LIKE '%ACAO%' THEN 'NPH'
		ELSE TABELA END

--============= GERAR A FOLHA IMPORTACAO NO SAP ============= 
DELETE FROM MBS..INTEGRA_FOLHA_SAP WHERE STATUS_GERACAO = 0

IF (SELECT COUNT(HISTORICO) FROM MBS..INTEGRA_FOLHA_SAP HAVING MAX(DATAREF) = @dataref) = 0 OR (SELECT COUNT(HISTORICO) FROM MBS..INTEGRA_FOLHA_SAP HAVING MAX(DATAREF) = @dataref) IS NULL
BEGIN

	INSERT INTO MBS..INTEGRA_FOLHA_SAP
	SELECT
		 F.DATABASE_NAME
		,F.DATABASE_ID
		,F.DATAREF
		,F.FILIAL
		,LEFT(F.PROJETO,7) AS PROJETO
		,F.CONTA_CONTABIL
		,F.TIPO_SAP
		,CASE
			WHEN F.FOLHA_TIPO LIKE 'PROV_FER%' THEN 'PRVFER'
			WHEN F.FOLHA_TIPO LIKE 'PROV_13%' THEN 'PRVD13'
			WHEN F.FOLHA_TIPO LIKE 'PROLAB%' THEN 'PROLAB'
			WHEN F.FOLHA_TIPO LIKE 'RESC%' THEN 'RESCIS'
			ELSE F.FOLHA_TIPO END AS TIPO_FOLHA
		,CONCAT(
			CASE
				WHEN F.FOLHA_TIPO COLLATE DATABASE_DEFAULT LIKE 'PROV_FER%' THEN 'PRVFER'
				WHEN F.FOLHA_TIPO COLLATE DATABASE_DEFAULT LIKE 'PROV_13%' THEN 'PRVD13'
				WHEN F.FOLHA_TIPO COLLATE DATABASE_DEFAULT LIKE 'PROLAB%' THEN 'PROLAB'
				WHEN F.FOLHA_TIPO COLLATE DATABASE_DEFAULT LIKE 'RESC%' THEN 'RESCIS'
				ELSE F.FOLHA_TIPO COLLATE DATABASE_DEFAULT END, ' (',
			F.DATAREF COLLATE DATABASE_DEFAULT,'), ',F.EVENTO COLLATE DATABASE_DEFAULT) AS HISTORICO
		,SUM(F.VALOR) AS TOTAL
		,0 AS STATUS_GERACAO
		,-1 AS OJDT_NUMBER
		,F.BPLID
		,F.BPLNAME
		,F.BPLCNPJ
		,F.JDT1_NUMBER
		,F.TABELA
		FROM MBS..FOLHAONLINE F 
		WHERE F.DATAREF = @dataref AND F.EVENTO NOT LIKE '%P%ACUM%'
		GROUP BY
			 F.DATABASE_NAME
			,F.DATABASE_ID
			,F.FILIAL
			,LEFT(F.PROJETO,7)
			,F.CONTA_CONTABIL
			,F.TIPO_SAP
			,F.FOLHA_TIPO
			,F.DATAREF
			,F.EVENTO
			,F.BPLID
			,F.BPLNAME
			,F.BPLCNPJ
			,F.JDT1_NUMBER
			,F.TABELA


	INSERT INTO MBS..INTEGRA_FOLHA_SAP ([JDT1_NUMBER] ,[DATABASE_NAME] ,[DATABASE_ID] ,[DATAREF] ,[FILIAL] ,[PROJETO] ,[CONTA_CONTABIL] ,[TIPO_SAP] ,[TIPO_FOLHA] ,[HISTORICO] ,[TOTAL] ,[STATUS_GERACAO] ,[OJDT_NUMBER] ,[BPLID] ,[BPLNAME] ,[BPLCNPJ] ,[TABELA])
		SELECT 0,[DATABASE_NAME] ,[DATABASE_ID] ,[DATAREF] ,[FILIAL] ,[PROJETO] 
		, CASE
			WHEN TABELA NOT LIKE 'NPH' THEN
				CASE
					WHEN HISTORICO LIKE '%FGTS%' OR HISTORICO LIKE '%INSS%' THEN '2.1.09.01.03'
					WHEN HISTORICO LIKE '%PF -%' THEN '2.1.09.01.01'
					WHEN HISTORICO LIKE '%P13 -%' THEN '2.1.09.01.02'
					ELSE [CONTA_CONTABIL] END         
			ELSE
				CASE
					WHEN HISTORICO LIKE '%FGTS%' OR HISTORICO LIKE '%INSS%' THEN '2.1.06.01.03'
					WHEN HISTORICO LIKE '%PF -%' THEN '2.1.06.01.01'
					WHEN HISTORICO LIKE '%P13 -%' THEN '2.1.06.01.02'
					ELSE [CONTA_CONTABIL] END   
			END				
			,'CREDITO' ,[TIPO_FOLHA] ,[HISTORICO] ,[TOTAL] ,[STATUS_GERACAO] ,[OJDT_NUMBER] ,[BPLID] ,[BPLNAME] ,[BPLCNPJ] ,[TABELA] FROM MBS..INTEGRA_FOLHA_SAP WHERE TIPO_FOLHA LIKE 'PRV%'


	INSERT INTO MBS..INTEGRA_FOLHA_SAP
		SELECT
			 [DATABASE_NAME]
			,[DATABASE_ID]
			,[DATAREF]
			,[FILIAL]
			,[PROJETO]
			,[CONTA_CONTABIL]
			,[TIPO_SAP]
			,[TIPO_FOLHA]
			,[HISTORICO]
			,[TOTAL]
			,[STATUS_GERACAO]
			,1 AS [OJDT_NUMBER]
			,[BPLID]
			,[BPLNAME]
			,[BPLCNPJ]
			,ROW_NUMBER() OVER(PARTITION BY DATAREF, FILIAL, TIPO_FOLHA ORDER BY  TIPO_SAP DESC, HISTORICO ASC) AS [JDT1_NUMBER]
			,[TABELA]
		FROM [Mbs].[dbo].[INTEGRA_FOLHA_SAP]

		DELETE FROM MBS..INTEGRA_FOLHA_SAP WHERE OJDT_NUMBER = -1

		UPDATE MBS..INTEGRA_FOLHA_SAP 
			SET HISTORICO = 
				CASE 
					WHEN ([TIPO_FOLHA] = 'MENSAL' OR [TIPO_FOLHA] = 'TOTALM') AND HISTORICO LIKE '%10990%' THEN 'SALARIO LIQUIDO A PAGAR REF. ' + @dataref
					WHEN [TIPO_FOLHA] = 'PROLAB' AND HISTORICO LIKE '%10990%' THEN 'PROLABORE LIQUIDO A PAGAR REF. ' + @dataref
					WHEN [TIPO_FOLHA] = 'RESCIS' AND HISTORICO LIKE '%10990%' THEN 'RESCISAO LIQUIDA A PAGAR REF. ' + @dataref
					WHEN [TIPO_FOLHA] = 'DECIMO' AND HISTORICO LIKE '%10990%' THEN 'DECIMO LIQUIDO A PAGAR REF. ' + @dataref
					ELSE HISTORICO END,
			JDT1_NUMBER = JDT1_NUMBER - 1,
			[TIPO_SAP] = 
				CASE
					WHEN (CONTA_CONTABIL LIKE '2%') AND ([TIPO_FOLHA] = 'PRVD13' OR [TIPO_FOLHA] = 'PRVFER') AND (HISTORICO LIKE '%BAIXA%' OR HISTORICO LIKE '%NEGATIVO%') THEN 'DEBITO'
					ELSE [TIPO_SAP] END,
			[PROJETO] = 
				CASE
					WHEN (CHARINDEX('-',projeto,1)) = 0 THEN 'GEN-000'
					ELSE [PROJETO] END
		

--============ EXCLUI AS BAIXAS DAS PREVISOES =========================
		DELETE FROM MBS..INTEGRA_FOLHA_SAP WHERE [TIPO_FOLHA] LIKE 'PRV%' AND HISTORICO LIKE '%BAIXA%'

		SELECT * FROM MBS..INTEGRA_FOLHA_SAP


END;
ELSE 
	BEGIN 
		--Send mail
		SET @texto = N'ERRO INTEGRA_FOLHA_SAP!!! FOLHA AUTOMATIZADA NAO REALIZADA - PERIODO: ' + CAST(@dataref AS NVARCHAR(MAX)) 
		EXEC msdb.dbo.sp_send_dbmail
			@recipients=N'rodrigo.matos@mw.far.br',
			--@copy_recipients=N'junior.nunes@eficienciacont.com.br',
			@body= N'ETAPA 01/03 - NADA FOI GERADO PARA ESTA FOLHA INTEGRA_FOLHA_SAP! RODRIGO MATOS.',
			@body_format = 'HTML',
			@subject = @texto,
			@profile_name = 'NutriexReports'
	END;