DECLARE @loop int = (SELECT COUNT(baseid) FROM mbs..bases);
DECLARE @i int = 0; 
DECLARE @empresa nvarchar(MAX);
DECLARE @pathORCT nvarchar(MAX);
DECLARE @pathRCT2 nvarchar(MAX);
DECLARE @pathOINV nvarchar(MAX);
DECLARE @pathORIN nvarchar(MAX);
DECLARE @pathINV1 nvarchar(MAX);
DECLARE @pathRIN1 nvarchar(MAX);
DECLARE @pathODPI nvarchar(MAX);
DECLARE @pathRCT3 nvarchar(MAX);
DECLARE @pathOACT nvarchar(MAX);
DECLARE @pathFT_ORCA nvarchar(MAX);
DECLARE @pathFT_OHRQ nvarchar(MAX);

DROP TABLE [MBS].[dbo].[FLUXOR]

CREATE TABLE [MBS].[dbo].[FLUXOR](
	[ORIGEM] [nvarchar](8) NULL,
	[BASE] [nvarchar](50) NULL,
	[FILIAL] [nvarchar](200) NULL,
	[DOCCR] [nvarchar](15) NULL,
	[DOCNFS] [nvarchar](15) NULL,
	[NUMNFS] [nvarchar](15) NULL,
	[TRANSIDCR] [nvarchar](15) NULL,
	[TRANSIDNFS] [nvarchar](15) NULL,
	[SUPERVISOR] [nvarchar](100) NULL,
	[FORMA_PGTO] [nvarchar](15) NULL,
	[DTFATNFS] [nvarchar](20) NULL,
	[DTVENCNFS] [nvarchar](20) NULL,
	[DTRECEB] [nvarchar](20) NULL,
	[CODPN] [nvarchar](15) NULL,
	[NOMEPN] [nvarchar](100) NULL,
	[TIPODOC] [nvarchar](20) NULL,
	[VLRNFS] [float] NULL,
	[VLRDOCCR] [float](15) NULL,
	[PARCELA] [nvarchar](15) NULL,
	[PARCELAS] [nvarchar](15) NULL,
	[CONTACOD] [nvarchar](15) NULL,
	[CONTANOME] [nvarchar](100) NULL,
	[OBSERVACAO] [nvarchar](MAX) NULL
) ON [PRIMARY]


while @i < @loop
	begin
		set @i = @i + 1;
		set @empresa = (select empresa from mbs..bases where baseid = @i)

		set @pathORCT = CONCAT(N'CREATE SYNONYM tpathORCT FOR ',@empresa,N'.DBO.ORCT');
		set @pathRCT2 = CONCAT(N'CREATE SYNONYM tpathRCT2 FOR ',@empresa,N'.DBO.RCT2');
		set @pathOINV = CONCAT(N'CREATE SYNONYM tpathOINV FOR ',@empresa,N'.DBO.OINV');
		set @pathORIN = CONCAT(N'CREATE SYNONYM tpathORIN FOR ',@empresa,N'.DBO.ORIN');
		set @pathINV1 = CONCAT(N'CREATE SYNONYM tpathINV1 FOR ',@empresa,N'.DBO.INV1');
		set @pathRIN1 = CONCAT(N'CREATE SYNONYM tpathRIN1 FOR ',@empresa,N'.DBO.RIN1');
		set @pathODPI = CONCAT(N'CREATE SYNONYM tpathODPI FOR ',@empresa,N'.DBO.ODPI');
		set @pathRCT3 = CONCAT(N'CREATE SYNONYM tpathRCT3 FOR ',@empresa,N'.DBO.RCT3');
		set @pathOACT = CONCAT(N'CREATE SYNONYM tpathOACT FOR ',@empresa,N'.DBO.OACT');
		set @pathFT_ORCA = CONCAT(N'CREATE SYNONYM tpathFT_ORCA FOR ',@empresa,N'.DBO.[@FT_ORCA]');
		set @pathFT_OHRQ = CONCAT(N'CREATE SYNONYM tpathFT_OHRQ FOR ',@empresa,N'.DBO.[@FT_OHRQ]');

		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathORCT') > 0 BEGIN DROP SYNONYM tpathORCT; EXEC(@pathORCT); END ELSE BEGIN exec(@pathORCT); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathRCT2') > 0 BEGIN DROP SYNONYM tpathRCT2; EXEC(@pathRCT2); END ELSE BEGIN exec(@pathRCT2); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathOINV') > 0 BEGIN DROP SYNONYM tpathOINV; EXEC(@pathOINV); END ELSE BEGIN exec(@pathOINV); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathORIN') > 0 BEGIN DROP SYNONYM tpathORIN; EXEC(@pathORIN); END ELSE BEGIN exec(@pathORIN); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathINV1') > 0 BEGIN DROP SYNONYM tpathINV1; EXEC(@pathINV1); END ELSE BEGIN exec(@pathINV1); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathRIN1') > 0 BEGIN DROP SYNONYM tpathRIN1; EXEC(@pathRIN1); END ELSE BEGIN exec(@pathRIN1); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathODPI') > 0 BEGIN DROP SYNONYM tpathODPI; EXEC(@pathODPI); END ELSE BEGIN exec(@pathODPI); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathRCT3') > 0 BEGIN DROP SYNONYM tpathRCT3; EXEC(@pathRCT3); END ELSE BEGIN exec(@pathRCT3); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathOACT') > 0 BEGIN DROP SYNONYM tpathOACT; EXEC(@pathOACT); END ELSE BEGIN exec(@pathOACT); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathFT_ORCA') > 0 BEGIN DROP SYNONYM tpathFT_ORCA; EXEC(@pathFT_ORCA); END ELSE BEGIN exec(@pathFT_ORCA); END
		IF (select COUNT(NAME) from sys.synonyms WHERE NAME = 'tpathFT_OHRQ') > 0 BEGIN DROP SYNONYM tpathFT_OHRQ; EXEC(@pathFT_OHRQ); END ELSE BEGIN exec(@pathFT_OHRQ); END
		
		
INSERT INTO [MBS].[dbo].[FLUXOR]
	SELECT 
		'CRECEBER' ORIGEM,
		@empresa BASE, 
		COALESCE(R0.BPLNAME,REPLACE(@empresa,'SBO','')) FILIAL,
		R0.DOCNUM DOCCR, 
		R2.DOCENTRY DOCNFS, 
		CASE
			WHEN R2.INVTYPE = 13 THEN V0.SERIAL
			WHEN R2.INVTYPE = 14 THEN D0.SERIAL
			WHEN R2.INVTYPE = 24 THEN 0
			WHEN R2.INVTYPE = 203 THEN 0
			ELSE 0
		END NUMNFS,
		R0.TRANSID TRANSIDCR, 
		R2.DOCTRANSID TRANSIDNFS, 
		CASE
			WHEN R2.INVTYPE = 13 THEN COALESCE(NULLIF(H1.NAME,''),'SEM_SUPERVISOR')
			WHEN R2.INVTYPE = 14 THEN COALESCE(NULLIF(H2.NAME,''),'SEM_SUPERVISOR')
			ELSE 'SEM_SUPERVISOR'
		END SUPERVISOR,	
		CASE
			WHEN DdctSumSy > 0 THEN '###DEDUCTION###'
			WHEN CashSumSy > 0 THEN 'DINHEIRO'
			WHEN CredSumSy > 0 THEN 'CARTAO'
			WHEN CheckSumSy> 0 THEN 'CHEQUE'
			WHEN TrsfrSumSy> 0 THEN 'TRANSFERENCIA'
			WHEN NoDocSumSy> 0 THEN '###NO_DOC###'
			ELSE 'X'
		END FORMA_PGTO,
		CASE
			WHEN R2.INVTYPE = 13 THEN CAST(V0.DOCDATE AS DATE)
			WHEN R2.INVTYPE = 14 THEN CAST(D0.DOCDATE AS DATE)
			WHEN R2.INVTYPE = 24 THEN CAST(R0.DOCDATE AS DATE)
			WHEN R2.INVTYPE = 203 THEN CAST(A0.DOCDATE AS DATE)
			ELSE CAST(R0.DOCDATE AS DATE)
		END DTFATNFS,
		CASE
			WHEN R2.INVTYPE = 13 THEN CAST(V0.DOCDUEDATE AS DATE)
			WHEN R2.INVTYPE = 14 THEN CAST(D0.DOCDUEDATE AS DATE)
			WHEN R2.INVTYPE = 24 THEN CAST(R0.DOCDUEDATE AS DATE)
			WHEN R2.INVTYPE = 203 THEN CAST(A0.DOCDUEDATE AS DATE)
			ELSE CAST(R0.DOCDUEDATE AS DATE)
		END DTVENCNFS,
		CAST(R0.DOCDATE AS DATE) DTRECEB, 
		R0.CARDCODE CODPN, 
		R0.CARDNAME NOMEPN, 
		CASE
			WHEN R2.INVTYPE = 13 THEN 'FAT_NFS'
			WHEN R2.INVTYPE = 14 THEN 'DEV_NFS'
			WHEN R2.INVTYPE = 24 THEN 'CONTAS_RECEBER'
			WHEN R2.INVTYPE = 203 THEN 'ADIANTAMENTO'
			ELSE R2.INVTYPE
		END TIPODOC,
		CASE
			WHEN R2.INVTYPE = 13 THEN CAST(V0.MAX1099 AS FLOAT)/V0.INSTALLMNT
			WHEN R2.INVTYPE = 14 THEN -CAST(D0.MAX1099 AS FLOAT)/D0.INSTALLMNT
			ELSE CAST(R0.DocTotalSy/(SELECT COUNT(DOCTRANSID) FROM tpathRCT2 WHERE DOCTRANSID = R2.DOCTRANSID) AS FLOAT)
		END VLRNFS,
		CASE WHEN R2.INVTYPE = 14 THEN -CAST(R2.APPLIEDSYS AS FLOAT) ELSE CAST(R2.APPLIEDSYS AS FLOAT) END VLRDOCCR,
		R2.INSTID PARCELA,
		CASE
			WHEN R2.INVTYPE = 13 THEN V0.INSTALLMNT
			WHEN R2.INVTYPE = 14 THEN D0.INSTALLMNT
			ELSE (SELECT COUNT(DOCTRANSID) FROM tpathRCT2 WHERE DOCTRANSID = R2.DOCTRANSID)
		END PARCELAS,
		CASE
			WHEN R2.INVTYPE = 13 THEN (SELECT TOP 1 V1.ACCTCODE FROM tpathINV1 V1 WHERE V1.DOCENTRY = V0.DOCENTRY)
			WHEN R2.INVTYPE = 14 THEN (SELECT TOP 1 D1.ACCTCODE FROM tpathRIN1 D1 WHERE D1.DOCENTRY = D0.DOCENTRY)
			WHEN R2.INVTYPE = 203 THEN A0.CtlAccount
			ELSE COALESCE(COALESCE(COALESCE(NULLIF(R0.CASHACCT,''),NULLIF(R0.TRSFRACCT,'')),NULLIF(R0.CHECKACCT,'')),R0.BPACT)
		END CONTACOD,
		(SELECT ACCTNAME FROM tpathOACT WHERE ACCTCODE LIKE
																		CASE
																			WHEN R2.INVTYPE = 13 THEN (SELECT TOP 1 V1.ACCTCODE FROM tpathINV1 V1 WHERE V1.DOCENTRY = V0.DOCENTRY)
																			WHEN R2.INVTYPE = 14 THEN (SELECT TOP 1 D1.ACCTCODE FROM tpathRIN1 D1 WHERE D1.DOCENTRY = D0.DOCENTRY)
																			WHEN R2.INVTYPE = 203 THEN A0.CtlAccount
																			ELSE COALESCE(COALESCE(COALESCE(NULLIF(R0.CASHACCT,''),NULLIF(R0.TRSFRACCT,'')),NULLIF(R0.CHECKACCT,'')),R0.BPACT)
																		END ) CONTANOME,
		CASE
			WHEN R2.INVTYPE = 13 THEN CONCAT(REPLACE(REPLACE(REPLACE(V0.COMMENTS,CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),' | ',V0.JrnlMemo)
			WHEN R2.INVTYPE = 14 THEN CONCAT(REPLACE(REPLACE(REPLACE(D0.COMMENTS,CHAR(13),' '),CHAR(10),' '),CHAR(9),' '),' | ',D0.JrnlMemo)
			ELSE R0.JrnlMemo
		END OBSERVACAO
	FROM 
		tpathORCT R0 INNER JOIN
		tpathRCT2 R2 ON R2.DOCNUM = R0.DOCNUM LEFT JOIN
		tpathOINV V0 ON V0.TRANSID = R2.DOCTRANSID LEFT JOIN
		tpathORIN D0 ON D0.TRANSID = R2.DOCTRANSID LEFT JOIN
		tpathODPI A0 ON A0.TRANSID = R2.DOCTRANSID LEFT JOIN
		tpathRCT3 R3 ON R3.DocNum = R0.DOCNUM left join
		tpathFT_ORCA c1 ON C1.CODE = V0.SLPCODE LEFT JOIN 
		tpathFT_ORCA c2 ON C2.CODE = D0.SLPCODE LEFT JOIN 
		tpathFT_OHRQ h1 ON c1.[U_Hierarquia] = h1.code LEFT JOIN 
		tpathFT_OHRQ h2 ON c2.[U_Hierarquia] = h2.code
	WHERE 
		YEAR(R0.DOCDATE) = 2020

end;	  

select * from [MBS].[dbo].[FLUXOR]